# Generated by Django 6.0.2 on 2026-02-15 08:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Code unique du template (ex: CLIENT_RAPIDE)', max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='Nom affiché du template', max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, help_text="Description de l'usage et du contenu du template", verbose_name='Description')),
                ('category', models.CharField(choices=[('CLIENT', 'Client/Prospect'), ('EMPLOYE', 'Employé'), ('FACTURATION', 'Facturation'), ('DOCUMENT', 'Document'), ('WORKFLOW', 'Workflow')], help_text='Catégorie du template pour le regroupement', max_length=20, verbose_name='Catégorie')),
                ('template_config', models.JSONField(help_text='\n        Configuration complète du formulaire à créer.\n        Inclut: target_model, related_models, form_schema, default_values, field_mappings\n        ', verbose_name='Configuration du template')),
                ('icon', models.CharField(blank=True, default='ph-file-text', help_text="Classe CSS de l'icône (Phosphor Icons)", max_length=50, verbose_name='Icône')),
                ('is_system', models.BooleanField(default=False, help_text='Les templates système ne peuvent pas être supprimés', verbose_name='Template système')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le template est disponible pour utilisation', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création du template', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification du template', verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Template de formulaire',
                'verbose_name_plural': 'Templates de formulaires',
                'db_table': 'modelforms_templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FormConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('code', models.CharField(db_index=True, help_text='Code unique du formulaire (ex: CLIENT_RAPIDE, NOUVEL_EMPLOYE)', max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='Nom affiché du formulaire', max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, help_text='Description détaillée du formulaire et de son usage', verbose_name='Description')),
                ('category', models.CharField(db_index=True, default='AUTRE', help_text='Catégorie du formulaire pour le regroupement (personnalisable)', max_length=50, verbose_name='Catégorie')),
                ('target_model', models.CharField(blank=True, db_index=True, help_text='Modèle principal pour création (optionnel pour formulaires multi-modèles)', max_length=100, verbose_name='Modèle principal')),
                ('is_multi_model', models.BooleanField(default=False, help_text='Si coché, le formulaire peut collecter des données de plusieurs modèles', verbose_name='Formulaire multi-modèles')),
                ('source_models', models.JSONField(blank=True, default=list, help_text='\n        Liste des modèles utilisés dans ce formulaire.\n        Format: ["core.Client", "tva.Declaration", "salaires.Employe"]\n        ', verbose_name='Modèles sources')),
                ('related_models', models.JSONField(blank=True, default=list, help_text='\n        Liste des modèles imbriqués à créer avec le formulaire.\n        Format: [{"model": "core.Adresse", "field": "adresse_siege", "required": true}]\n        ', verbose_name='Modèles liés')),
                ('form_schema', models.JSONField(blank=True, default=dict, help_text='\n        Configuration des sections et de l\'ordre des champs.\n        Format: {\n            "sections": [\n                {"id": "identity", "title": "Identité", "fields": ["nom", "prenom"]},\n                {"id": "contact", "title": "Contact", "fields": ["email", "telephone"]}\n            ]\n        }\n        ', verbose_name='Schéma du formulaire')),
                ('default_values', models.JSONField(blank=True, default=dict, help_text='\n        Valeurs par défaut pour les champs.\n        Supporte les variables: {{today}}, {{current_user}}, {{current_user.id}}\n        Format: {"statut": "PROSPECT", "date_creation": "{{today}}"}\n        ', verbose_name='Valeurs par défaut')),
                ('validation_rules', models.JSONField(blank=True, default=list, help_text='\n        Règles de validation personnalisées.\n        Format: [\n            {"type": "required_if", "field": "tva_number", "condition": "forme_juridique == \'SA\'"},\n            {"type": "regex", "field": "ide_number", "pattern": "^CHE-\\d{3}\\.\\d{3}\\.\\d{3}$"}\n        ]\n        ', verbose_name='Règles de validation')),
                ('post_actions', models.JSONField(blank=True, default=list, help_text='\n        Actions à exécuter après la création réussie.\n        Format: [\n            {"type": "email", "template": "nouveau_client", "to": "{{responsable.email}}"},\n            {"type": "task", "title": "Vérifier le client", "assign_to": "{{current_user}}"}\n        ]\n        ', verbose_name='Actions post-soumission')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('ARCHIVED', 'Archivé')], db_index=True, default='DRAFT', help_text='Statut actuel du formulaire (Brouillon, Actif, Archivé)', max_length=20, verbose_name='Statut')),
                ('require_validation', models.BooleanField(default=False, help_text='Si coché, les soumissions doivent être validées avant création', verbose_name='Nécessite validation')),
                ('icon', models.CharField(blank=True, default='ph-file-text', help_text="Classe CSS de l'icône (Phosphor Icons)", max_length=50, verbose_name='Icône')),
                ('public_token', models.UUIDField(default=uuid.uuid4, help_text="Token unique pour l'accès public au formulaire", unique=True, verbose_name='Token public')),
                ('access_level', models.CharField(choices=[('public', 'Public – accessible sans authentification'), ('code', "Code d'accès – nécessite un code"), ('authenticated', 'Authentifié – nécessite un compte')], default='authenticated', help_text='Détermine qui peut accéder à ce formulaire', max_length=20, verbose_name="Niveau d'accès")),
                ('access_code', models.CharField(blank=True, help_text='Code requis si le niveau d\'accès est "Code d\'accès"', max_length=50, verbose_name="Code d'accès")),
                ('success_message', models.TextField(blank=True, default='Merci ! Votre formulaire a été soumis avec succès.', help_text='Message affiché après soumission réussie', verbose_name='Message de succès')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('mandats', models.ManyToManyField(blank=True, help_text='Mandats pour lesquels ce formulaire est disponible', related_name='form_configurations', to='core.mandat', verbose_name='Mandats associés')),
            ],
            options={
                'verbose_name': 'Configuration de formulaire',
                'verbose_name_plural': 'Configurations de formulaires',
                'db_table': 'modelforms_configurations',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('submitted_data', models.JSONField(help_text='Données du formulaire au format JSON', verbose_name='Données soumises')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure de soumission du formulaire', verbose_name='Date de soumission')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En traitement'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué'), ('REJECTED', 'Rejeté')], db_index=True, default='PENDING', help_text='Statut de traitement de la soumission', max_length=20, verbose_name='Statut')),
                ('created_records', models.JSONField(blank=True, default=list, help_text='\n        Liste des enregistrements créés.\n        Format: [{"model": "core.Client", "id": "uuid-...", "repr": "Dupont SA"}]\n        ', verbose_name='Enregistrements créés')),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur en cas d'échec du traitement", verbose_name="Message d'erreur")),
                ('error_details', models.JSONField(blank=True, default=dict, help_text="Informations techniques détaillées sur l'erreur", verbose_name="Détails de l'erreur")),
                ('validated_at', models.DateTimeField(blank=True, help_text='Date et heure de validation de la soumission', null=True, verbose_name='Date de validation')),
                ('validation_notes', models.TextField(blank=True, help_text='Commentaires du validateur sur cette soumission', verbose_name='Notes de validation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('form_config', models.ForeignKey(help_text='Configuration de formulaire utilisée pour cette soumission', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='modelforms.formconfiguration', verbose_name='Configuration')),
                ('mandat', models.ForeignKey(blank=True, help_text='Mandat associé (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='core.mandat', verbose_name='Mandat')),
                ('submitted_by', models.ForeignKey(blank=True, help_text='Utilisateur ayant soumis le formulaire (null pour soumissions anonymes)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='form_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Soumis par')),
                ('validated_by', models.ForeignKey(blank=True, help_text='Utilisateur ayant validé la soumission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_validations', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Soumission de formulaire',
                'verbose_name_plural': 'Soumissions de formulaires',
                'db_table': 'modelforms_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelFieldMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_model', models.CharField(default='', help_text="Modèle Django d'où provient le champ (ex: core.Client, tva.Declaration)", max_length=100, verbose_name='Modèle source')),
                ('field_name', models.CharField(help_text='Nom du champ dans le modèle Django', max_length=100, verbose_name='Nom du champ')),
                ('field_path', models.CharField(blank=True, help_text='Pour les champs imbriqués via relation: adresse_siege.rue', max_length=200, verbose_name='Chemin du champ')),
                ('widget_type', models.CharField(choices=[('text', 'Texte'), ('textarea', 'Zone de texte'), ('email', 'Email'), ('phone', 'Téléphone'), ('number', 'Nombre'), ('decimal', 'Décimal'), ('currency', 'Montant'), ('date', 'Date'), ('datetime', 'Date et heure'), ('time', 'Heure'), ('select', 'Liste déroulante'), ('radio', 'Boutons radio'), ('checkbox', 'Case à cocher'), ('autocomplete', 'Autocomplete'), ('file', 'Fichier'), ('image', 'Image'), ('iban', 'IBAN'), ('avs', 'Numéro AVS'), ('ide', 'Numéro IDE'), ('country', 'Pays'), ('canton', 'Canton'), ('hidden', 'Caché')], default='text', help_text="Type de composant d'interface pour ce champ", max_length=20, verbose_name='Type de widget')),
                ('label', models.CharField(blank=True, help_text='Label personnalisé (laissez vide pour utiliser le verbose_name)', max_length=200, verbose_name='Label')),
                ('help_text', models.CharField(blank=True, help_text='Texte explicatif affiché sous le champ', max_length=500, verbose_name="Texte d'aide")),
                ('placeholder', models.CharField(blank=True, help_text='Texte indicatif affiché quand le champ est vide', max_length=200, verbose_name='Placeholder')),
                ('required', models.BooleanField(default=None, help_text='Null = utiliser la valeur du modèle', null=True, verbose_name='Obligatoire')),
                ('min_value', models.CharField(blank=True, help_text='Valeur minimum autorisée pour les champs numériques', max_length=50, verbose_name='Valeur minimum')),
                ('max_value', models.CharField(blank=True, help_text='Valeur maximum autorisée pour les champs numériques', max_length=50, verbose_name='Valeur maximum')),
                ('min_length', models.PositiveIntegerField(blank=True, help_text='Nombre minimum de caractères pour les champs texte', null=True, verbose_name='Longueur minimum')),
                ('max_length', models.PositiveIntegerField(blank=True, help_text='Nombre maximum de caractères pour les champs texte', null=True, verbose_name='Longueur maximum')),
                ('regex_pattern', models.CharField(blank=True, help_text='Expression régulière pour validation', max_length=500, verbose_name='Pattern regex')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='\n        Conditions de visibilité du champ.\n        Format: {"visible_if": {"field": "forme_juridique", "operator": "in", "value": ["SA", "SARL"]}}\n        ', verbose_name='Conditions')),
                ('order', models.PositiveIntegerField(default=0, help_text='Position du champ dans le formulaire (0 = premier)', verbose_name="Ordre d'affichage")),
                ('section', models.CharField(blank=True, help_text='ID de la section dans form_schema', max_length=50, verbose_name='Section')),
                ('options', models.JSONField(blank=True, default=dict, help_text='\n        Options spécifiques au widget.\n        Ex pour autocomplete: {"endpoint": "/api/v1/core/clients/", "display_field": "raison_sociale"}\n        ', verbose_name='Options')),
                ('form_config', models.ForeignKey(help_text='Configuration de formulaire à laquelle appartient ce mapping', on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='modelforms.formconfiguration', verbose_name='Configuration')),
            ],
            options={
                'verbose_name': 'Mapping de champ',
                'verbose_name_plural': 'Mappings de champs',
                'db_table': 'modelforms_field_mappings',
                'ordering': ['form_config', 'order', 'field_name'],
            },
        ),
        migrations.AddIndex(
            model_name='formconfiguration',
            index=models.Index(fields=['code'], name='modelforms__code_cfae23_idx'),
        ),
        migrations.AddIndex(
            model_name='formconfiguration',
            index=models.Index(fields=['target_model', 'status'], name='modelforms__target__29f220_idx'),
        ),
        migrations.AddIndex(
            model_name='formconfiguration',
            index=models.Index(fields=['category', 'status'], name='modelforms__categor_953fa2_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['form_config', 'status'], name='modelforms__form_co_5bd689_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['submitted_by', 'submitted_at'], name='modelforms__submitt_258ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['status', 'submitted_at'], name='modelforms__status_879c0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modelfieldmapping',
            unique_together={('form_config', 'source_model', 'field_name', 'field_path')},
        ),
    ]
