# Generated by Django 6.0.3 on 2026-04-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelforms', '0002_langue_saisie'),
    ]

    operations = [
        migrations.AddField(
            model_name='formconfiguration',
            name='description_de',
            field=models.TextField(blank=True, help_text='Description détaillée du formulaire et de son usage', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='formconfiguration',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description détaillée du formulaire et de son usage', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='formconfiguration',
            name='description_fr',
            field=models.TextField(blank=True, help_text='Description détaillée du formulaire et de son usage', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='formconfiguration',
            name='description_it',
            field=models.TextField(blank=True, help_text='Description détaillée du formulaire et de son usage', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='formconfiguration',
            name='name_de',
            field=models.CharField(help_text='Nom affiché du formulaire', max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='formconfiguration',
            name='name_en',
            field=models.CharField(help_text='Nom affiché du formulaire', max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='formconfiguration',
            name='name_fr',
            field=models.CharField(help_text='Nom affiché du formulaire', max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='formconfiguration',
            name='name_it',
            field=models.CharField(help_text='Nom affiché du formulaire', max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='formconfiguration',
            name='success_message_de',
            field=models.TextField(blank=True, default='Merci ! Votre formulaire a été soumis avec succès.', help_text='Message affiché après soumission réussie', null=True, verbose_name='Message de succès'),
        ),
        migrations.AddField(
            model_name='formconfiguration',
            name='success_message_en',
            field=models.TextField(blank=True, default='Merci ! Votre formulaire a été soumis avec succès.', help_text='Message affiché après soumission réussie', null=True, verbose_name='Message de succès'),
        ),
        migrations.AddField(
            model_name='formconfiguration',
            name='success_message_fr',
            field=models.TextField(blank=True, default='Merci ! Votre formulaire a été soumis avec succès.', help_text='Message affiché après soumission réussie', null=True, verbose_name='Message de succès'),
        ),
        migrations.AddField(
            model_name='formconfiguration',
            name='success_message_it',
            field=models.TextField(blank=True, default='Merci ! Votre formulaire a été soumis avec succès.', help_text='Message affiché après soumission réussie', null=True, verbose_name='Message de succès'),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='description_de',
            field=models.TextField(blank=True, help_text="Description de l'usage et du contenu du template", null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='description_en',
            field=models.TextField(blank=True, help_text="Description de l'usage et du contenu du template", null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='description_fr',
            field=models.TextField(blank=True, help_text="Description de l'usage et du contenu du template", null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='description_it',
            field=models.TextField(blank=True, help_text="Description de l'usage et du contenu du template", null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='name_de',
            field=models.CharField(help_text='Nom affiché du template', max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='name_en',
            field=models.CharField(help_text='Nom affiché du template', max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='name_fr',
            field=models.CharField(help_text='Nom affiché du template', max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='name_it',
            field=models.CharField(help_text='Nom affiché du template', max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='modelfieldmapping',
            name='help_text_de',
            field=models.CharField(blank=True, help_text='Texte explicatif affiché sous le champ', max_length=500, null=True, verbose_name="Texte d'aide"),
        ),
        migrations.AddField(
            model_name='modelfieldmapping',
            name='help_text_en',
            field=models.CharField(blank=True, help_text='Texte explicatif affiché sous le champ', max_length=500, null=True, verbose_name="Texte d'aide"),
        ),
        migrations.AddField(
            model_name='modelfieldmapping',
            name='help_text_fr',
            field=models.CharField(blank=True, help_text='Texte explicatif affiché sous le champ', max_length=500, null=True, verbose_name="Texte d'aide"),
        ),
        migrations.AddField(
            model_name='modelfieldmapping',
            name='help_text_it',
            field=models.CharField(blank=True, help_text='Texte explicatif affiché sous le champ', max_length=500, null=True, verbose_name="Texte d'aide"),
        ),
        migrations.AddField(
            model_name='modelfieldmapping',
            name='label_de',
            field=models.CharField(blank=True, help_text='Label personnalisé (laissez vide pour utiliser le verbose_name)', max_length=200, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='modelfieldmapping',
            name='label_en',
            field=models.CharField(blank=True, help_text='Label personnalisé (laissez vide pour utiliser le verbose_name)', max_length=200, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='modelfieldmapping',
            name='label_fr',
            field=models.CharField(blank=True, help_text='Label personnalisé (laissez vide pour utiliser le verbose_name)', max_length=200, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='modelfieldmapping',
            name='label_it',
            field=models.CharField(blank=True, help_text='Label personnalisé (laissez vide pour utiliser le verbose_name)', max_length=200, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='modelfieldmapping',
            name='placeholder_de',
            field=models.CharField(blank=True, help_text='Texte indicatif affiché quand le champ est vide', max_length=200, null=True, verbose_name='Placeholder'),
        ),
        migrations.AddField(
            model_name='modelfieldmapping',
            name='placeholder_en',
            field=models.CharField(blank=True, help_text='Texte indicatif affiché quand le champ est vide', max_length=200, null=True, verbose_name='Placeholder'),
        ),
        migrations.AddField(
            model_name='modelfieldmapping',
            name='placeholder_fr',
            field=models.CharField(blank=True, help_text='Texte indicatif affiché quand le champ est vide', max_length=200, null=True, verbose_name='Placeholder'),
        ),
        migrations.AddField(
            model_name='modelfieldmapping',
            name='placeholder_it',
            field=models.CharField(blank=True, help_text='Texte indicatif affiché quand le champ est vide', max_length=200, null=True, verbose_name='Placeholder'),
        ),
    ]
