# Generated by Django 6.0.3 on 2026-04-05 22:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_periodicite_description_de_and_more'),
        ('modelforms', '0003_formconfiguration_description_de_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('langue_saisie', models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie')),
                ('code', models.CharField(db_index=True, help_text='Code metier du processus (ex: ONBOARDING_CLIENT). Unique par version.', max_length=50, verbose_name='Code')),
                ('name', models.CharField(help_text='Nom affiche du processus', max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, help_text='Description metier du processus', verbose_name='Description')),
                ('category', models.CharField(choices=[('CLIENT', 'Client/Prospect'), ('FACTURATION', 'Facturation'), ('SALAIRE', 'Salaires'), ('TVA', 'TVA'), ('DOCUMENT', 'Document'), ('WORKFLOW', 'Workflow generique'), ('AUTRE', 'Autre')], db_index=True, default='WORKFLOW', max_length=50, verbose_name='Categorie')),
                ('version', models.PositiveIntegerField(default=1, help_text='Numero de version du processus. Incremente a chaque publication.', verbose_name='Version')),
                ('is_draft', models.BooleanField(db_index=True, default=True, help_text='Si coche, le processus est en edition et ne peut pas etre declenche.', verbose_name='Brouillon')),
                ('icon', models.CharField(default='ph-flow-arrow', help_text="Classe CSS de l'icone (Phosphor Icons)", max_length=50, verbose_name='Icone')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('mandats', models.ManyToManyField(blank=True, help_text='Mandats pour lesquels ce processus est disponible. Si vide, le processus est global (visible par tous).', related_name='process_definitions', to='core.mandat', verbose_name='Mandats associes')),
            ],
            options={
                'verbose_name': 'Definition de processus',
                'verbose_name_plural': 'Definitions de processus',
                'db_table': 'modelforms_process_definitions',
                'ordering': ['category', 'name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('langue_saisie', models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie')),
                ('code', models.CharField(help_text='Code unique du step dans le processus (ex: STEP_01_COLLECTE)', max_length=50, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('step_type', models.CharField(choices=[('FORM_FILL', 'Remplir un formulaire'), ('DOCUMENT_UPLOAD', 'Uploader un document'), ('HUMAN_APPROVAL', 'Validation humaine'), ('CALCULATION', 'Calcul'), ('CREATE_OBJECT', 'Creer un objet'), ('SEND_EMAIL', 'Envoyer un email'), ('SEND_NOTIFICATION', 'Envoyer une notification'), ('CREATE_TASK', 'Creer une tache'), ('WEBHOOK', 'Appel HTTP externe'), ('CONDITIONAL', 'Branche conditionnelle'), ('LOOP', 'Boucle sur collection'), ('WAIT', 'Attendre'), ('START', 'Debut du processus'), ('END', 'Fin du processus')], db_index=True, max_length=30, verbose_name="Type d'etape")),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Configuration specifique au type d\'etape. Ex FORM_FILL: {"form_config_code": "CLIENT_RAPIDE"}. Ex SEND_EMAIL: {"template": "NOUVEAU_CLIENT", "to": "{{record.email}}"}', verbose_name='Configuration')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Conditions d\'execution du step (ex: {"variable": "x", "operator": "==", "value": "y"})', verbose_name='Conditions')),
                ('max_retries', models.PositiveIntegerField(default=0, verbose_name='Max retries')),
                ('retry_delay_seconds', models.PositiveIntegerField(default=60, verbose_name='Delai entre retries (secondes)')),
                ('timeout_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Timeout (secondes)')),
                ('position_x', models.FloatField(default=0, verbose_name='Position X')),
                ('position_y', models.FloatField(default=0, verbose_name='Position Y')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='modelforms.processdefinition', verbose_name='Processus')),
            ],
            options={
                'verbose_name': 'Etape de processus',
                'verbose_name_plural': 'Etapes de processus',
                'db_table': 'modelforms_process_steps',
                'ordering': ['process', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('langue_saisie', models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('WAITING', "En attente d'action humaine"), ('COMPLETED', 'Termine'), ('FAILED', 'Echec'), ('CANCELLED', 'Annule')], db_index=True, default='PENDING', max_length=20, verbose_name='Statut')),
                ('variables', models.JSONField(blank=True, default=dict, help_text="Variables accumulees pendant l'execution du processus.", verbose_name='Variables')),
                ('trigger_type', models.CharField(default='MANUAL', help_text='MANUAL, WEBHOOK, CRON, SIGNAL, etc.', max_length=30, verbose_name='Type de declenchement')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('mandat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_instances', to='core.mandat', verbose_name='Mandat')),
                ('process_def', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='modelforms.processdefinition', verbose_name='Definition')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_process_instances', to=settings.AUTH_USER_MODEL, verbose_name='Declenche par')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='modelforms.processstep', verbose_name='Etape courante')),
            ],
            options={
                'verbose_name': 'Instance de processus',
                'verbose_name_plural': 'Instances de processus',
                'db_table': 'modelforms_process_instances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('langue_saisie', models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie')),
                ('label', models.CharField(blank=True, help_text='Libelle affiche sur l\'arete (ex: "si approuve")', max_length=100, verbose_name='Libelle')),
                ('condition', models.JSONField(blank=True, default=dict, help_text='Condition JSON. Vide = transition inconditionnelle.', verbose_name='Condition')),
                ('order', models.PositiveIntegerField(default=0, help_text="Si plusieurs transitions sortantes, evaluees dans l'ordre croissant.", verbose_name="Ordre d'evaluation")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('from_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='modelforms.processstep', verbose_name='Depuis')),
                ('to_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='modelforms.processstep', verbose_name='Vers')),
            ],
            options={
                'verbose_name': 'Transition de processus',
                'verbose_name_plural': 'Transitions de processus',
                'db_table': 'modelforms_process_transitions',
                'ordering': ['from_step', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StepExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('langue_saisie', models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('WAITING', "En attente d'action humaine"), ('COMPLETED', 'Termine'), ('FAILED', 'Echec'), ('SKIPPED', 'Ignore')], db_index=True, default='PENDING', max_length=20, verbose_name='Statut')),
                ('input', models.JSONField(blank=True, default=dict, verbose_name="Input (variables a l'entree)")),
                ('output', models.JSONField(blank=True, default=dict, verbose_name='Output (variables produites)')),
                ('logs', models.TextField(blank=True, help_text="Logs d'execution (stdout/stderr/events)", verbose_name='Logs')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retries_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('form_submission', models.ForeignKey(blank=True, help_text='Si le step est de type FORM_FILL, reference la FormSubmission creee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_executions', to='modelforms.formsubmission', verbose_name='Soumission liee')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='modelforms.processinstance', verbose_name='Instance')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='modelforms.processstep', verbose_name='Step')),
            ],
            options={
                'verbose_name': "Execution d'etape",
                'verbose_name_plural': "Executions d'etapes",
                'db_table': 'modelforms_step_executions',
                'ordering': ['instance', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='processdefinition',
            index=models.Index(fields=['code', 'version'], name='modelforms__code_4bd483_idx'),
        ),
        migrations.AddIndex(
            model_name='processdefinition',
            index=models.Index(fields=['category', 'is_draft'], name='modelforms__categor_afd353_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processdefinition',
            unique_together={('code', 'version')},
        ),
        migrations.AddIndex(
            model_name='processstep',
            index=models.Index(fields=['process', 'step_type'], name='modelforms__process_3cad21_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processstep',
            unique_together={('process', 'code')},
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['process_def', 'status'], name='modelforms__process_4fddf5_idx'),
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['mandat', 'status'], name='modelforms__mandat__db1943_idx'),
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['status', 'created_at'], name='modelforms__status_a32ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='processtransition',
            index=models.Index(fields=['from_step', 'order'], name='modelforms__from_st_9bdb66_idx'),
        ),
        migrations.AddIndex(
            model_name='stepexecution',
            index=models.Index(fields=['instance', 'status'], name='modelforms__instanc_33e398_idx'),
        ),
        migrations.AddIndex(
            model_name='stepexecution',
            index=models.Index(fields=['step', 'status'], name='modelforms__step_id_f8bf5a_idx'),
        ),
    ]
