# Generated by Django 6.0.2 on 2026-02-15 08:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Ex: No-Reply Production, Newsletter Marketing', max_length=100, verbose_name='Nom de la configuration')),
                ('type_config', models.CharField(choices=[('SMTP', 'Envoi (SMTP)'), ('IMAP', 'Réception (IMAP)'), ('POP3', 'Réception (POP3)')], default='SMTP', max_length=10, verbose_name='Type de configuration')),
                ('usage', models.CharField(choices=[('NOREPLY', 'No-reply (transactionnel)'), ('NEWSLETTER', 'Newsletter'), ('SUPPORT', 'Support'), ('NOTIFICATIONS', 'Notifications'), ('RECEPTION', 'Réception et analyse'), ('GENERAL', 'Général')], default='GENERAL', max_length=20, verbose_name='Usage')),
                ('smtp_host', models.CharField(blank=True, help_text='Ex: smtp.gmail.com, smtp.office365.com', max_length=255, verbose_name='Serveur SMTP')),
                ('smtp_port', models.PositiveIntegerField(default=587, help_text='587 pour TLS, 465 pour SSL, 25 pour non sécurisé', verbose_name='Port SMTP')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Utiliser TLS')),
                ('smtp_use_ssl', models.BooleanField(default=False, verbose_name='Utiliser SSL')),
                ('imap_host', models.CharField(blank=True, help_text='Ex: imap.gmail.com', max_length=255, verbose_name='Serveur IMAP/POP3')),
                ('imap_port', models.PositiveIntegerField(default=993, verbose_name='Port IMAP/POP3')),
                ('imap_use_ssl', models.BooleanField(default=True, verbose_name='Utiliser SSL pour IMAP')),
                ('imap_dossier', models.CharField(blank=True, default='INBOX', max_length=100, verbose_name='Dossier à surveiller')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('username', models.CharField(help_text="Généralement identique à l'adresse email", max_length=255, verbose_name="Nom d'utilisateur")),
                ('password', models.TextField(help_text="Mot de passe ou mot de passe d'application", verbose_name='Mot de passe')),
                ('from_name', models.CharField(blank=True, help_text='Ex: AltiusOne Support', max_length=100, verbose_name="Nom d'expéditeur")),
                ('reply_to', models.EmailField(blank=True, help_text="Si différente de l'adresse d'envoi", max_length=254, verbose_name='Adresse de réponse')),
                ('analyse_ai_activee', models.BooleanField(default=False, help_text="Analyser automatiquement les emails reçus avec l'IA", verbose_name="Activer l'analyse IA")),
                ('extraire_pieces_jointes', models.BooleanField(default=False, help_text='Sauvegarder automatiquement les pièces jointes', verbose_name='Extraire les pièces jointes')),
                ('est_defaut', models.BooleanField(default=False, verbose_name='Configuration par défaut')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Configuration email',
                'verbose_name_plural': 'Configurations email',
                'db_table': 'configurations_email',
                'ordering': ['-est_defaut', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TemplateEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Identifiant unique (ex: INVITATION_STAFF)', max_length=50, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('type_template', models.CharField(choices=[('INVITATION', 'Invitation'), ('PASSWORD_RESET', 'Réinitialisation mot de passe'), ('WELCOME', 'Bienvenue'), ('NOTIFICATION', 'Notification'), ('RAPPEL', 'Rappel'), ('FACTURE', 'Facture'), ('RAPPORT', 'Rapport'), ('CUSTOM', 'Personnalisé')], default='CUSTOM', max_length=20, verbose_name='Type')),
                ('sujet', models.CharField(help_text='Supporte les variables: {{nom}}, {{entreprise}}, etc.', max_length=255, verbose_name='Sujet')),
                ('corps_html', models.TextField(verbose_name='Contenu HTML')),
                ('corps_texte', models.TextField(blank=True, help_text='Version texte brut (optionnel)', verbose_name='Contenu texte')),
                ('variables_disponibles', models.JSONField(blank=True, default=list, help_text='Liste des variables: ["nom", "email", "lien"]', verbose_name='Variables disponibles')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(blank=True, help_text='Configuration SMTP à utiliser', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='mailing.configurationemail', verbose_name='Configuration email')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Template email',
                'verbose_name_plural': 'Templates email',
                'db_table': 'templates_email',
                'ordering': ['type_template', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='EmailRecu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(help_text='Identifiant unique du serveur', max_length=500, unique=True, verbose_name='Message-ID')),
                ('expediteur', models.EmailField(max_length=254, verbose_name='Expéditeur')),
                ('expediteur_nom', models.CharField(blank=True, max_length=255, verbose_name="Nom de l'expéditeur")),
                ('destinataires', models.JSONField(default=list, verbose_name='Destinataires')),
                ('destinataires_cc', models.JSONField(blank=True, default=list, verbose_name='CC')),
                ('sujet', models.CharField(max_length=500, verbose_name='Sujet')),
                ('corps_html', models.TextField(blank=True, verbose_name='Contenu HTML')),
                ('corps_texte', models.TextField(blank=True, verbose_name='Contenu texte')),
                ('pieces_jointes', models.JSONField(blank=True, default=list, help_text='[{"nom": "doc.pdf", "taille": 1024, "type": "application/pdf", "path": "..."}]', verbose_name='Pièces jointes')),
                ('date_reception', models.DateTimeField(verbose_name='Date de réception')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('statut', models.CharField(choices=[('NON_LU', 'Non lu'), ('LU', 'Lu'), ('TRAITE', 'Traité'), ('ARCHIVE', 'Archivé'), ('SPAM', 'Spam')], db_index=True, default='NON_LU', max_length=20, verbose_name='Statut')),
                ('est_important', models.BooleanField(default=False, verbose_name='Important')),
                ('analyse_effectuee', models.BooleanField(default=False, verbose_name='Analyse IA effectuée')),
                ('analyse_resultat', models.JSONField(blank=True, default=dict, help_text='{"type": "demande_info", "urgence": "haute", "resume": "...", "actions": [...]}', verbose_name="Résultat de l'analyse")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_detecte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_recus', to='core.client', verbose_name='Client détecté')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_recus', to='mailing.configurationemail', verbose_name='Configuration')),
                ('mandat_detecte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_recus', to='core.mandat', verbose_name='Mandat détecté')),
            ],
            options={
                'verbose_name': 'Email reçu',
                'verbose_name_plural': 'Emails reçus',
                'db_table': 'emails_recus',
                'ordering': ['-date_reception'],
                'indexes': [models.Index(fields=['expediteur', 'statut'], name='emails_recu_expedit_d44f17_idx'), models.Index(fields=['date_reception'], name='emails_recu_date_re_81b8d9_idx'), models.Index(fields=['configuration', 'statut'], name='emails_recu_configu_9b4f5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailEnvoye',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destinataire', models.EmailField(max_length=254, verbose_name='Destinataire')),
                ('destinataires_cc', models.JSONField(blank=True, default=list, verbose_name='CC')),
                ('destinataires_bcc', models.JSONField(blank=True, default=list, verbose_name='BCC')),
                ('sujet', models.CharField(max_length=255, verbose_name='Sujet')),
                ('corps_html', models.TextField(verbose_name='Contenu HTML')),
                ('corps_texte', models.TextField(blank=True, verbose_name='Contenu texte')),
                ('pieces_jointes', models.JSONField(blank=True, default=list, help_text='[{"nom": "doc.pdf", "path": "/path/to/file"}]', verbose_name='Pièces jointes')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYE', 'Envoyé'), ('ECHEC', 'Échec'), ('BOUNCE', 'Bounce')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('erreur', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('tentatives', models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de tentatives')),
                ('content_type', models.CharField(blank=True, help_text='Ex: facture, invitation, rappel', max_length=100, verbose_name='Type de contenu')),
                ('object_id', models.CharField(blank=True, help_text="UUID de l'objet associé", max_length=50, verbose_name="ID de l'objet")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_envoyes', to='mailing.configurationemail', verbose_name='Configuration utilisée')),
                ('mandat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_envoyes', to='core.mandat', verbose_name='Mandat associé')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='Envoyé par')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_envoyes', to='mailing.templateemail', verbose_name='Template utilisé')),
            ],
            options={
                'verbose_name': 'Email envoyé',
                'verbose_name_plural': 'Emails envoyés',
                'db_table': 'emails_envoyes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destinataire', 'statut'], name='emails_envo_destina_426faa_idx'), models.Index(fields=['created_at'], name='emails_envo_created_7fa5dd_idx')],
            },
        ),
    ]
