# Generated by Django 6.0.2 on 2026-02-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_create_tache_assignation_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationemail',
            name='username',
            field=models.EmailField(help_text="Adresse email d'authentification SMTP/IMAP", max_length=254, verbose_name="Nom d'utilisateur"),
        ),
        migrations.AlterField(
            model_name='emailenvoye',
            name='pieces_jointes',
            field=models.JSONField(blank=True, default=list, help_text='[{"nom": "doc.pdf", "cle_s3": "abc123_doc.pdf", "taille": 1024, "type_mime": "application/pdf"}]', verbose_name='Pièces jointes'),
        ),
    ]
