# Generated by Django 6.0.3 on 2026-04-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_change_username_to_emailfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationemail',
            name='nom_de',
            field=models.CharField(help_text='Ex: No-Reply Production, Newsletter Marketing', max_length=100, null=True, verbose_name='Nom de la configuration'),
        ),
        migrations.AddField(
            model_name='configurationemail',
            name='nom_en',
            field=models.CharField(help_text='Ex: No-Reply Production, Newsletter Marketing', max_length=100, null=True, verbose_name='Nom de la configuration'),
        ),
        migrations.AddField(
            model_name='configurationemail',
            name='nom_fr',
            field=models.CharField(help_text='Ex: No-Reply Production, Newsletter Marketing', max_length=100, null=True, verbose_name='Nom de la configuration'),
        ),
        migrations.AddField(
            model_name='configurationemail',
            name='nom_it',
            field=models.CharField(help_text='Ex: No-Reply Production, Newsletter Marketing', max_length=100, null=True, verbose_name='Nom de la configuration'),
        ),
        migrations.AddField(
            model_name='templateemail',
            name='corps_html_de',
            field=models.TextField(null=True, verbose_name='Contenu HTML'),
        ),
        migrations.AddField(
            model_name='templateemail',
            name='corps_html_en',
            field=models.TextField(null=True, verbose_name='Contenu HTML'),
        ),
        migrations.AddField(
            model_name='templateemail',
            name='corps_html_fr',
            field=models.TextField(null=True, verbose_name='Contenu HTML'),
        ),
        migrations.AddField(
            model_name='templateemail',
            name='corps_html_it',
            field=models.TextField(null=True, verbose_name='Contenu HTML'),
        ),
        migrations.AddField(
            model_name='templateemail',
            name='corps_texte_de',
            field=models.TextField(blank=True, help_text='Version texte brut (optionnel)', null=True, verbose_name='Contenu texte'),
        ),
        migrations.AddField(
            model_name='templateemail',
            name='corps_texte_en',
            field=models.TextField(blank=True, help_text='Version texte brut (optionnel)', null=True, verbose_name='Contenu texte'),
        ),
        migrations.AddField(
            model_name='templateemail',
            name='corps_texte_fr',
            field=models.TextField(blank=True, help_text='Version texte brut (optionnel)', null=True, verbose_name='Contenu texte'),
        ),
        migrations.AddField(
            model_name='templateemail',
            name='corps_texte_it',
            field=models.TextField(blank=True, help_text='Version texte brut (optionnel)', null=True, verbose_name='Contenu texte'),
        ),
        migrations.AddField(
            model_name='templateemail',
            name='nom_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom du template'),
        ),
        migrations.AddField(
            model_name='templateemail',
            name='nom_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom du template'),
        ),
        migrations.AddField(
            model_name='templateemail',
            name='nom_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom du template'),
        ),
        migrations.AddField(
            model_name='templateemail',
            name='nom_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom du template'),
        ),
        migrations.AddField(
            model_name='templateemail',
            name='sujet_de',
            field=models.CharField(help_text='Supporte les variables: {{nom}}, {{entreprise}}, etc.', max_length=255, null=True, verbose_name='Sujet'),
        ),
        migrations.AddField(
            model_name='templateemail',
            name='sujet_en',
            field=models.CharField(help_text='Supporte les variables: {{nom}}, {{entreprise}}, etc.', max_length=255, null=True, verbose_name='Sujet'),
        ),
        migrations.AddField(
            model_name='templateemail',
            name='sujet_fr',
            field=models.CharField(help_text='Supporte les variables: {{nom}}, {{entreprise}}, etc.', max_length=255, null=True, verbose_name='Sujet'),
        ),
        migrations.AddField(
            model_name='templateemail',
            name='sujet_it',
            field=models.CharField(help_text='Supporte les variables: {{nom}}, {{entreprise}}, etc.', max_length=255, null=True, verbose_name='Sujet'),
        ),
    ]
