# Generated by Django 6.0.1 on 2026-01-10 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_user_contact_lie_user_doit_changer_mot_de_passe_and_more'),
        ('documents', '0008_rename_conv_user_statut_idx_conversatio_utilisa_adc1dd_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCollaboratif',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('docs_id', models.CharField(help_text="Identifiant du document dans l'instance Docs", max_length=255, unique=True, verbose_name='ID Docs')),
                ('titre', models.CharField(max_length=500, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type_document', models.CharField(choices=[('NOTE', 'Note'), ('RAPPORT', 'Rapport'), ('PV', 'Procès-verbal'), ('COURRIER', 'Courrier'), ('CONTRAT', 'Contrat'), ('MEMO', 'Mémo interne'), ('DOC', 'Documentation'), ('WIKI', 'Wiki'), ('AUTRE', 'Autre')], default='NOTE', max_length=20, verbose_name='Type de document')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_COURS', 'En cours de rédaction'), ('REVISION', 'En révision'), ('VALIDE', 'Validé'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('est_public', models.BooleanField(default=False, help_text='Si activé, tous les utilisateurs du mandat peuvent voir ce document', verbose_name='Public dans le mandat')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('date_derniere_edition', models.DateTimeField(blank=True, help_text='Mise à jour via webhook depuis Docs', null=True, verbose_name='Dernière édition collaborative')),
                ('nombre_collaborateurs', models.PositiveIntegerField(default=1, verbose_name='Nombre de collaborateurs')),
                ('nombre_versions', models.PositiveIntegerField(default=1, verbose_name='Nombre de versions')),
                ('taille_contenu', models.PositiveIntegerField(default=0, verbose_name='Taille du contenu (caractères)')),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('de', 'Deutsch'), ('it', 'Italiano'), ('en', 'English')], default='fr', max_length=5, verbose_name='Langue')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_collaboratifs', to='core.client', verbose_name='Client')),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_collaboratifs_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('document_exporte', models.ForeignKey(blank=True, help_text='Version PDF/Word archivée dans la GED', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_source_collaboratif', to='documents.document', verbose_name='Document exporté')),
                ('dossier', models.ForeignKey(blank=True, help_text='Dossier de classement dans la GED', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_collaboratifs', to='documents.dossier', verbose_name='Dossier GED')),
                ('mandat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_collaboratifs', to='core.mandat', verbose_name='Mandat')),
            ],
            options={
                'verbose_name': 'Document collaboratif',
                'verbose_name_plural': 'Documents collaboratifs',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='LienPartagePublic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token')),
                ('permet_edition', models.BooleanField(default=False, verbose_name="Permettre l'édition")),
                ('permet_commentaire', models.BooleanField(default=True, verbose_name='Permettre les commentaires')),
                ('permet_telechargement', models.BooleanField(default=True, verbose_name='Permettre le téléchargement')),
                ('mot_de_passe_hash', models.CharField(blank=True, help_text='Laisser vide pour un accès sans mot de passe', max_length=128, verbose_name='Hash du mot de passe')),
                ('date_expiration', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('nombre_acces_max', models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre d'accès maximum")),
                ('nombre_acces', models.PositiveIntegerField(default=0, verbose_name="Nombre d'accès")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liens_publics_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_publics', to='editeur.documentcollaboratif', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Lien de partage public',
                'verbose_name_plural': 'Liens de partage publics',
            },
        ),
        migrations.CreateModel(
            name='ModeleDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du modèle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('categorie', models.CharField(choices=[('FIDUCIAIRE', 'Fiduciaire'), ('COMPTABLE', 'Comptabilité'), ('FISCAL', 'Fiscalité'), ('RH', 'Ressources Humaines'), ('JURIDIQUE', 'Juridique'), ('COMMERCIAL', 'Commercial'), ('INTERNE', 'Usage interne'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Catégorie')),
                ('type_document', models.CharField(choices=[('NOTE', 'Note'), ('RAPPORT', 'Rapport'), ('PV', 'Procès-verbal'), ('COURRIER', 'Courrier'), ('CONTRAT', 'Contrat'), ('MEMO', 'Mémo interne'), ('DOC', 'Documentation'), ('WIKI', 'Wiki'), ('AUTRE', 'Autre')], default='NOTE', max_length=20, verbose_name='Type de document')),
                ('contenu_json', models.JSONField(default=dict, verbose_name='Contenu (BlockNote JSON)')),
                ('apercu_html', models.TextField(blank=True, verbose_name='Aperçu HTML')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('est_public', models.BooleanField(default=False, help_text='Visible par tous les utilisateurs', verbose_name='Public')),
                ('est_systeme', models.BooleanField(default=False, help_text='Modèle fourni par AltiusOne', verbose_name='Modèle système')),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('de', 'Deutsch'), ('it', 'Italiano'), ('en', 'English')], default='fr', max_length=5, verbose_name='Langue')),
                ('nombre_utilisations', models.PositiveIntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modeles_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Modèle de document',
                'verbose_name_plural': 'Modèles de documents',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='PartageDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('niveau_acces', models.CharField(choices=[('LECTURE', 'Lecture seule'), ('COMMENTAIRE', 'Commentaire'), ('EDITION', 'Édition'), ('ADMIN', 'Administration')], default='LECTURE', max_length=20, verbose_name="Niveau d'accès")),
                ('date_partage', models.DateTimeField(auto_now_add=True, verbose_name='Date de partage')),
                ('date_expiration', models.DateTimeField(blank=True, help_text='Laisser vide pour un accès permanent', null=True, verbose_name="Date d'expiration")),
                ('notifier_modifications', models.BooleanField(default=True, verbose_name='Notifier des modifications')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partages', to='editeur.documentcollaboratif', verbose_name='Document')),
                ('partage_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partages_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Partagé par')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_partages', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Partage de document',
                'verbose_name_plural': 'Partages de documents',
            },
        ),
        migrations.CreateModel(
            name='SessionEdition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Identifiant de connexion WebSocket', max_length=255, verbose_name='ID de session')),
                ('debut', models.DateTimeField(auto_now_add=True, verbose_name='Début de session')),
                ('derniere_activite', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin de session')),
                ('est_active', models.BooleanField(default=True, verbose_name='Session active')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_edition', to='editeur.documentcollaboratif', verbose_name='Document')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_edition', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Session d'édition",
                'verbose_name_plural': "Sessions d'édition",
            },
        ),
        migrations.CreateModel(
            name='VersionExportee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format_export', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'Word (.docx)'), ('ODT', 'OpenDocument (.odt)'), ('HTML', 'HTML'), ('MD', 'Markdown')], max_length=10, verbose_name='Format')),
                ('fichier', models.FileField(upload_to='editeur/exports/%Y/%m/', verbose_name='Fichier')),
                ('taille', models.PositiveIntegerField(default=0, verbose_name='Taille (octets)')),
                ('numero_version', models.PositiveIntegerField(default=1, verbose_name='Numéro de version')),
                ('hash_contenu', models.CharField(blank=True, help_text='SHA-256 du contenu source', max_length=64, verbose_name='Hash du contenu')),
                ('date_export', models.DateTimeField(auto_now_add=True, verbose_name="Date d'export")),
                ('notes', models.TextField(blank=True, verbose_name='Notes de version')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions_exportees', to='editeur.documentcollaboratif', verbose_name='Document')),
                ('document_ged', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions_source_editeur', to='documents.document', verbose_name='Document GED')),
                ('exporte_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports_documents', to=settings.AUTH_USER_MODEL, verbose_name='Exporté par')),
            ],
            options={
                'verbose_name': 'Version exportée',
                'verbose_name_plural': 'Versions exportées',
                'ordering': ['-date_export'],
            },
        ),
        migrations.AddIndex(
            model_name='documentcollaboratif',
            index=models.Index(fields=['docs_id'], name='editeur_doc_docs_id_7e06e8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcollaboratif',
            index=models.Index(fields=['mandat', '-date_modification'], name='editeur_doc_mandat__171b27_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcollaboratif',
            index=models.Index(fields=['client', '-date_modification'], name='editeur_doc_client__4ca8fc_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcollaboratif',
            index=models.Index(fields=['createur', '-date_modification'], name='editeur_doc_createu_089381_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcollaboratif',
            index=models.Index(fields=['statut'], name='editeur_doc_statut_7b4846_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcollaboratif',
            index=models.Index(fields=['type_document'], name='editeur_doc_type_do_de640c_idx'),
        ),
        migrations.AddIndex(
            model_name='lienpartagepublic',
            index=models.Index(fields=['token'], name='editeur_lie_token_87edda_idx'),
        ),
        migrations.AddIndex(
            model_name='lienpartagepublic',
            index=models.Index(fields=['document', 'est_actif'], name='editeur_lie_documen_df3264_idx'),
        ),
        migrations.AddIndex(
            model_name='modeledocument',
            index=models.Index(fields=['categorie'], name='editeur_mod_categor_2bf9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='modeledocument',
            index=models.Index(fields=['est_public', 'categorie'], name='editeur_mod_est_pub_0ac7fe_idx'),
        ),
        migrations.AddIndex(
            model_name='partagedocument',
            index=models.Index(fields=['utilisateur', '-date_partage'], name='editeur_par_utilisa_bd20ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partagedocument',
            unique_together={('document', 'utilisateur')},
        ),
        migrations.AddIndex(
            model_name='sessionedition',
            index=models.Index(fields=['document', 'est_active'], name='editeur_ses_documen_b6e614_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionedition',
            index=models.Index(fields=['utilisateur', 'est_active'], name='editeur_ses_utilisa_03a0ae_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionedition',
            index=models.Index(fields=['session_id'], name='editeur_ses_session_0780db_idx'),
        ),
        migrations.AddIndex(
            model_name='versionexportee',
            index=models.Index(fields=['document', '-date_export'], name='editeur_ver_documen_f85b76_idx'),
        ),
    ]
