# Generated by Django 6.0.3 on 2026-03-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editeur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeledocument',
            name='categorie',
            field=models.CharField(choices=[('FIDUCIAIRE', 'Entreprise'), ('COMPTABLE', 'Comptabilité'), ('FISCAL', 'Fiscalité'), ('RH', 'Ressources Humaines'), ('JURIDIQUE', 'Juridique'), ('COMMERCIAL', 'Commercial'), ('INTERNE', 'Usage interne'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Catégorie'),
        ),
    ]
