# Generated by Django 6.0.3 on 2026-04-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editeur', '0002_alter_modeledocument_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcollaboratif',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='documentcollaboratif',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='documentcollaboratif',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='documentcollaboratif',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='documentcollaboratif',
            name='titre_de',
            field=models.CharField(max_length=500, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='documentcollaboratif',
            name='titre_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='documentcollaboratif',
            name='titre_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='documentcollaboratif',
            name='titre_it',
            field=models.CharField(max_length=500, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='modeledocument',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='modeledocument',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='modeledocument',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='modeledocument',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='modeledocument',
            name='nom_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Nom du modèle'),
        ),
        migrations.AddField(
            model_name='modeledocument',
            name='nom_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Nom du modèle'),
        ),
        migrations.AddField(
            model_name='modeledocument',
            name='nom_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Nom du modèle'),
        ),
        migrations.AddField(
            model_name='modeledocument',
            name='nom_it',
            field=models.CharField(max_length=200, null=True, verbose_name='Nom du modèle'),
        ),
        migrations.AddField(
            model_name='versionexportee',
            name='notes_de',
            field=models.TextField(blank=True, null=True, verbose_name='Notes de version'),
        ),
        migrations.AddField(
            model_name='versionexportee',
            name='notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='Notes de version'),
        ),
        migrations.AddField(
            model_name='versionexportee',
            name='notes_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Notes de version'),
        ),
        migrations.AddField(
            model_name='versionexportee',
            name='notes_it',
            field=models.TextField(blank=True, null=True, verbose_name='Notes de version'),
        ),
    ]
