# Generated by Django 5.2.8 on 2025-11-13 00:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rue', models.CharField(max_length=255)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('complement', models.CharField(blank=True, max_length=100)),
                ('npa', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'NPA invalide (4 chiffres)')])),
                ('localite', models.CharField(max_length=100)),
                ('canton', models.CharField(choices=[('AG', 'Argovie'), ('AI', 'Appenzell Rhodes-Intérieures'), ('AR', 'Appenzell Rhodes-Extérieures'), ('BE', 'Berne'), ('BL', 'Bâle-Campagne'), ('BS', 'Bâle-Ville'), ('FR', 'Fribourg'), ('GE', 'Genève'), ('GL', 'Glaris'), ('GR', 'Grisons'), ('JU', 'Jura'), ('LU', 'Lucerne'), ('NE', 'Neuchâtel'), ('NW', 'Nidwald'), ('OW', 'Obwald'), ('SG', 'Saint-Gall'), ('SH', 'Schaffhouse'), ('SO', 'Soleure'), ('SZ', 'Schwyz'), ('TG', 'Thurgovie'), ('TI', 'Tessin'), ('UR', 'Uri'), ('VD', 'Vaud'), ('VS', 'Valais'), ('ZG', 'Zoug'), ('ZH', 'Zurich')], max_length=2)),
                ('pays', models.CharField(default='CH', max_length=2)),
            ],
            options={
                'verbose_name': 'Adresse',
                'db_table': 'adresses',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('MANAGER', 'Chef de bureau'), ('COMPTABLE', 'Comptable'), ('ASSISTANT', 'Assistant'), ('CLIENT', 'Client')], default='ASSISTANT', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('groups', models.ManyToManyField(blank=True, related_name='core_user_set', related_query_name='core_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='core_user_set', related_query_name='core_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('raison_sociale', models.CharField(db_index=True, max_length=255)),
                ('nom_commercial', models.CharField(blank=True, max_length=255)),
                ('forme_juridique', models.CharField(choices=[('EI', 'Entreprise individuelle'), ('RC', 'Raison collective'), ('SC', 'Société en commandite'), ('SARL', 'Société à responsabilité limitée'), ('SA', 'Société anonyme'), ('SC_SIMPLE', 'Société en commandite simple'), ('SC_ACTIONS', 'Société en commandite par actions'), ('COOP', 'Société coopérative'), ('ASSOC', 'Association'), ('FOND', 'Fondation')], max_length=20)),
                ('ide_number', models.CharField(help_text='Format: CHE-123.456.789', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^CHE-\\d{3}\\.\\d{3}\\.\\d{3}$', 'Format IDE invalide (CHE-XXX.XXX.XXX)')], verbose_name='Numéro IDE')),
                ('tva_number', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Numéro TVA')),
                ('rc_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro RC')),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('site_web', models.URLField(blank=True)),
                ('date_creation', models.DateField(verbose_name='Date de création entreprise')),
                ('date_inscription_rc', models.DateField(blank=True, null=True, verbose_name='Date inscription RC')),
                ('date_debut_exercice', models.DateField(verbose_name='Début exercice comptable')),
                ('date_fin_exercice', models.DateField(verbose_name='Fin exercice comptable')),
                ('statut', models.CharField(choices=[('PROSPECT', 'Prospect'), ('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('RESILIE', 'Résilié'), ('ARCHIVE', 'Archivé')], db_index=True, default='PROSPECT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('adresse_correspondance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients_correspondance', to='core.adresse')),
                ('adresse_siege', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients_siege', to='core.adresse')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'db_table': 'clients',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('civilite', models.CharField(choices=[('M', 'Monsieur'), ('MME', 'Madame'), ('DR', 'Docteur'), ('PROF', 'Professeur')], max_length=10)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('fonction', models.CharField(choices=[('DIRECTEUR', 'Directeur'), ('GERANT', 'Gérant'), ('ADMIN', 'Administrateur'), ('COMPTABLE', 'Comptable'), ('RH', 'Ressources Humaines'), ('AUTRE', 'Autre')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('principal', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact',
                'db_table': 'contacts',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='contact_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_principal', to='core.contact'),
        ),
        migrations.CreateModel(
            name='Mandat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('numero', models.CharField(db_index=True, max_length=50, unique=True)),
                ('type_mandat', models.CharField(choices=[('COMPTA', 'Comptabilité'), ('TVA', 'TVA'), ('SALAIRES', 'Salaires'), ('FISCAL', 'Conseil fiscal'), ('REVISION', 'Révision'), ('CONSEIL', 'Conseil général'), ('CREATION', 'Création entreprise'), ('GLOBAL', 'Mandat global')], db_index=True, max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('periodicite', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('SEMESTRIEL', 'Semestriel'), ('ANNUEL', 'Annuel'), ('PONCTUEL', 'Ponctuel')], max_length=20)),
                ('type_facturation', models.CharField(choices=[('FORFAIT', 'Forfait'), ('HORAIRE', 'Taux horaire'), ('MIXTE', 'Mixte')], default='HORAIRE', max_length=20)),
                ('montant_forfait', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taux_horaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='\n    {\n        "plan_comptable": "PME",\n        "methode_tva": "EFFECTIVE",\n        "periodicite_tva": "TRIMESTRIEL",\n        "cloture_mois": 12,\n        "devise": "CHF",\n        "langues": ["fr"],\n        "modules_actifs": ["compta", "tva", "salaires"]\n    }\n    ')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente validation'), ('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('TERMINE', 'Terminé'), ('RESILIE', 'Résilié')], db_index=True, default='BROUILLON', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('conditions_particulieres', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandats', to='core.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('equipe', models.ManyToManyField(blank=True, related_name='mandats_equipe', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandats_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mandat',
                'db_table': 'mandats',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ExerciceComptable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('annee', models.IntegerField(db_index=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('CLOTURE_PROVISOIRE', 'Clôture provisoire'), ('CLOTURE_DEFINITIVE', 'Clôture définitive')], db_index=True, default='OUVERT', max_length=30)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('resultat_exercice', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cloture_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mandat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='core.mandat')),
            ],
            options={
                'verbose_name': 'Exercice comptable',
                'db_table': 'exercices_comptables',
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('VIEW', 'Consultation'), ('EXPORT', 'Export'), ('VALIDATE', 'Validation'), ('SUBMIT', 'Soumission')], max_length=20)),
                ('table_name', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('object_repr', models.CharField(max_length=255)),
                ('changements', models.JSONField(blank=True, default=dict, help_text='\n    Détails des changements:\n    {\n        "before": {"field1": "old_value"},\n        "after": {"field1": "new_value"}\n    }\n    ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('mandat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mandat')),
            ],
            options={
                'verbose_name': "Log d'audit",
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('type_notification', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Succès'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur'), ('TASK', 'Tâche')], max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('lien_action', models.CharField(blank=True, max_length=500)),
                ('lien_texte', models.CharField(blank=True, max_length=100)),
                ('lue', models.BooleanField(db_index=True, default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('archivee', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('mandat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mandat')),
            ],
            options={
                'verbose_name': 'Notification',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=20)),
                ('date_echeance', models.DateField(blank=True, db_index=True, null=True)),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('EN_ATTENTE', 'En attente'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], db_index=True, default='A_FAIRE', max_length=20)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('temps_estime_heures', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temps_reel_heures', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('assigne_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taches_assignees', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taches_creees', to=settings.AUTH_USER_MODEL)),
                ('mandat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='core.mandat')),
            ],
            options={
                'verbose_name': 'Tâche',
                'db_table': 'taches',
                'ordering': ['-priorite', 'date_echeance'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['raison_sociale', 'statut'], name='clients_raison__8f868b_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['ide_number'], name='clients_ide_num_55b91d_idx'),
        ),
        migrations.AddIndex(
            model_name='mandat',
            index=models.Index(fields=['client', 'statut'], name='mandats_client__4665b1_idx'),
        ),
        migrations.AddIndex(
            model_name='mandat',
            index=models.Index(fields=['type_mandat', 'statut'], name='mandats_type_ma_e803ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exercicecomptable',
            unique_together={('mandat', 'annee')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['utilisateur', 'timestamp'], name='audit_log_utilisa_08bccc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['table_name', 'object_id'], name='audit_log_table_n_32d68b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_log_timesta_e8e14e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['destinataire', 'lue'], name='notificatio_destina_6faf8c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'),
        ),
        migrations.AddIndex(
            model_name='tache',
            index=models.Index(fields=['assigne_a', 'statut'], name='taches_assigne_3e4ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='tache',
            index=models.Index(fields=['date_echeance', 'statut'], name='taches_date_ec_1a2eb3_idx'),
        ),
    ]
