# Generated by Django 5.2.8 on 2025-11-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='description_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='notes_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='notes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='notes_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='notes_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mandat',
            name='conditions_particulieres_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mandat',
            name='conditions_particulieres_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mandat',
            name='conditions_particulieres_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mandat',
            name='conditions_particulieres_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mandat',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mandat',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mandat',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mandat',
            name='description_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='lien_texte_de',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='lien_texte_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='lien_texte_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='lien_texte_it',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='titre_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='titre_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='titre_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='titre_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='description_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='titre_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='titre_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='titre_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='titre_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='forme_juridique',
            field=models.CharField(choices=[('EI', 'Entreprise individuelle'), ('RC', 'Raison collective'), ('SC', 'Société en commandite'), ('SNC', 'Société en nom collectif'), ('SARL', 'Société à responsabilité limitée'), ('SA', 'Société anonyme'), ('SC_SIMPLE', 'Société en commandite simple'), ('SC_ACTIONS', 'Société en commandite par actions'), ('COOP', 'Société coopérative'), ('ASSOC', 'Association'), ('FOND', 'Fondation')], max_length=20),
        ),
    ]
