# Generated by Django 6.0.2 on 2026-02-20 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_migrate_client_addresses_remove_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptebancaire',
            name='devise',
            field=models.ForeignKey(db_column='devise', default='CHF', on_delete=django.db.models.deletion.PROTECT, to='core.devise', verbose_name='Devise'),
        ),
    ]
