# Generated by Django 5.2.8 on 2025-11-19 09:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_client_description_client_description_de_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adresse',
            options={'verbose_name': 'Adresse', 'verbose_name_plural': 'Adresses'},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': "Log d'audit", 'verbose_name_plural': "Logs d'audit"},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['raison_sociale'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='exercicecomptable',
            options={'ordering': ['-annee'], 'verbose_name': 'Exercice comptable', 'verbose_name_plural': 'Exercices comptables'},
        ),
        migrations.AlterModelOptions(
            name='mandat',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Mandat', 'verbose_name_plural': 'Mandats'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='tache',
            options={'ordering': ['-priorite', 'date_echeance'], 'verbose_name': 'Tâche', 'verbose_name_plural': 'Tâches'},
        ),
        migrations.AlterField(
            model_name='adresse',
            name='canton',
            field=models.CharField(choices=[('AG', 'Argovie'), ('AI', 'Appenzell Rhodes-Intérieures'), ('AR', 'Appenzell Rhodes-Extérieures'), ('BE', 'Berne'), ('BL', 'Bâle-Campagne'), ('BS', 'Bâle-Ville'), ('FR', 'Fribourg'), ('GE', 'Genève'), ('GL', 'Glaris'), ('GR', 'Grisons'), ('JU', 'Jura'), ('LU', 'Lucerne'), ('NE', 'Neuchâtel'), ('NW', 'Nidwald'), ('OW', 'Obwald'), ('SG', 'Saint-Gall'), ('SH', 'Schaffhouse'), ('SO', 'Soleure'), ('SZ', 'Schwyz'), ('TG', 'Thurgovie'), ('TI', 'Tessin'), ('UR', 'Uri'), ('VD', 'Vaud'), ('VS', 'Valais'), ('ZG', 'Zoug'), ('ZH', 'Zurich')], max_length=2, verbose_name='Canton'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='complement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complément'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='localite',
            field=models.CharField(max_length=100, verbose_name='Localité'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='npa',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'NPA invalide (4 chiffres)')], verbose_name='NPA'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='pays',
            field=models.CharField(default='CH', max_length=2, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='rue',
            field=models.CharField(max_length=255, verbose_name='Rue'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('VIEW', 'Consultation'), ('EXPORT', 'Export'), ('VALIDATE', 'Validation'), ('SUBMIT', 'Soumission')], max_length=20, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changements',
            field=models.JSONField(blank=True, default=dict, help_text='\n    Détails des changements:\n    {\n        "before": {"field1": "old_value"},\n        "after": {"field1": "new_value"}\n    }\n    ', verbose_name='Changements'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='mandat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(max_length=100, verbose_name='ID objet'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_repr',
            field=models.CharField(max_length=255, verbose_name='Représentation objet'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='table_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nom de la table'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Horodatage'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse_correspondance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients_correspondance', to='core.adresse', verbose_name='Adresse de correspondance'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse_siege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients_siege', to='core.adresse', verbose_name='Adresse de siège'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_principal', to='core.contact', verbose_name='Contact principal'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='client',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='client',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='client',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='client',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='forme_juridique',
            field=models.CharField(choices=[('EI', 'Entreprise individuelle'), ('RC', 'Raison collective'), ('SC', 'Société en commandite'), ('SNC', 'Société en nom collectif'), ('SARL', 'Société à responsabilité limitée'), ('SA', 'Société anonyme'), ('SC_SIMPLE', 'Société en commandite simple'), ('SC_ACTIONS', 'Société en commandite par actions'), ('COOP', 'Société coopérative'), ('ASSOC', 'Association'), ('FOND', 'Fondation')], max_length=20, verbose_name='Forme juridique'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom_commercial',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom commercial'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes_de',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes_it',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='client',
            name='raison_sociale',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Raison sociale'),
        ),
        migrations.AlterField(
            model_name='client',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='client',
            name='site_web',
            field=models.URLField(blank=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='client',
            name='statut',
            field=models.CharField(choices=[('PROSPECT', 'Prospect'), ('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('RESILIE', 'Résilié'), ('ARCHIVE', 'Archivé')], db_index=True, default='PROSPECT', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='civilite',
            field=models.CharField(choices=[('M', 'Monsieur'), ('MME', 'Madame'), ('DR', 'Docteur'), ('PROF', 'Professeur')], max_length=10, verbose_name='Civilité'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fonction',
            field=models.CharField(choices=[('DIRECTEUR', 'Directeur'), ('GERANT', 'Gérant'), ('ADMIN', 'Administrateur'), ('COMPTABLE', 'Comptable'), ('RH', 'Ressources Humaines'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='principal',
            field=models.BooleanField(default=False, verbose_name='Contact principal'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='exercicecomptable',
            name='annee',
            field=models.IntegerField(db_index=True, verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='exercicecomptable',
            name='cloture_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Clôturé par'),
        ),
        migrations.AlterField(
            model_name='exercicecomptable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='exercicecomptable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='exercicecomptable',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture'),
        ),
        migrations.AlterField(
            model_name='exercicecomptable',
            name='date_debut',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='exercicecomptable',
            name='date_fin',
            field=models.DateField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='exercicecomptable',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='exercicecomptable',
            name='mandat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AlterField(
            model_name='exercicecomptable',
            name='resultat_exercice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Résultat exercice'),
        ),
        migrations.AlterField(
            model_name='exercicecomptable',
            name='statut',
            field=models.CharField(choices=[('OUVERT', 'Ouvert'), ('CLOTURE_PROVISOIRE', 'Clôture provisoire'), ('CLOTURE_DEFINITIVE', 'Clôture définitive')], db_index=True, default='OUVERT', max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='exercicecomptable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandats', to='core.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='conditions_particulieres',
            field=models.TextField(blank=True, verbose_name='Conditions particulières'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='conditions_particulieres_de',
            field=models.TextField(blank=True, null=True, verbose_name='Conditions particulières'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='conditions_particulieres_en',
            field=models.TextField(blank=True, null=True, verbose_name='Conditions particulières'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='conditions_particulieres_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Conditions particulières'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='conditions_particulieres_it',
            field=models.TextField(blank=True, null=True, verbose_name='Conditions particulières'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='configuration',
            field=models.JSONField(blank=True, default=dict, help_text='\n    {\n        "plan_comptable": "PME",\n        "methode_tva": "EFFECTIVE",\n        "periodicite_tva": "TRIMESTRIEL",\n        "cloture_mois": 12,\n        "devise": "CHF",\n        "langues": ["fr"],\n        "modules_actifs": ["compta", "tva", "salaires"]\n    }\n    ', verbose_name='Configuration'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='date_debut',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='equipe',
            field=models.ManyToManyField(blank=True, related_name='mandats_equipe', to=settings.AUTH_USER_MODEL, verbose_name='Équipe'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='montant_forfait',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant forfait'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='numero',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='periodicite',
            field=models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('SEMESTRIEL', 'Semestriel'), ('ANNUEL', 'Annuel'), ('PONCTUEL', 'Ponctuel')], max_length=20, verbose_name='Périodicité'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandats_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente validation'), ('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('TERMINE', 'Terminé'), ('RESILIE', 'Résilié')], db_index=True, default='BROUILLON', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='taux_horaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taux horaire'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='type_facturation',
            field=models.CharField(choices=[('FORFAIT', 'Forfait'), ('HORAIRE', 'Taux horaire'), ('MIXTE', 'Mixte')], default='HORAIRE', max_length=20, verbose_name='Type de facturation'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='type_mandat',
            field=models.CharField(choices=[('COMPTA', 'Comptabilité'), ('TVA', 'TVA'), ('SALAIRES', 'Salaires'), ('FISCAL', 'Conseil fiscal'), ('REVISION', 'Révision'), ('CONSEIL', 'Conseil général'), ('CREATION', 'Création entreprise'), ('GLOBAL', 'Mandat global')], db_index=True, max_length=20, verbose_name='Type de mandat'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='archivee',
            field=models.BooleanField(default=False, verbose_name='Archivée'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_lecture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='lien_action',
            field=models.CharField(blank=True, max_length=500, verbose_name='Lien action'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='lien_texte',
            field=models.CharField(blank=True, max_length=100, verbose_name='Texte du lien'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='lien_texte_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Texte du lien'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='lien_texte_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Texte du lien'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='lien_texte_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Texte du lien'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='lien_texte_it',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Texte du lien'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='lue',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Lue'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='mandat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message_de',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message_en',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message_fr',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message_it',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='titre_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='titre_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='titre_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='titre_it',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Succès'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur'), ('TASK', 'Tâche')], max_length=20, verbose_name='Type de notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='assigne_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taches_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='cree_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taches_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='date_echeance',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='tache',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='mandat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='priorite',
            field=models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=20, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('EN_ATTENTE', 'En attente'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], db_index=True, default='A_FAIRE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='temps_estime_heures',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temps estimé (heures)'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='temps_reel_heures',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temps réel (heures)'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='titre_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='titre_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='titre_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='titre_it',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='core_user_set', related_query_name='core_user', to='auth.group', verbose_name='Groupes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, verbose_name='Préférences'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('MANAGER', 'Chef de bureau'), ('COMPTABLE', 'Comptable'), ('ASSISTANT', 'Assistant'), ('CLIENT', 'Client')], default='ASSISTANT', max_length=20, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='Authentification à deux facteurs'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='core_user_set', related_query_name='core_user', to='auth.permission', verbose_name='Permissions'),
        ),
    ]
