# Generated by Django 6.0 on 2025-12-16 00:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_adresse_options_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(help_text='Ex: Compte principal, Compte salaires, etc.', max_length=100, verbose_name='Libellé')),
                ('type_compte', models.CharField(choices=[('COURANT', 'Compte courant'), ('EPARGNE', 'Compte épargne'), ('SALAIRE', 'Compte salaire'), ('POSTAL', 'Compte postal (PostFinance)'), ('QR', 'Compte QR-IBAN')], default='COURANT', max_length=20, verbose_name='Type de compte')),
                ('iban', models.CharField(help_text='International Bank Account Number (sans espaces)', max_length=34, validators=[django.core.validators.RegexValidator('^[A-Z]{2}\\d{2}[A-Z0-9]{4,30}$', 'Format IBAN invalide. Ex: CH93 0076 2011 6238 5295 7')], verbose_name='IBAN')),
                ('bic_swift', models.CharField(blank=True, help_text='Bank Identifier Code', max_length=11, validators=[django.core.validators.RegexValidator('^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$', 'Format BIC/SWIFT invalide. Ex: POFICHBEXXX')], verbose_name='BIC/SWIFT')),
                ('nom_banque', models.CharField(max_length=100, verbose_name='Nom de la banque')),
                ('adresse_banque', models.TextField(blank=True, verbose_name='Adresse de la banque')),
                ('clearing', models.CharField(blank=True, help_text='Numéro de compensation bancaire suisse', max_length=10, verbose_name='Numéro clearing')),
                ('titulaire_nom', models.CharField(help_text="Nom tel qu'il apparaît sur le compte", max_length=100, verbose_name='Nom du titulaire')),
                ('devise', models.CharField(choices=[('CHF', 'CHF - Franc suisse'), ('EUR', 'EUR - Euro'), ('USD', 'USD - Dollar américain')], default='CHF', max_length=3, verbose_name='Devise')),
                ('est_compte_principal', models.BooleanField(default=False, help_text='Compte principal de la fiduciaire pour les factures', verbose_name='Compte principal')),
                ('est_qr_iban', models.BooleanField(default=False, help_text='IBAN spécifique pour les QR-Bills (commence par CH30-CH31)', verbose_name='QR-IBAN')),
                ('qr_reference_type', models.CharField(choices=[('QRR', 'Référence QR (QRR)'), ('SCOR', 'Référence SCOR (Creditor Reference)'), ('NON', 'Sans référence')], default='QRR', max_length=10, verbose_name='Type de référence QR')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comptes_bancaires', to='core.client', verbose_name='Client')),
                ('mandat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comptes_bancaires', to='core.mandat', verbose_name='Mandat')),
                ('titulaire_adresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_bancaires', to='core.adresse', verbose_name='Adresse du titulaire')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comptes_bancaires', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Compte bancaire',
                'verbose_name_plural': 'Comptes bancaires',
                'db_table': 'comptes_bancaires',
                'ordering': ['-est_compte_principal', 'libelle'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('est_compte_principal', True)), fields=('est_compte_principal',), name='unique_compte_principal')],
            },
        ),
    ]
