# Generated by Django 6.0 on 2025-12-16 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_add_role_devise_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='canton',
            field=models.CharField(blank=True, choices=[('AG', 'Argovie'), ('AI', 'Appenzell Rhodes-Intérieures'), ('AR', 'Appenzell Rhodes-Extérieures'), ('BE', 'Berne'), ('BL', 'Bâle-Campagne'), ('BS', 'Bâle-Ville'), ('FR', 'Fribourg'), ('GE', 'Genève'), ('GL', 'Glaris'), ('GR', 'Grisons'), ('JU', 'Jura'), ('LU', 'Lucerne'), ('NE', 'Neuchâtel'), ('NW', 'Nidwald'), ('OW', 'Obwald'), ('SG', 'Saint-Gall'), ('SH', 'Schaffhouse'), ('SO', 'Soleure'), ('SZ', 'Schwyz'), ('TG', 'Thurgovie'), ('TI', 'Tessin'), ('UR', 'Uri'), ('VD', 'Vaud'), ('VS', 'Valais'), ('ZG', 'Zoug'), ('ZH', 'Zurich')], help_text='Uniquement pour les adresses suisses', max_length=2, verbose_name='Canton'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='code_postal',
            field=models.CharField(default='', help_text='NPA pour la Suisse, ZIP pour USA, etc.', max_length=20, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='localite',
            field=models.CharField(max_length=100, verbose_name='Localité/Ville'),
        ),
        migrations.AlterField(
            model_name='devise',
            name='est_devise_base',
            field=models.BooleanField(default=False, help_text='Devise principale de comptabilité', verbose_name='Devise de base'),
        ),
        migrations.AlterField(
            model_name='devise',
            name='separateur_milliers',
            field=models.CharField(default="'", help_text="Ex: ' pour 1'000 ou , pour 1,000", max_length=1, verbose_name='Séparateur milliers'),
        ),
        migrations.AlterField(
            model_name='devise',
            name='symbole_avant',
            field=models.BooleanField(default=False, help_text='True pour $100, False pour 100 CHF', verbose_name='Symbole avant le montant'),
        ),
        migrations.AlterField(
            model_name='devise',
            name='taux_change',
            field=models.DecimalField(decimal_places=6, default=1, help_text='Taux par rapport au CHF (1 CHF = X devise)', max_digits=12, verbose_name='Taux de change'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(help_text='Code unique du rôle (ex: ADMIN, MANAGER)', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='role',
            name='est_role_defaut',
            field=models.BooleanField(default=False, help_text='Rôle assigné automatiquement aux nouveaux utilisateurs', verbose_name='Rôle par défaut'),
        ),
        migrations.AlterField(
            model_name='role',
            name='niveau',
            field=models.PositiveSmallIntegerField(default=0, help_text='0=plus bas, 100=plus haut. Un utilisateur peut gérer les rôles de niveau inférieur.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Niveau hiérarchique'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions Django associées à ce rôle', to='auth.permission', verbose_name='Permissions'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions_custom',
            field=models.JSONField(blank=True, default=list, help_text='Liste de codes de permissions custom: ["can_export_data", "can_view_reports"]', verbose_name='Permissions personnalisées'),
        ),
        migrations.AlterField(
            model_name='role',
            name='peut_etre_assigne',
            field=models.BooleanField(default=True, help_text='Si False, ce rôle ne peut pas être assigné manuellement', verbose_name='Peut être assigné'),
        ),
    ]
