# Generated by Django 6.0 on 2026-01-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_adresse_canton_alter_adresse_code_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('VIEW', 'Consultation'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('VALIDATE', 'Validation'), ('SUBMIT', 'Soumission')], max_length=20, verbose_name='Action'),
        ),
    ]
