# Generated by Django 6.0.2 on 2026-02-22 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mandat_regime_devise_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptebancaire',
            name='devise',
            field=models.ForeignKey(db_column='devise', on_delete=django.db.models.deletion.PROTECT, to='core.devise', verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='devise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.devise', verbose_name='Devise'),
        ),
    ]
