# Generated by Django 6.0.2 on 2026-02-23 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_comptebancaire_devise_alter_tiers_devise'),
        ('facturation', '0013_prestation_type_fk_final'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tache',
            name='taches_assigne_3e4ac9_idx',
        ),
        migrations.AddField(
            model_name='tache',
            name='assignes',
            field=models.ManyToManyField(blank=True, related_name='taches_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assignés à'),
        ),
        migrations.AddField(
            model_name='tache',
            name='prestation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches', to='facturation.prestation', verbose_name='Prestation'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='assigne_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taches_assignees_old', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à (ancien)'),
        ),
    ]
