# Generated by Django 6.0 on 2026-01-08 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0009_add_additional_periodicites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_lie',
            field=models.ForeignKey(blank=True, help_text='Contact associé pour les utilisateurs clients', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateur_lie', to='core.contact', verbose_name='Contact lié'),
        ),
        migrations.AddField(
            model_name='user',
            name='doit_changer_mot_de_passe',
            field=models.BooleanField(default=False, help_text="Force l'utilisateur à changer son mot de passe à la prochaine connexion", verbose_name='Doit changer le mot de passe'),
        ),
        migrations.AddField(
            model_name='user',
            name='type_utilisateur',
            field=models.CharField(choices=[('STAFF', 'Collaborateur interne'), ('CLIENT', 'Client externe')], db_index=True, default='STAFF', max_length=10, verbose_name="Type d'utilisateur"),
        ),
        migrations.CreateModel(
            name='AccesMandat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('est_responsable', models.BooleanField(default=False, help_text="Le responsable peut inviter d'autres utilisateurs pour ce mandat", verbose_name='Est responsable')),
                ('limite_invitations', models.PositiveIntegerField(default=5, help_text="Nombre maximum d'utilisateurs que ce responsable peut inviter", verbose_name="Limite d'invitations")),
                ('invitations_restantes', models.PositiveIntegerField(default=5, verbose_name='Invitations restantes')),
                ('date_debut_acces', models.DateField(blank=True, null=True, verbose_name="Date de début d'accès")),
                ('date_fin_acces', models.DateField(blank=True, null=True, verbose_name="Date de fin d'accès")),
                ('notes', models.TextField(blank=True, help_text='Notes internes sur cet accès', verbose_name='Notes')),
                ('accorde_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acces_accordes', to=settings.AUTH_USER_MODEL, verbose_name='Accès accordé par')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('mandat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_utilisateurs', to='core.mandat', verbose_name='Mandat')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions Django sur ce mandat', to='auth.permission', verbose_name='Permissions')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_mandats', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Accès mandat',
                'verbose_name_plural': 'Accès mandats',
                'db_table': 'acces_mandats',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['utilisateur', 'is_active'], name='acces_manda_utilisa_d1aa1e_idx'), models.Index(fields=['mandat', 'is_active'], name='acces_manda_mandat__1b232c_idx')],
                'unique_together': {('utilisateur', 'mandat')},
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('type_invitation', models.CharField(choices=[('STAFF', 'Invitation collaborateur'), ('CLIENT', 'Invitation client mandat')], max_length=10, verbose_name="Type d'invitation")),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token')),
                ('date_expiration', models.DateTimeField(verbose_name="Date d'expiration")),
                ('est_responsable_prevu', models.BooleanField(default=False, help_text="L'invité sera responsable du mandat côté client", verbose_name='Sera responsable')),
                ('limite_invitations_prevue', models.PositiveIntegerField(default=5, verbose_name="Limite d'invitations prévue")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('EXPIREE', 'Expirée'), ('ANNULEE', 'Annulée')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_acceptation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'acceptation")),
                ('forcer_changement_mdp', models.BooleanField(default=True, help_text="L'utilisateur devra changer son mot de passe à la première connexion", verbose_name='Forcer changement mot de passe')),
                ('message_personnalise', models.TextField(blank=True, help_text="Message inclus dans l'email d'invitation", verbose_name='Message personnalisé')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('invite_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Invité par')),
                ('mandat', models.ForeignKey(blank=True, help_text="Mandat auquel l'invité aura accès (pour les clients)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.mandat', verbose_name='Mandat')),
                ('permissions_acces', models.ManyToManyField(blank=True, help_text='Permissions à accorder sur le mandat', to='auth.permission', verbose_name='Permissions')),
                ('role_preassigne', models.ForeignKey(blank=True, help_text="Rôle attribué à l'utilisateur lors de l'acceptation", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='core.role', verbose_name='Rôle pré-assigné')),
                ('utilisateur_cree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_origine', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur créé')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'db_table': 'invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'statut'], name='invitations_email_ee21c2_idx'), models.Index(fields=['token'], name='invitations_token_5b330c_idx'), models.Index(fields=['date_expiration', 'statut'], name='invitations_date_ex_513c82_idx')],
            },
        ),
    ]
