# Generated by Django 6.0.2 on 2026-02-23 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_migrate_assigne_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='assigne_a',
        ),
    ]
