# Generated by Django 6.0.3 on 2026-03-07 23:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tache_remove_assigne_a'),
        ('tva', '0008_configurationtva_regime_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreMetier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('module', models.CharField(choices=[('core', 'Général'), ('salaires', 'Salaires'), ('facturation', 'Facturation'), ('comptabilite', 'Comptabilité'), ('fiscalite', 'Fiscalité'), ('tva', 'TVA'), ('projets', 'Projets'), ('documents', 'Documents'), ('analytics', 'Analytics')], db_index=True, help_text='Module auquel appartient ce paramètre', max_length=30, verbose_name='Module')),
                ('categorie', models.CharField(db_index=True, help_text='Ex: type_contrat, type_facture, mode_paiement, type_journal...', max_length=60, verbose_name='Catégorie')),
                ('code', models.CharField(help_text='Valeur technique (ex: CDI, VIREMENT, SA). Ne pas modifier après création.', max_length=50, verbose_name='Code technique')),
                ('libelle', models.CharField(help_text="Texte affiché à l'utilisateur", max_length=200, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, help_text='Description ou aide contextuelle', verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('systeme', models.BooleanField(default=False, help_text="Si vrai, ne peut pas être supprimé par l'utilisateur", verbose_name='Paramètre système')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires (couleur, icône, config spécifique...)', verbose_name='Métadonnées')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('regime_fiscal', models.ForeignKey(blank=True, help_text="Si renseigné, ce choix n'apparaît que pour ce régime fiscal", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametres_metier', to='tva.regimefiscal', verbose_name='Régime fiscal')),
            ],
            options={
                'verbose_name': 'Paramètre métier',
                'verbose_name_plural': 'Paramètres métier',
                'db_table': 'parametres_metier',
                'ordering': ['module', 'categorie', 'ordre', 'libelle'],
                'indexes': [models.Index(fields=['module', 'categorie'], name='parametres__module_554ff5_idx'), models.Index(fields=['module', 'categorie', 'is_active'], name='parametres__module_c1c174_idx')],
                'unique_together': {('module', 'categorie', 'code')},
            },
        ),
    ]
