# Generated by Django 6.0.2 on 2026-02-08 12:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_type_collaborateur_and_collaborateur_fiduciaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raison_sociale', models.CharField(help_text="Nom officiel de l'entreprise", max_length=255, verbose_name='Raison sociale')),
                ('nom_commercial', models.CharField(blank=True, help_text='Nom utilisé commercialement si différent', max_length=255, verbose_name='Nom commercial')),
                ('forme_juridique', models.CharField(choices=[('EI', 'Entreprise individuelle'), ('RC', 'Raison collective'), ('SC', 'Société en commandite'), ('SNC', 'Société en nom collectif'), ('SARL', 'Société à responsabilité limitée'), ('SA', 'Société anonyme'), ('SC_SIMPLE', 'Société en commandite simple'), ('SC_ACTIONS', 'Société en commandite par actions'), ('COOP', 'Société coopérative'), ('ASSOC', 'Association'), ('FOND', 'Fondation')], max_length=20, verbose_name='Forme juridique')),
                ('ide_number', models.CharField(help_text="Numéro d'identification des entreprises (CHE-XXX.XXX.XXX)", max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^CHE-\\d{3}\\.\\d{3}\\.\\d{3}$', 'Format IDE invalide (CHE-XXX.XXX.XXX)')], verbose_name='Numéro IDE')),
                ('ch_id', models.CharField(blank=True, help_text='Numéro CH-ID (CH-XXX-XXXXXXX-X)', max_length=30, verbose_name='CH-ID')),
                ('ofrc_id', models.CharField(blank=True, help_text="Numéro de l'Office fédéral du registre du commerce", max_length=20, verbose_name='OFRC-ID')),
                ('tva_number', models.CharField(blank=True, help_text='Numéro TVA si assujetti', max_length=20, verbose_name='Numéro TVA')),
                ('siege', models.CharField(help_text='Localité du siège social', max_length=100, verbose_name='Siège')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('but', models.TextField(blank=True, help_text="But de l'entreprise tel qu'inscrit au RC", verbose_name='But')),
                ('date_creation', models.DateField(blank=True, help_text="Date de création/commencement de l'entreprise", null=True, verbose_name='Date de création')),
                ('date_inscription_rc', models.DateField(blank=True, help_text="Date d'inscription au registre du commerce", null=True, verbose_name="Date d'inscription RC")),
                ('canton_rc', models.CharField(blank=True, choices=[('AG', 'Argovie'), ('AI', 'Appenzell Rhodes-Intérieures'), ('AR', 'Appenzell Rhodes-Extérieures'), ('BE', 'Berne'), ('BL', 'Bâle-Campagne'), ('BS', 'Bâle-Ville'), ('FR', 'Fribourg'), ('GE', 'Genève'), ('GL', 'Glaris'), ('GR', 'Grisons'), ('JU', 'Jura'), ('LU', 'Lucerne'), ('NE', 'Neuchâtel'), ('NW', 'Nidwald'), ('OW', 'Obwald'), ('SG', 'Saint-Gall'), ('SH', 'Schaffhouse'), ('SO', 'Soleure'), ('SZ', 'Schwyz'), ('TG', 'Thurgovie'), ('TI', 'Tessin'), ('UR', 'Uri'), ('VD', 'Vaud'), ('VS', 'Valais'), ('ZG', 'Zoug'), ('ZH', 'Zurich')], help_text='Canton du registre du commerce', max_length=2, verbose_name='Canton du RC')),
                ('derniere_publication_fosc', models.TextField(blank=True, help_text='Dernière publication à la Feuille officielle suisse du commerce', verbose_name='Dernière publication FOSC')),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EN_LIQUIDATION', 'En liquidation'), ('RADIEE', 'Radiée')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('logo', models.ImageField(blank=True, help_text="Logo de l'entreprise (utilisé sur les documents)", null=True, upload_to='entreprise/logo/', verbose_name='Logo')),
                ('associes', models.JSONField(blank=True, default=list, help_text='Liste des associés avec leurs informations', verbose_name='Associés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('adresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entreprises', to='core.adresse', verbose_name='Adresse du siège')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'db_table': 'entreprise',
            },
        ),
    ]
