# Generated by Django 6.0.3 on 2026-03-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_invitation_code_court'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invitation',
            new_name='invitations_code_co_705ec5_idx',
            old_name='invitations_code_co_idx',
        ),
    ]
