# Generated by Django 6.0.2 on 2026-02-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_default_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='canton_rc',
            field=models.CharField(blank=True, choices=[('AG', 'Argovie'), ('AI', 'Appenzell Rhodes-Intérieures'), ('AR', 'Appenzell Rhodes-Extérieures'), ('BE', 'Berne'), ('BL', 'Bâle-Campagne'), ('BS', 'Bâle-Ville'), ('FR', 'Fribourg'), ('GE', 'Genève'), ('GL', 'Glaris'), ('GR', 'Grisons'), ('JU', 'Jura'), ('LU', 'Lucerne'), ('NE', 'Neuchâtel'), ('NW', 'Nidwald'), ('OW', 'Obwald'), ('SG', 'Saint-Gall'), ('SH', 'Schaffhouse'), ('SO', 'Soleure'), ('SZ', 'Schwyz'), ('TG', 'Thurgovie'), ('TI', 'Tessin'), ('UR', 'Uri'), ('VD', 'Vaud'), ('VS', 'Valais'), ('ZG', 'Zoug'), ('ZH', 'Zurich')], help_text='Canton du registre du commerce', max_length=2, verbose_name='Canton RC'),
        ),
        migrations.AddField(
            model_name='client',
            name='ch_id',
            field=models.CharField(blank=True, help_text='Numéro CH-ID (CH-XXX-XXXXXXX-X)', max_length=30, verbose_name='CH-ID'),
        ),
        migrations.AddField(
            model_name='client',
            name='ofrc_id',
            field=models.CharField(blank=True, help_text="Numéro de l'Office fédéral du registre du commerce", max_length=20, verbose_name='OFRC-ID'),
        ),
        migrations.AddField(
            model_name='client',
            name='siege',
            field=models.CharField(blank=True, help_text='Localité du siège social', max_length=100, verbose_name='Siège'),
        ),
    ]
