# Generated by Django 6.0.2 on 2026-02-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_zefix_fields_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='localite',
            field=models.CharField(blank=True, help_text='Localité', max_length=100, verbose_name='Localité'),
        ),
        migrations.AddField(
            model_name='client',
            name='npa',
            field=models.CharField(blank=True, help_text='Numéro postal', max_length=10, verbose_name='NPA'),
        ),
    ]
