# Generated by Django 6.0.2

import core.models
import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_invitation_code_court_meta_index'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichierJoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('object_id', models.UUIDField(help_text="Identifiant de l'objet parent", verbose_name='ID objet')),
                ('fichier', models.FileField(help_text='Fichier joint', upload_to=core.models.fichier_joint_upload_path, verbose_name='Fichier')),
                ('nom_original', models.CharField(help_text="Nom du fichier lors de l'upload", max_length=255, verbose_name='Nom original')),
                ('extension', models.CharField(blank=True, help_text='Extension du fichier (pdf, jpg, etc.)', max_length=20, verbose_name='Extension')),
                ('mime_type', models.CharField(blank=True, help_text='Type MIME du fichier', max_length=100, verbose_name='Type MIME')),
                ('taille', models.BigIntegerField(default=0, help_text='Taille du fichier en octets', verbose_name='Taille')),
                ('hash_fichier', models.CharField(blank=True, db_index=True, help_text='Empreinte SHA-256 du fichier', max_length=64, verbose_name='Hash SHA-256')),
                ('description', models.CharField(blank=True, help_text='Description ou commentaire sur ce fichier', max_length=500, verbose_name='Description')),
                ('ordre', models.IntegerField(default=0, help_text="Position d'affichage dans la liste", verbose_name='Ordre')),
                ('content_type', models.ForeignKey(help_text='Modèle auquel ce fichier est rattaché', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Type de contenu')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Fichier joint',
                'verbose_name_plural': 'Fichiers joints',
                'db_table': 'fichiers_joints',
                'ordering': ['ordre', 'created_at'],
                'indexes': [
                    models.Index(fields=['content_type', 'object_id'], name='fj_ct_oid_idx'),
                ],
            },
        ),
    ]
