# Generated by Django 6.0.2 on 2026-02-10 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_npa_localite_to_client'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collaborateurfiduciaire',
            name='unique_collaborateur_mandat',
        ),
        migrations.RenameIndex(
            model_name='collaborateurfiduciaire',
            new_name='collaborate_utilisa_6dc3a9_idx',
            old_name='collab_fid_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='collaborateurfiduciaire',
            new_name='collaborate_mandat__b17796_idx',
            old_name='collab_fid_mandat_active_idx',
        ),
        migrations.AlterUniqueTogether(
            name='collaborateurfiduciaire',
            unique_together={('utilisateur', 'mandat')},
        ),
    ]
