# Generated by Django 6.0.3 on 2026-03-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fichierjoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptebancaire',
            name='est_compte_principal',
            field=models.BooleanField(default=False, help_text="Compte principal de l'entreprise pour les factures", verbose_name='Compte principal'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='type_invitation',
            field=models.CharField(choices=[('STAFF', 'Collaborateur interne'), ('STAFF_PRESTATAIRE', 'Prestataire externe'), ('CLIENT', 'Client externe'), ('CLIENT_PRESTATAIRE', 'Prestataire client')], max_length=20, verbose_name="Type d'invitation"),
        ),
    ]
