# Generated by Django 6.0.3 on 2026-03-12 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_comptebancaire_est_compte_principal_and_more'),
        ('tva', '0009_add_parametre_metier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_creation',
            field=models.DateField(blank=True, null=True, verbose_name='Date de création entreprise'),
        ),
        migrations.AlterField(
            model_name='client',
            name='forme_juridique',
            field=models.CharField(choices=[('EI', 'Entreprise individuelle'), ('RC', 'Raison collective'), ('SC', 'Société en commandite'), ('SNC', 'Société en nom collectif'), ('SARL', 'Société à responsabilité limitée'), ('SA', 'Société anonyme'), ('SC_SIMPLE', 'Société en commandite simple'), ('SC_ACTIONS', 'Société en commandite par actions'), ('COOP', 'Société coopérative'), ('ASSOC', 'Association'), ('FOND', 'Fondation'), ('PP', 'Personne physique'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Forme juridique'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ide_number',
            field=models.CharField(blank=True, help_text='Format: CHE-123.456.789 (optionnel)', max_length=20, validators=[django.core.validators.RegexValidator('^CHE-\\d{3}\\.\\d{3}\\.\\d{3}$', 'Format IDE invalide (CHE-XXX.XXX.XXX)')], verbose_name='Numéro IDE'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('ide_number', ''), _negated=True), fields=('ide_number',), name='unique_ide_number_non_vide'),
        ),
    ]
