# Generated by Django 6.0.2 on 2026-02-13 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='parent_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_clients_set', to='core.client', verbose_name='Client parent'),
        ),
    ]
