# Generated by Django 6.0.3 on 2026-03-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_seed_reference_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptebancaire',
            name='iban',
            field=models.CharField(help_text='International Bank Account Number', max_length=34, verbose_name='IBAN'),
        ),
    ]
