# Generated by Django 6.0.3 on 2026-03-18 18:23

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0022_user_totp_secret_backup_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(verbose_name='ID objet')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, verbose_name='Embedding')),
                ('text_hash', models.CharField(help_text='SHA-256 du texte source, pour détecter les changements', max_length=64, verbose_name='Hash du texte')),
                ('text_preview', models.CharField(blank=True, max_length=200, verbose_name='Aperçu du texte')),
                ('model_used', models.CharField(default='paraphrase-multilingual-mpnet-base-v2', max_length=100, verbose_name='Modèle utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Type de contenu')),
            ],
            options={
                'verbose_name': 'Embedding de modèle',
                'verbose_name_plural': 'Embeddings de modèles',
                'db_table': 'model_embeddings',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='me_ct_oid_idx'), models.Index(fields=['content_type'], name='me_ct_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_model_embedding')],
            },
        ),
    ]
