# Generated by Django 6.0.3 on 2026-03-24 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_contrats_et_analytique'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('taux', models.DecimalField(decimal_places=6, help_text='1 CHF = X unités de cette devise', max_digits=12, verbose_name='Taux')),
                ('source', models.CharField(blank=True, default='BNS', help_text='BNS, BCE, manuel, etc.', max_length=50, verbose_name='Source')),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_cours', to='core.devise', verbose_name='Devise')),
            ],
            options={
                'verbose_name': 'Cours de change',
                'verbose_name_plural': 'Cours de change',
                'db_table': 'cours_change',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['devise', 'date'], name='cours_chang_devise__192875_idx')],
                'unique_together': {('devise', 'date')},
            },
        ),
    ]
