# Generated by Django 6.0.3 on 2026-03-24 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_contrats_langue_saisie'),
        ('documents', '0010_alter_categoriedocument_langue_saisie_and_more'),
        ('projets', '0002_langue_saisie'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Position/lot du projet (pour contrats de sous-traitance)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats', to='projets.position', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='accesmandat',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='client',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='collaborateurfiduciaire',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='categorie',
            field=models.CharField(blank=True, help_text='Code ParametreMetier (module=contrats, categorie=type_contrat)', max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='date_fin',
            field=models.DateField(blank=True, help_text='Vide = durée indéterminée', null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Fichier du contrat dans la GED', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats', to='documents.document', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='numero',
            field=models.CharField(blank=True, help_text='Référence unique du contrat', max_length=50, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='sens',
            field=models.CharField(choices=[('EMIS', 'Émis'), ('RECU', 'Reçu')], default='EMIS', help_text='Émis = envoyé au client, Reçu = reçu du client', max_length=10, verbose_name='Sens'),
        ),
        migrations.AlterField(
            model_name='exercicecomptable',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='fichierjoint',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='modelecontrat',
            name='categorie',
            field=models.CharField(blank=True, help_text='Code ParametreMetier (module=contrats, categorie=type_contrat)', max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='modelecontrat',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Fichier template dans la GED (DOCX, éditable via OnlyOffice)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modeles_contrat', to='documents.document', verbose_name='Document template'),
        ),
        migrations.AlterField(
            model_name='modelecontrat',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='modeledocumentpdf',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='parametremetier',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
    ]
