# Generated by Django 6.0.3 on 2026-04-03 10:33

import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_contrat_position_alter_accesmandat_langue_saisie_and_more'),
        ('tva', '0012_regimefiscal_delai_paiement_defaut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeIdentifiantLegal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('langue_saisie', models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie')),
                ('code', models.CharField(help_text='Code technique unique (ex: IDE, SIRET, RCCM, NIF)', max_length=30, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(help_text='Nom complet (ex: Identifiant des entreprises)', max_length=150, verbose_name='Libellé')),
                ('pays', django_countries.fields.CountryField(blank=True, help_text="Pays d'origine de cet identifiant", max_length=2, verbose_name='Pays')),
                ('format_validation', models.CharField(blank=True, help_text='Expression régulière pour valider le format. Ex: ^CHE-\\d{3}\\.\\d{3}\\.\\d{3}$', max_length=255, verbose_name='Format de validation (regex)')),
                ('exemple', models.CharField(blank=True, help_text='Exemple de valeur correcte (ex: CHE-123.456.789)', max_length=100, verbose_name='Exemple')),
                ('obligatoire_entreprise', models.BooleanField(default=False, verbose_name="Obligatoire pour l'entreprise émettrice")),
                ('obligatoire_client', models.BooleanField(default=False, verbose_name='Obligatoire pour le client')),
                ('afficher_sur_facture', models.BooleanField(default=True, verbose_name='Afficher sur les factures')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('regime_fiscal', models.ForeignKey(blank=True, help_text="Si renseigné, cet identifiant ne s'affiche que pour ce régime", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types_identifiants', to='tva.regimefiscal', verbose_name='Régime fiscal')),
            ],
            options={
                'verbose_name': "Type d'identifiant légal",
                'verbose_name_plural': "Types d'identifiants légaux",
                'db_table': 'types_identifiants_legaux',
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='IdentifiantLegal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('langue_saisie', models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie')),
                ('valeur', models.CharField(max_length=100, verbose_name='Valeur')),
                ('verifie', models.BooleanField(default=False, help_text='Indique si cet identifiant a été vérifié auprès du registre officiel', verbose_name='Vérifié')),
                ('date_verification', models.DateField(blank=True, null=True, verbose_name='Date de vérification')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifiants_legaux', to='core.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifiants_legaux', to='core.entreprise', verbose_name='Entreprise')),
                ('type_identifiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identifiants', to='core.typeidentifiantlegal', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Identifiant légal',
                'verbose_name_plural': 'Identifiants légaux',
                'db_table': 'identifiants_legaux',
                'ordering': ['type_identifiant__ordre'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('client__isnull', False), ('entreprise__isnull', True)), models.Q(('client__isnull', True), ('entreprise__isnull', False)), _connector='OR'), name='identifiant_legal_une_seule_entite'), models.UniqueConstraint(condition=models.Q(('client__isnull', False)), fields=('type_identifiant', 'client'), name='unique_type_identifiant_par_client'), models.UniqueConstraint(condition=models.Q(('entreprise__isnull', False)), fields=('type_identifiant', 'entreprise'), name='unique_type_identifiant_par_entreprise')],
            },
        ),
    ]
