# Generated by merge script
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_accesmandat_langue_saisie_client_langue_saisie_and_more"),
        ("core", "0027_contrat_position_alter_accesmandat_langue_saisie_and_more"),
    ]

    operations = [
    ]
