# Generated by Django 6.0.3 on 2026-04-03 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_typeidentifiantlegal_identifiantlegal'),
        ('tva', '0012_regimefiscal_delai_paiement_defaut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='devise',
            field=models.ForeignKey(blank=True, help_text="Devise principale de l'entreprise (auto-remplie depuis le régime si vide)", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entreprises', to='core.devise', verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='regime_fiscal',
            field=models.ForeignKey(blank=True, help_text='Détermine la TVA, les cotisations, le plan comptable et la devise par défaut', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entreprises', to='tva.regimefiscal', verbose_name='Régime fiscal'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='ide_number',
            field=models.CharField(blank=True, help_text='Identifiant suisse CHE-XXX.XXX.XXX (optionnel, utiliser Identifiants légaux)', max_length=20, null=True, unique=True, verbose_name='Numéro IDE'),
        ),
    ]
