# Generated by Django 6.0.3 on 2026-04-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_entreprise_devise_entreprise_regime_fiscal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicite',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='periodicite',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='periodicite',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='periodicite',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='periodicite',
            name='libelle_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Libellé'),
        ),
        migrations.AddField(
            model_name='periodicite',
            name='libelle_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Libellé'),
        ),
        migrations.AddField(
            model_name='periodicite',
            name='libelle_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Libellé'),
        ),
        migrations.AddField(
            model_name='periodicite',
            name='libelle_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='modeledocumentpdf',
            name='couleur_primaire',
            field=models.CharField(default='#02312e', max_length=7, verbose_name='Couleur primaire'),
        ),
    ]
