# Generated by Django 5.2.8 on 2025-11-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimisationfiscale',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='optimisationfiscale',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='optimisationfiscale',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='optimisationfiscale',
            name='description_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='optimisationfiscale',
            name='notes_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optimisationfiscale',
            name='notes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optimisationfiscale',
            name='notes_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optimisationfiscale',
            name='notes_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optimisationfiscale',
            name='titre_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='optimisationfiscale',
            name='titre_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='optimisationfiscale',
            name='titre_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='optimisationfiscale',
            name='titre_it',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
