# Generated by Django 5.2.8 on 2025-11-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalite', '0003_alter_annexefiscale_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declarationfiscale',
            name='canton',
            field=models.CharField(choices=[('AG', 'Argovie'), ('AI', 'Appenzell Rhodes-Intérieures'), ('AR', 'Appenzell Rhodes-Extérieures'), ('BE', 'Berne'), ('BL', 'Bâle-Campagne'), ('BS', 'Bâle-Ville'), ('FR', 'Fribourg'), ('GE', 'Genève'), ('GL', 'Glaris'), ('GR', 'Grisons'), ('JU', 'Jura'), ('LU', 'Lucerne'), ('NE', 'Neuchâtel'), ('NW', 'Nidwald'), ('OW', 'Obwald'), ('SG', 'Saint-Gall'), ('SH', 'Schaffhouse'), ('SO', 'Soleure'), ('SZ', 'Schwyz'), ('TG', 'Thurgovie'), ('TI', 'Tessin'), ('UR', 'Uri'), ('VD', 'Vaud'), ('VS', 'Valais'), ('ZG', 'Zoug'), ('ZH', 'Zurich')], max_length=2, verbose_name='Canton'),
        ),
        migrations.AlterField(
            model_name='tauximposition',
            name='canton',
            field=models.CharField(choices=[('AG', 'Argovie'), ('AI', 'Appenzell Rhodes-Intérieures'), ('AR', 'Appenzell Rhodes-Extérieures'), ('BE', 'Berne'), ('BL', 'Bâle-Campagne'), ('BS', 'Bâle-Ville'), ('FR', 'Fribourg'), ('GE', 'Genève'), ('GL', 'Glaris'), ('GR', 'Grisons'), ('JU', 'Jura'), ('LU', 'Lucerne'), ('NE', 'Neuchâtel'), ('NW', 'Nidwald'), ('OW', 'Obwald'), ('SG', 'Saint-Gall'), ('SH', 'Schaffhouse'), ('SO', 'Soleure'), ('SZ', 'Schwyz'), ('TG', 'Thurgovie'), ('TI', 'Tessin'), ('UR', 'Uri'), ('VD', 'Vaud'), ('VS', 'Valais'), ('ZG', 'Zoug'), ('ZH', 'Zurich')], max_length=2, verbose_name='Canton'),
        ),
    ]
