# Generated by Django 6.0.2 on 2026-02-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalite', '0008_internationalization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctionfiscale',
            name='montant_comptable',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valeur inscrite en comptabilité dans la devise du régime', max_digits=15, verbose_name='Montant comptable'),
        ),
        migrations.AlterField(
            model_name='correctionfiscale',
            name='montant_fiscal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valeur retenue fiscalement dans la devise du régime (calculé automatiquement)', max_digits=15, verbose_name='Montant fiscal'),
        ),
        migrations.AlterField(
            model_name='declarationfiscale',
            name='benefice_avant_impots',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bénéfice comptable avant impôts dans la devise du régime', max_digits=15, verbose_name='Bénéfice avant impôts'),
        ),
        migrations.AlterField(
            model_name='declarationfiscale',
            name='benefice_imposable',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bénéfice après corrections fiscales dans la devise du régime', max_digits=15, verbose_name='Bénéfice imposable'),
        ),
        migrations.AlterField(
            model_name='declarationfiscale',
            name='capital_imposable',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Capital après corrections fiscales dans la devise du régime', max_digits=15, verbose_name='Capital imposable'),
        ),
        migrations.AlterField(
            model_name='declarationfiscale',
            name='capital_propre',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Capital propre comptable dans la devise du régime', max_digits=15, verbose_name='Capital propre'),
        ),
        migrations.AlterField(
            model_name='declarationfiscale',
            name='impot_cantonal',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Montant de l'impôt cantonal dans la devise du régime", max_digits=12, verbose_name='Impôt cantonal'),
        ),
        migrations.AlterField(
            model_name='declarationfiscale',
            name='impot_communal',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Montant de l'impôt communal dans la devise du régime", max_digits=12, verbose_name='Impôt communal'),
        ),
        migrations.AlterField(
            model_name='declarationfiscale',
            name='impot_federal',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Montant de l'impôt fédéral direct dans la devise du régime", max_digits=12, verbose_name='Impôt fédéral'),
        ),
        migrations.AlterField(
            model_name='declarationfiscale',
            name='impot_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Somme des impôts fédéral, cantonal et communal dans la devise du régime', max_digits=12, verbose_name='Impôt total'),
        ),
        migrations.AlterField(
            model_name='optimisationfiscale',
            name='economie_estimee',
            field=models.DecimalField(decimal_places=2, help_text="Économie d'impôt estimée dans la devise du régime", max_digits=12, verbose_name='Économie estimée'),
        ),
        migrations.AlterField(
            model_name='optimisationfiscale',
            name='economie_reelle',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Économie d'impôt effectivement réalisée dans la devise du régime", max_digits=12, null=True, verbose_name='Économie réelle'),
        ),
        migrations.AlterField(
            model_name='reclamationfiscale',
            name='montant_accorde',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Réduction d'impôt finalement obtenue dans la devise du régime", max_digits=12, null=True, verbose_name='Montant accordé'),
        ),
        migrations.AlterField(
            model_name='reclamationfiscale',
            name='montant_conteste',
            field=models.DecimalField(decimal_places=2, help_text="Montant d'impôt remis en cause dans la devise du régime", max_digits=12, verbose_name='Montant contesté'),
        ),
        migrations.AlterField(
            model_name='reclamationfiscale',
            name='montant_demande',
            field=models.DecimalField(decimal_places=2, help_text="Montant d'impôt souhaité après correction dans la devise du régime", max_digits=12, verbose_name='Montant demandé'),
        ),
        migrations.AlterField(
            model_name='reportperte',
            name='montant_perte',
            field=models.DecimalField(decimal_places=2, help_text='Montant initial de la perte fiscale dans la devise du régime', max_digits=15, verbose_name='Montant de la perte'),
        ),
        migrations.AlterField(
            model_name='reportperte',
            name='montant_restant',
            field=models.DecimalField(decimal_places=2, help_text='Solde de perte encore reportable dans la devise du régime', max_digits=15, verbose_name='Montant restant'),
        ),
        migrations.AlterField(
            model_name='reportperte',
            name='montant_utilise',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumul des pertes déjà imputées dans la devise du régime', max_digits=15, verbose_name='Montant utilisé'),
        ),
        migrations.AlterField(
            model_name='utilisationperte',
            name='montant_utilise',
            field=models.DecimalField(decimal_places=2, help_text='Montant de perte imputé sur cette déclaration dans la devise du régime', max_digits=15, verbose_name='Montant utilisé'),
        ),
    ]
