# Generated by Django 6.0.3 on 2026-03-19 20:22

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalite', '0012_regime_fiscal_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annexefiscale',
            name='fichier',
            field=models.FileField(blank=True, help_text='Document PDF ou autre pièce jointe', max_length=500, null=True, storage=core.storage.S3FiscaliteStorage(), upload_to='fiscalite/annexes/', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='declarationfiscale',
            name='fichier_declaration',
            field=models.FileField(blank=True, help_text='Document PDF de la déclaration déposée', max_length=500, null=True, storage=core.storage.S3FiscaliteStorage(), upload_to='fiscalite/declarations/', verbose_name='Fichier déclaration'),
        ),
        migrations.AlterField(
            model_name='declarationfiscale',
            name='fichier_taxation',
            field=models.FileField(blank=True, help_text='Document PDF de la décision de taxation', max_length=500, null=True, storage=core.storage.S3FiscaliteStorage(), upload_to='fiscalite/taxations/', verbose_name='Fichier taxation'),
        ),
        migrations.AlterField(
            model_name='reclamationfiscale',
            name='fichier_decision',
            field=models.FileField(blank=True, help_text='Document PDF de la décision reçue', max_length=500, null=True, storage=core.storage.S3FiscaliteStorage(), upload_to='fiscalite/decisions/', verbose_name='Fichier décision'),
        ),
        migrations.AlterField(
            model_name='reclamationfiscale',
            name='fichier_reclamation',
            field=models.FileField(blank=True, help_text='Document PDF de la réclamation déposée', max_length=500, null=True, storage=core.storage.S3FiscaliteStorage(), upload_to='fiscalite/reclamations/', verbose_name='Fichier réclamation'),
        ),
    ]
