# Generated by Django 6.0.3 on 2026-03-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalite', '0013_storage_s3'),
    ]

    operations = [
        migrations.AddField(
            model_name='annexefiscale',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='correctionfiscale',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='declarationfiscale',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='optimisationfiscale',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='reclamationfiscale',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='reportperte',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='tauximposition',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='utilisationperte',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
    ]
