# Generated by Django 6.0.3 on 2026-03-24 22:50

import core.storage
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_contrat_position_alter_accesmandat_langue_saisie_and_more'),
        ('fiscalite', '0014_langue_saisie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcompteFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('langue_saisie', models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie')),
                ('type_acompte', models.CharField(choices=[('IFD', 'Impôt fédéral direct'), ('ICC', 'Impôt cantonal et communal'), ('IS', 'Impôt à la source'), ('AUTRE', 'Autre')], default='ICC', max_length=20, verbose_name="Type d'acompte")),
                ('annee_fiscale', models.IntegerField(verbose_name='Année fiscale')),
                ('numero_acompte', models.IntegerField(default=1, help_text='1er, 2e, 3e, 4e trimestre, etc.', verbose_name="N° d'acompte")),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant payé')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, verbose_name='Référence paiement')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('PAYE', 'Payé'), ('EN_RETARD', 'En retard'), ('ANNULE', 'Annulé')], db_index=True, default='PLANIFIE', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('declaration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acomptes', to='fiscalite.declarationfiscale', verbose_name='Déclaration liée')),
                ('mandat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acomptes_fiscaux', to='core.mandat', verbose_name='Mandat')),
            ],
            options={
                'verbose_name': 'Acompte fiscal',
                'verbose_name_plural': 'Acomptes fiscaux',
                'db_table': 'acomptes_fiscaux',
                'ordering': ['annee_fiscale', 'date_echeance'],
                'indexes': [models.Index(fields=['mandat', 'annee_fiscale'], name='acomptes_fi_mandat__8f1f1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImpotAnticipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('langue_saisie', models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie')),
                ('type_revenu', models.CharField(choices=[('DIVIDENDE', 'Dividende'), ('INTERET', 'Intérêt'), ('PRESTATION_ASSURANCE', "Prestation d'assurance"), ('LOT_LOTERIE', 'Lot de loterie'), ('AUTRE', 'Autre')], default='DIVIDENDE', max_length=30, verbose_name='Type de revenu')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('date_revenu', models.DateField(verbose_name='Date du revenu')),
                ('montant_brut', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant brut')),
                ('taux_retenue', models.DecimalField(decimal_places=2, default=Decimal('35.00'), help_text='35% en Suisse', max_digits=5, verbose_name='Taux de retenue (%)')),
                ('montant_retenu', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant retenu')),
                ('debiteur', models.CharField(blank=True, help_text='Société qui verse le dividende/intérêt', max_length=255, verbose_name='Débiteur')),
                ('date_demande_remboursement', models.DateField(blank=True, null=True, verbose_name='Date demande remboursement')),
                ('numero_formulaire', models.CharField(blank=True, help_text='DA-1, R-US, etc.', max_length=50, verbose_name='N° formulaire')),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant remboursé')),
                ('date_remboursement', models.DateField(blank=True, null=True, verbose_name='Date remboursement')),
                ('statut', models.CharField(choices=[('RETENU', 'Retenu'), ('REMBOURSEMENT_DEMANDE', 'Remboursement demandé'), ('REMBOURSE', 'Remboursé'), ('REFUSE', 'Refusé'), ('PRESCRIT', 'Prescrit')], db_index=True, default='RETENU', max_length=30, verbose_name='Statut')),
                ('fichier', models.FileField(blank=True, max_length=500, null=True, storage=core.storage.S3FiscaliteStorage(), upload_to='fiscalite/impot_anticipe/', verbose_name='Fichier')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('mandat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impots_anticipes', to='core.mandat', verbose_name='Mandat')),
            ],
            options={
                'verbose_name': 'Impôt anticipé',
                'verbose_name_plural': 'Impôts anticipés',
                'db_table': 'impots_anticipes',
                'ordering': ['-annee', '-date_revenu'],
                'indexes': [models.Index(fields=['mandat', 'annee'], name='impots_anti_mandat__38727a_idx')],
            },
        ),
    ]
