# Generated by merge script
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fiscalite", "0013_annexefiscale_langue_saisie_and_more"),
        ("fiscalite", "0015_acomptefiscal_impotanticipe"),
    ]

    operations = [
    ]
