# Generated by Django 5.2.8 on 2025-11-13 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertemetrique',
            name='acquittee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_acquittees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertemetrique',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertemetrique',
            name='mandat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mandat'),
        ),
        migrations.AddField(
            model_name='comparaisonperiode',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comparaisonperiode',
            name='mandat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparaisons', to='core.mandat'),
        ),
        migrations.AddField(
            model_name='exportdonnees',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportdonnees',
            name='demande_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportdonnees',
            name='mandat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='core.mandat'),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertemetrique',
            name='indicateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='analytics.indicateur'),
        ),
        migrations.AddField(
            model_name='planificationrapport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planificationrapport',
            name='mandat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planifications_rapports', to='core.mandat'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rapport',
            name='genere_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rapport',
            name='mandat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='core.mandat'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='planification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_generes', to='analytics.planificationrapport'),
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableaux_bord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='utilisateurs_partage',
            field=models.ManyToManyField(blank=True, related_name='tableaux_partages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valeurindicateur',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valeurindicateur',
            name='indicateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valeurs', to='analytics.indicateur'),
        ),
        migrations.AddField(
            model_name='valeurindicateur',
            name='mandat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valeurs_indicateurs', to='core.mandat'),
        ),
        migrations.AddField(
            model_name='alertemetrique',
            name='valeur_indicateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.valeurindicateur'),
        ),
        migrations.AddIndex(
            model_name='rapport',
            index=models.Index(fields=['mandat', 'type_rapport'], name='rapports_mandat__815420_idx'),
        ),
        migrations.AddIndex(
            model_name='rapport',
            index=models.Index(fields=['date_generation'], name='rapports_date_ge_c7d5b4_idx'),
        ),
        migrations.AddIndex(
            model_name='valeurindicateur',
            index=models.Index(fields=['indicateur', 'date_mesure'], name='valeurs_ind_indicat_388fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='valeurindicateur',
            index=models.Index(fields=['mandat', 'date_mesure'], name='valeurs_ind_mandat__fc4035_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='valeurindicateur',
            unique_together={('indicateur', 'mandat', 'date_mesure')},
        ),
        migrations.AddIndex(
            model_name='alertemetrique',
            index=models.Index(fields=['statut', 'niveau'], name='alertes_met_statut_b751fa_idx'),
        ),
        migrations.AddIndex(
            model_name='alertemetrique',
            index=models.Index(fields=['mandat', 'statut'], name='alertes_met_mandat__b3cf1b_idx'),
        ),
    ]
