# Generated by Django 6.0.2 on 2026-02-15 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertemetrique',
            name='acquittee_par',
            field=models.ForeignKey(blank=True, help_text="Utilisateur ayant pris en charge l'alerte", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_acquittees', to=settings.AUTH_USER_MODEL, verbose_name='Acquittée par'),
        ),
        migrations.AddField(
            model_name='alertemetrique',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='alertemetrique',
            name='mandat',
            field=models.ForeignKey(blank=True, help_text="Mandat concerné par l'alerte", null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AddField(
            model_name='comparaisonperiode',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='comparaisonperiode',
            name='mandat',
            field=models.ForeignKey(help_text='Mandat concerné par cette comparaison', on_delete=django.db.models.deletion.CASCADE, related_name='comparaisons', to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AddField(
            model_name='exportdonnees',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='exportdonnees',
            name='demande_par',
            field=models.ForeignKey(help_text="Utilisateur ayant demandé l'export", on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Demandé par'),
        ),
        migrations.AddField(
            model_name='exportdonnees',
            name='mandat',
            field=models.ForeignKey(help_text='Mandat dont les données sont exportées', on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='periodicite_ref',
            field=models.ForeignKey(blank=True, help_text="Fréquence de calcul de l'indicateur", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicateurs', to='core.periodicite', verbose_name='Périodicité'),
        ),
        migrations.AddField(
            model_name='alertemetrique',
            name='indicateur',
            field=models.ForeignKey(help_text="Indicateur ayant déclenché l'alerte", on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='analytics.indicateur', verbose_name='Indicateur'),
        ),
        migrations.AddField(
            model_name='modelerapport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='modelerapport',
            name='proprietaire',
            field=models.ForeignKey(blank=True, help_text='Utilisateur propriétaire (vide pour les modèles système)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modeles_rapport', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AddField(
            model_name='planificationrapport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='planificationrapport',
            name='frequence_ref',
            field=models.ForeignKey(blank=True, help_text='Fréquence de génération du rapport', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planifications_rapports', to='core.periodicite', verbose_name='Fréquence'),
        ),
        migrations.AddField(
            model_name='planificationrapport',
            name='mandat',
            field=models.ForeignKey(blank=True, help_text='Mandat concerné par cette planification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planifications_rapports', to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='genere_par',
            field=models.ForeignKey(help_text='Utilisateur ayant demandé la génération', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Généré par'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='mandat',
            field=models.ForeignKey(blank=True, help_text='Mandat concerné par ce rapport', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='planification',
            field=models.ForeignKey(blank=True, help_text='Planification ayant déclenché cette génération', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_generes', to='analytics.planificationrapport', verbose_name='Planification'),
        ),
        migrations.AddField(
            model_name='sectionrapport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='sectionrapport',
            name='rapport',
            field=models.ForeignKey(help_text='Rapport contenant cette section', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='analytics.rapport', verbose_name='Rapport'),
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='proprietaire',
            field=models.ForeignKey(help_text='Utilisateur ayant créé ce tableau de bord', on_delete=django.db.models.deletion.CASCADE, related_name='tableaux_bord', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='utilisateurs_partage',
            field=models.ManyToManyField(blank=True, help_text='Utilisateurs ayant accès à ce tableau de bord', related_name='tableaux_partages', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs partagés'),
        ),
        migrations.AddField(
            model_name='typegraphiquerapport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='sectionrapport',
            name='type_graphique',
            field=models.ForeignKey(blank=True, help_text='Graphique prédéfini à utiliser', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections_utilisant', to='analytics.typegraphiquerapport', verbose_name='Type de graphique'),
        ),
        migrations.AddField(
            model_name='valeurindicateur',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='valeurindicateur',
            name='indicateur',
            field=models.ForeignKey(help_text='Indicateur mesuré', on_delete=django.db.models.deletion.CASCADE, related_name='valeurs', to='analytics.indicateur', verbose_name='Indicateur'),
        ),
        migrations.AddField(
            model_name='valeurindicateur',
            name='mandat',
            field=models.ForeignKey(blank=True, help_text='Mandat concerné (optionnel pour indicateurs globaux)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valeurs_indicateurs', to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AddField(
            model_name='alertemetrique',
            name='valeur_indicateur',
            field=models.ForeignKey(blank=True, help_text="Valeur spécifique ayant déclenché l'alerte", null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.valeurindicateur', verbose_name='Valeur indicateur'),
        ),
        migrations.AddIndex(
            model_name='rapport',
            index=models.Index(fields=['mandat', 'type_rapport'], name='rapports_mandat__815420_idx'),
        ),
        migrations.AddIndex(
            model_name='rapport',
            index=models.Index(fields=['date_generation'], name='rapports_date_ge_c7d5b4_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionrapport',
            index=models.Index(fields=['rapport', 'ordre'], name='sections_ra_rapport_1f8f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='valeurindicateur',
            index=models.Index(fields=['indicateur', 'date_mesure'], name='valeurs_ind_indicat_388fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='valeurindicateur',
            index=models.Index(fields=['mandat', 'date_mesure'], name='valeurs_ind_mandat__fc4035_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='valeurindicateur',
            unique_together={('indicateur', 'mandat', 'date_mesure')},
        ),
        migrations.AddIndex(
            model_name='alertemetrique',
            index=models.Index(fields=['statut', 'niveau'], name='alertes_met_statut_b751fa_idx'),
        ),
        migrations.AddIndex(
            model_name='alertemetrique',
            index=models.Index(fields=['mandat', 'statut'], name='alertes_met_mandat__b3cf1b_idx'),
        ),
    ]
