# Generated by Django 6.0.3 on 2026-03-19 20:22

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportdonnees',
            name='fichier',
            field=models.FileField(blank=True, help_text="Fichier d'export généré", max_length=500, null=True, storage=core.storage.S3ExportStorage(), upload_to='exports/', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='fichier',
            field=models.FileField(blank=True, help_text='Fichier du rapport généré', max_length=500, null=True, storage=core.storage.S3ExportStorage(), upload_to='rapports/', verbose_name='Fichier'),
        ),
    ]
