# Generated by Django 5.2.8 on 2025-11-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicateur',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='description_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='nom_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='nom_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='nom_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='nom_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='nom_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='nom_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='nom_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='nom_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='description_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='nom_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='nom_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='nom_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='nom_it',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
