# Generated by merge script
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_alertemetrique_langue_saisie_and_more"),
        ("analytics", "0004_langue_saisie"),
    ]

    operations = [
    ]
