# Generated by Django 6.0.1 on 2026-01-10 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_fix_tableaux_bord_icons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleRapport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type_rapport', models.CharField(choices=[('BILAN', 'Bilan'), ('COMPTE_RESULTATS', 'Compte de résultats'), ('BALANCE', 'Balance'), ('TRESORERIE', 'Tableau de trésorerie'), ('TVA', 'Rapport TVA'), ('SALAIRES', 'Rapport salaires'), ('EVOLUTION_CA', 'Évolution CA'), ('RENTABILITE', 'Analyse rentabilité'), ('CUSTOM', 'Rapport personnalisé')], max_length=30)),
                ('sections_defaut', models.JSONField(default=list, help_text='\n        Liste des sections par défaut:\n        [\n            {"type": "titre", "contenu": "Rapport {type_rapport}"},\n            {"type": "texte", "contenu": "<p>Introduction...</p>"},\n            {"type": "graphique", "code_graphique": "BILAN_REPARTITION"},\n            {"type": "tableau", "config": {"source": "comptes_bilan"}}\n        ]\n        ')),
                ('parametres_defaut', models.JSONField(blank=True, default=dict)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('nombre_utilisations', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('proprietaire', models.ForeignKey(blank=True, help_text='Null pour les modèles système', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modeles_rapport', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modèle de rapport',
                'verbose_name_plural': 'Modèles de rapport',
                'db_table': 'modeles_rapport',
                'ordering': ['type_rapport', 'ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeGraphiqueRapport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('code', models.CharField(db_index=True, help_text='Code unique ex: BILAN_REPARTITION_ACTIF_PASSIF', max_length=100, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description de ce que montre le graphique')),
                ('types_rapport_compatibles', models.JSONField(default=list, help_text='Liste des types de rapports: ["BILAN", "COMPTE_RESULTATS"]')),
                ('type_graphique', models.CharField(choices=[('donut', 'Donut / Camembert'), ('bar', 'Barres verticales'), ('horizontal_bar', 'Barres horizontales'), ('line', 'Ligne'), ('area', 'Aire'), ('stacked_bar', 'Barres empilées')], max_length=20)),
                ('unite_donnees', models.CharField(choices=[('CHF', 'Montants (CHF)'), ('POURCENTAGE', 'Pourcentages (%)'), ('NOMBRE', 'Nombres/Comptages')], default='CHF', help_text='Unité des données pour éviter les mélanges', max_length=20)),
                ('config_source', models.JSONField(default=dict, help_text='\n        Configuration pour récupérer les données:\n        {\n            "source": "ecritures_comptables",\n            "agregation": "sum",\n            "champ_valeur": "montant",\n            "grouper_par": "classe",\n            "filtres": {"classe__in": [1, 2]}\n        }\n        ')),
                ('options_affichage', models.JSONField(default=dict, help_text='\n        Options de style et d\'affichage:\n        {\n            "couleurs": ["#4680FF", "#2CA87F"],\n            "afficher_legende": true,\n            "afficher_valeurs": true,\n            "format_valeur": "currency"\n        }\n        ')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Type de graphique rapport',
                'verbose_name_plural': 'Types de graphiques rapport',
                'db_table': 'types_graphique_rapport',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='SectionRapport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('ordre', models.PositiveIntegerField(default=0, help_text='Position de la section dans le rapport')),
                ('type_section', models.CharField(choices=[('titre', 'Titre'), ('texte', 'Texte/Paragraphe'), ('graphique', 'Graphique'), ('tableau', 'Tableau de données'), ('kpi', 'Indicateurs clés (KPI)'), ('saut_page', 'Saut de page'), ('separateur', 'Séparateur horizontal')], max_length=20)),
                ('contenu_texte', models.TextField(blank=True, help_text='Contenu HTML pour les sections titre/texte')),
                ('config', models.JSONField(blank=True, default=dict, help_text='\n        Configuration spécifique à cette section:\n        - Pour graphique: {"titre_personnalise": "Mon titre"}\n        - Pour tableau: {"colonnes": ["compte", "libelle", "solde"], "max_lignes": 20}\n        - Pour kpi: {"indicateurs": ["ca_total", "marge_brute"]}\n        ')),
                ('visible', models.BooleanField(default=True, help_text="Si False, la section n'apparaît pas dans le PDF")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='analytics.rapport')),
                ('type_graphique', models.ForeignKey(blank=True, help_text='Graphique prédéfini à utiliser', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections_utilisant', to='analytics.typegraphiquerapport')),
            ],
            options={
                'verbose_name': 'Section de rapport',
                'verbose_name_plural': 'Sections de rapport',
                'db_table': 'sections_rapport',
                'ordering': ['rapport', 'ordre'],
                'indexes': [models.Index(fields=['rapport', 'ordre'], name='sections_ra_rapport_1f8f2a_idx')],
            },
        ),
    ]
