# Generated by Django 6.0.2 on 2026-02-15 08:09

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OntologieType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('categorie', models.CharField(choices=[('entity', 'Entité'), ('relation', 'Relation')], max_length=10, verbose_name='Catégorie')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('nom_pluriel', models.CharField(blank=True, max_length=100, verbose_name='Nom pluriel')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icone', models.CharField(blank=True, default='ph-circle', help_text='Classe Phosphor Icons (ex: ph-user, ph-building)', max_length=50, verbose_name='Icône')),
                ('couleur', models.CharField(default='#6366f1', help_text='Code hexadécimal (ex: #6366f1)', max_length=7, verbose_name='Couleur')),
                ('schema_attributs', models.JSONField(blank=True, default=dict, help_text='Schéma JSON décrivant les champs dynamiques', verbose_name='Schéma des attributs')),
                ('verbe', models.CharField(blank=True, help_text='Ex: "emploie", "possède"', max_length=100, verbose_name='Verbe')),
                ('verbe_inverse', models.CharField(blank=True, help_text='Ex: "est employé par", "est possédé par"', max_length=100, verbose_name='Verbe inverse')),
                ('bidirectionnel', models.BooleanField(default=False, verbose_name='Bidirectionnel')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('cible_types_autorises', models.ManyToManyField(blank=True, help_text="Types d'entités pouvant être cible de cette relation", related_name='relation_cibles', to='graph.ontologietype', verbose_name='Types cible autorisés')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('source_types_autorises', models.ManyToManyField(blank=True, help_text="Types d'entités pouvant être source de cette relation", related_name='relation_sources', to='graph.ontologietype', verbose_name='Types source autorisés')),
            ],
            options={
                'verbose_name': "Type d'ontologie",
                'verbose_name_plural': "Types d'ontologie",
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Entite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('attributs', models.JSONField(blank=True, default=dict, help_text='Attributs dynamiques selon le schéma du type', verbose_name='Attributs')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Géolocalisation')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('embedding_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Embedding mis à jour le')),
                ('source', models.CharField(choices=[('manuelle', 'Saisie manuelle'), ('import', 'Import CSV/Excel'), ('ocr', 'Extraction OCR'), ('api', 'API externe'), ('systeme', 'Système')], default='manuelle', max_length=20, verbose_name='Source')),
                ('confiance', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Score de confiance')),
                ('verifie', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('verifie_at', models.DateTimeField(blank=True, null=True, verbose_name='Vérifié le')),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('verifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entites_verifiees', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par')),
                ('type', models.ForeignKey(limit_choices_to={'categorie': 'entity'}, on_delete=django.db.models.deletion.PROTECT, related_name='entites', to='graph.ontologietype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Entité',
                'verbose_name_plural': 'Entités',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('attributs', models.JSONField(blank=True, default=dict, verbose_name='Attributs')),
                ('poids', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Poids')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('en_cours', models.BooleanField(default=True, verbose_name='En cours')),
                ('confiance', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Score de confiance')),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_entrantes', to='graph.entite', verbose_name='Entité cible')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('document_preuve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relations_graphe', to='documents.document', verbose_name='Document preuve')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_sortantes', to='graph.entite', verbose_name='Entité source')),
                ('type', models.ForeignKey(limit_choices_to={'categorie': 'relation'}, on_delete=django.db.models.deletion.PROTECT, related_name='relations', to='graph.ontologietype', verbose_name='Type de relation')),
            ],
            options={
                'verbose_name': 'Relation',
                'verbose_name_plural': 'Relations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequeteSauvegardee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('types_entites', models.JSONField(blank=True, default=list, help_text="Liste des IDs de types d'entités à inclure", verbose_name="Types d'entités")),
                ('types_relations', models.JSONField(blank=True, default=list, help_text='Liste des IDs de types de relations à inclure', verbose_name='Types de relations')),
                ('profondeur', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Profondeur')),
                ('date_min', models.DateField(blank=True, null=True, verbose_name='Date minimum')),
                ('date_max', models.DateField(blank=True, null=True, verbose_name='Date maximum')),
                ('parametres_vue', models.JSONField(blank=True, default=dict, help_text='Position caméra, zoom, filtres visuels, etc.', verbose_name='Paramètres de vue')),
                ('partage', models.BooleanField(default=False, verbose_name='Partagée')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('entite_depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='graph.entite', verbose_name='Entité de départ')),
            ],
            options={
                'verbose_name': 'Requête sauvegardée',
                'verbose_name_plural': 'Requêtes sauvegardées',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('type', models.CharField(choices=[('doublon', 'Doublon potentiel'), ('flux_suspect', 'Flux suspect'), ('incoherence', 'Incohérence temporelle'), ('connexion_cachee', 'Connexion cachée'), ('orphelin', 'Entité orpheline')], max_length=20, verbose_name="Type d'anomalie")),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Score de confiance')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', "En cours d'analyse"), ('confirme', 'Confirmé'), ('rejete', 'Rejeté'), ('resolu', 'Résolu')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('traite_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('commentaire_resolution', models.TextField(blank=True, verbose_name='Commentaire de résolution')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='graph.entite', verbose_name='Entité concernée')),
                ('entite_liee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies_liees', to='graph.entite', verbose_name='Entité liée')),
            ],
            options={
                'verbose_name': 'Anomalie',
                'verbose_name_plural': 'Anomalies',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['type', 'statut'], name='graph_anom_type_statut_idx'), models.Index(fields=['score'], name='graph_anom_score_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ontologietype',
            index=models.Index(fields=['categorie', 'nom'], name='graph_onttype_cat_nom_idx'),
        ),
        migrations.AddIndex(
            model_name='entite',
            index=models.Index(fields=['type', 'nom'], name='graph_entite_type_nom_idx'),
        ),
        migrations.AddIndex(
            model_name='entite',
            index=models.Index(fields=['source', 'confiance'], name='graph_entite_src_conf_idx'),
        ),
        migrations.AddIndex(
            model_name='entite',
            index=models.Index(fields=['content_type', 'object_id'], name='graph_entite_gfk_idx'),
        ),
        migrations.AddIndex(
            model_name='entite',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geom'], name='graph_entite_geom_gist_idx'),
        ),
        migrations.AddIndex(
            model_name='entite',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='graph_entite_emb_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='relation',
            index=models.Index(fields=['type', 'en_cours'], name='graph_rel_type_encours_idx'),
        ),
        migrations.AddIndex(
            model_name='relation',
            index=models.Index(fields=['date_debut', 'date_fin'], name='graph_rel_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='relation',
            constraint=models.UniqueConstraint(fields=('source', 'cible', 'type'), name='graph_relation_unique_src_cbl_type'),
        ),
    ]
