# Generated by Django 6.0.3 on 2026-04-04 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('graph', '0002_langue_saisie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalie',
            name='commentaire_resolution_de',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire de résolution'),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='commentaire_resolution_en',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire de résolution'),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='commentaire_resolution_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire de résolution'),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='commentaire_resolution_it',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire de résolution'),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='titre_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='titre_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='titre_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='titre_it',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='entite',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='entite',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='entite',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='entite',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='entite',
            name='nom_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='entite',
            name='nom_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='entite',
            name='nom_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='entite',
            name='nom_it',
            field=models.CharField(max_length=255, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='ontologietype',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='ontologietype',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='ontologietype',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='ontologietype',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='ontologietype',
            name='nom_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='ontologietype',
            name='nom_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='ontologietype',
            name='nom_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='ontologietype',
            name='nom_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='ontologietype',
            name='nom_pluriel_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom pluriel'),
        ),
        migrations.AddField(
            model_name='ontologietype',
            name='nom_pluriel_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom pluriel'),
        ),
        migrations.AddField(
            model_name='ontologietype',
            name='nom_pluriel_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom pluriel'),
        ),
        migrations.AddField(
            model_name='ontologietype',
            name='nom_pluriel_it',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom pluriel'),
        ),
        migrations.AddField(
            model_name='ontologietype',
            name='verbe_de',
            field=models.CharField(blank=True, help_text='Ex: "emploie", "possède"', max_length=100, null=True, verbose_name='Verbe'),
        ),
        migrations.AddField(
            model_name='ontologietype',
            name='verbe_en',
            field=models.CharField(blank=True, help_text='Ex: "emploie", "possède"', max_length=100, null=True, verbose_name='Verbe'),
        ),
        migrations.AddField(
            model_name='ontologietype',
            name='verbe_fr',
            field=models.CharField(blank=True, help_text='Ex: "emploie", "possède"', max_length=100, null=True, verbose_name='Verbe'),
        ),
        migrations.AddField(
            model_name='ontologietype',
            name='verbe_inverse_de',
            field=models.CharField(blank=True, help_text='Ex: "est employé par", "est possédé par"', max_length=100, null=True, verbose_name='Verbe inverse'),
        ),
        migrations.AddField(
            model_name='ontologietype',
            name='verbe_inverse_en',
            field=models.CharField(blank=True, help_text='Ex: "est employé par", "est possédé par"', max_length=100, null=True, verbose_name='Verbe inverse'),
        ),
        migrations.AddField(
            model_name='ontologietype',
            name='verbe_inverse_fr',
            field=models.CharField(blank=True, help_text='Ex: "est employé par", "est possédé par"', max_length=100, null=True, verbose_name='Verbe inverse'),
        ),
        migrations.AddField(
            model_name='ontologietype',
            name='verbe_inverse_it',
            field=models.CharField(blank=True, help_text='Ex: "est employé par", "est possédé par"', max_length=100, null=True, verbose_name='Verbe inverse'),
        ),
        migrations.AddField(
            model_name='ontologietype',
            name='verbe_it',
            field=models.CharField(blank=True, help_text='Ex: "emploie", "possède"', max_length=100, null=True, verbose_name='Verbe'),
        ),
        migrations.AddField(
            model_name='requetesauvegardee',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='requetesauvegardee',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='requetesauvegardee',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='requetesauvegardee',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='requetesauvegardee',
            name='nom_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='requetesauvegardee',
            name='nom_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='requetesauvegardee',
            name='nom_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='requetesauvegardee',
            name='nom_it',
            field=models.CharField(max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AddIndex(
            model_name='entite',
            index=models.Index(fields=['type', 'nom_fr'], name='graph_entite_type_nom_idx-fr'),
        ),
        migrations.AddIndex(
            model_name='entite',
            index=models.Index(fields=['type', 'nom_de'], name='graph_entite_type_nom_idx-de'),
        ),
        migrations.AddIndex(
            model_name='entite',
            index=models.Index(fields=['type', 'nom_it'], name='graph_entite_type_nom_idx-it'),
        ),
        migrations.AddIndex(
            model_name='entite',
            index=models.Index(fields=['type', 'nom_en'], name='graph_entite_type_nom_idx-en'),
        ),
        migrations.AddIndex(
            model_name='ontologietype',
            index=models.Index(fields=['categorie', 'nom_fr'], name='graph_onttype_cat_nom_idx-fr'),
        ),
        migrations.AddIndex(
            model_name='ontologietype',
            index=models.Index(fields=['categorie', 'nom_de'], name='graph_onttype_cat_nom_idx-de'),
        ),
        migrations.AddIndex(
            model_name='ontologietype',
            index=models.Index(fields=['categorie', 'nom_it'], name='graph_onttype_cat_nom_idx-it'),
        ),
        migrations.AddIndex(
            model_name='ontologietype',
            index=models.Index(fields=['categorie', 'nom_en'], name='graph_onttype_cat_nom_idx-en'),
        ),
    ]
