# Generated by Django 6.0.2 on 2026-02-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titre'),
        ),
    ]
