# Generated by Django 6.0.3 on 2026-04-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_conversation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title_it',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre'),
        ),
    ]
