# Generated by Django 5.2.8 on 2025-11-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codetva',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codetva',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codetva',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codetva',
            name='description_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codetva',
            name='libelle_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='codetva',
            name='libelle_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='codetva',
            name='libelle_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='codetva',
            name='libelle_it',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
