# Generated by Django 5.2.8 on 2025-11-19 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tva', '0002_codetva_description_de_codetva_description_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='codetva',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='codetva',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='codetva',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='codetva',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='configurationtva',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='configurationtva',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='configurationtva',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='configurationtva',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='correctiontva',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='correctiontva',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='correctiontva',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='correctiontva',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='lignetva',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='lignetva',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='lignetva',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='lignetva',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='operationtva',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='operationtva',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='operationtva',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='operationtva',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='tauxtva',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='tauxtva',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='tauxtva',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='tauxtva',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
    ]
