# Generated by Django 6.0.2 on 2026-02-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tva', '0004_regime_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctiontva',
            name='base_calcul',
            field=models.DecimalField(decimal_places=2, help_text='Montant servant de base au calcul dans la devise du régime', max_digits=15, verbose_name='Base de calcul'),
        ),
        migrations.AlterField(
            model_name='correctiontva',
            name='montant_correction',
            field=models.DecimalField(decimal_places=2, help_text='Montant de la correction dans la devise du régime', max_digits=15, verbose_name='Montant de correction'),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='chiffre_affaires_imposable',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Chiffre d'affaires soumis à la TVA dans la devise du régime", max_digits=15, verbose_name='CA imposable'),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='chiffre_affaires_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Chiffre d'affaires total dans la devise du régime", max_digits=15, verbose_name='CA total'),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='corrections_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total des corrections dans la devise du régime', max_digits=15, verbose_name='Corrections totales'),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='deductions_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total des déductions dans la devise du régime', max_digits=15, verbose_name='Déductions totales'),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='tva_due_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total de la TVA due dans la devise du régime', max_digits=15, verbose_name='TVA due totale'),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='tva_prealable_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Total de l'impôt préalable déductible dans la devise du régime", max_digits=15, verbose_name='TVA préalable totale'),
        ),
        migrations.AlterField(
            model_name='lignetva',
            name='base_imposable',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant hors taxe dans la devise du régime', max_digits=15, verbose_name='Base imposable'),
        ),
        migrations.AlterField(
            model_name='lignetva',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de TVA calculé dans la devise du régime', max_digits=15, verbose_name='Montant TVA'),
        ),
        migrations.AlterField(
            model_name='operationtva',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, help_text='Montant hors taxe dans la devise du régime', max_digits=15, verbose_name='Montant HT'),
        ),
        migrations.AlterField(
            model_name='operationtva',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, help_text='Montant toutes taxes comprises dans la devise du régime', max_digits=15, verbose_name='Montant TTC'),
        ),
        migrations.AlterField(
            model_name='operationtva',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, help_text='Montant de TVA dans la devise du régime', max_digits=15, verbose_name='Montant TVA'),
        ),
    ]
