# Generated by Django 6.0.3 on 2026-03-07 23:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_parametre_metier'),
        ('tva', '0008_configurationtva_regime_not_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tauxtva',
            name='type_taux',
            field=models.CharField(choices=[('NORMAL', 'Taux normal'), ('REDUIT', 'Taux réduit'), ('SPECIAL', 'Taux spécial hébergement'), ('EXONERE', 'Exonéré'), ('SSS', 'Taux de la dette fiscale nette (SSS)')], help_text='Catégorie du taux TVA', max_length=10, verbose_name='Type de taux'),
        ),
        migrations.CreateModel(
            name='RapprochementAnnuel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('annee', models.IntegerField(help_text='Année fiscale du rapprochement', verbose_name='Année')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('DEPOSE', 'Déposé')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('ca_comptable', models.DecimalField(decimal_places=2, default=0, help_text="Chiffre d'affaires total depuis la comptabilité", max_digits=15, verbose_name='CA comptable')),
                ('ca_declare', models.DecimalField(decimal_places=2, default=0, help_text="Chiffre d'affaires total déclaré dans les décomptes TVA", max_digits=15, verbose_name='CA déclaré')),
                ('ecart_ca', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Écart CA')),
                ('tva_due_comptable', models.DecimalField(decimal_places=2, default=0, help_text='TVA due depuis les comptes de passif (2200)', max_digits=15, verbose_name='TVA due comptable')),
                ('tva_due_declaree', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='TVA due déclarée')),
                ('ecart_tva_due', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Écart TVA due')),
                ('tva_prealable_comptable', models.DecimalField(decimal_places=2, default=0, help_text="Impôt préalable depuis les comptes d'actif (1170)", max_digits=15, verbose_name='TVA préalable comptable')),
                ('tva_prealable_declaree', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='TVA préalable déclarée')),
                ('ecart_tva_prealable', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Écart TVA préalable')),
                ('declaration_complementaire_necessaire', models.BooleanField(default=False, verbose_name='Déclaration complémentaire nécessaire')),
                ('montant_complementaire', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant complémentaire')),
                ('date_limite', models.DateField(blank=True, help_text="180 jours après la clôture de l'exercice", null=True, verbose_name='Date limite')),
                ('remarques', models.TextField(blank=True, verbose_name='Remarques')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('mandat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapprochements_tva', to='core.mandat', verbose_name='Mandat')),
            ],
            options={
                'verbose_name': 'Rapprochement annuel TVA',
                'verbose_name_plural': 'Rapprochements annuels TVA',
                'db_table': 'rapprochements_annuels_tva',
                'ordering': ['-annee'],
                'unique_together': {('mandat', 'annee')},
            },
        ),
    ]
