# Generated by Django 6.0.3 on 2026-03-19 20:22

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tva', '0009_add_parametre_metier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declarationtva',
            name='fichier_pdf',
            field=models.FileField(blank=True, help_text='Version PDF de la déclaration', max_length=500, null=True, storage=core.storage.S3TVAStorage(), upload_to='tva/pdf/', verbose_name='Fichier PDF'),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='fichier_xml',
            field=models.FileField(blank=True, help_text='Export XML pour soumission électronique', max_length=500, null=True, storage=core.storage.S3TVAStorage(), upload_to='tva/xml/', verbose_name='Fichier XML'),
        ),
    ]
