# Generated by Django 6.0.3 on 2026-04-03 00:39

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tva', '0009_add_parametre_metier'),
    ]

    operations = [
        migrations.AddField(
            model_name='codetva',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='configurationtva',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='correctiontva',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='declarationtva',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='lignetva',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='operationtva',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='rapprochementannuel',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='regimefiscal',
            name='delai_paiement_defaut',
            field=models.IntegerField(default=30, verbose_name='Délai de paiement par défaut (jours)'),
        ),
        migrations.AddField(
            model_name='regimefiscal',
            name='identifiants_requis',
            field=models.JSONField(blank=True, default=list, help_text="Codes des TypeIdentifiantLegal requis pour ce régime. Ex: ['IDE', 'TVA']", verbose_name="Types d'identifiants requis"),
        ),
        migrations.AddField(
            model_name='regimefiscal',
            name='indemnite_recouvrement',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant fixe ajouté en cas de recouvrement (ex: 40 EUR en France)', max_digits=10, verbose_name='Indemnité forfaitaire de recouvrement'),
        ),
        migrations.AddField(
            model_name='regimefiscal',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='regimefiscal',
            name='mentions_obligatoires',
            field=models.JSONField(blank=True, default=list, help_text='Liste des mentions requises sur les factures. Ex: [{code, texte, type_document}]', verbose_name='Mentions légales obligatoires'),
        ),
        migrations.AddField(
            model_name='regimefiscal',
            name='nombre_relances_max',
            field=models.PositiveIntegerField(default=4, verbose_name='Nombre maximum de relances'),
        ),
        migrations.AddField(
            model_name='regimefiscal',
            name='penalite_retard_taux',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Taux annuel applicable en cas de retard de paiement', max_digits=5, verbose_name='Taux pénalités de retard (%)'),
        ),
        migrations.AddField(
            model_name='regimefiscal',
            name='seuil_facture_simplifiee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant TTC en dessous duquel la facture est simplifiée (ex: 400 CHF en Suisse, 150 EUR en France)', max_digits=10, null=True, verbose_name='Seuil facture simplifiée'),
        ),
        migrations.AddField(
            model_name='regimefiscal',
            name='suppression_facture_emise',
            field=models.BooleanField(default=False, help_text='Si False, seules les factures en brouillon peuvent être supprimées (recommandé)', verbose_name='Autoriser suppression facture émise'),
        ),
        migrations.AddField(
            model_name='tauxtva',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='fichier_pdf',
            field=models.FileField(blank=True, help_text='Version PDF de la déclaration', max_length=500, null=True, storage=core.storage.S3TVAStorage(), upload_to='tva/pdf/', verbose_name='Fichier PDF'),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='fichier_xml',
            field=models.FileField(blank=True, help_text='Export XML pour soumission électronique', max_length=500, null=True, storage=core.storage.S3TVAStorage(), upload_to='tva/xml/', verbose_name='Fichier XML'),
        ),
    ]
