# Generated by merge script
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tva", "0010_codetva_langue_saisie_configurationtva_langue_saisie_and_more"),
        ("tva", "0011_langue_saisie"),
    ]

    operations = [
    ]
