# Generated by Django 5.2.8 on 2025-11-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriedocument',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriedocument',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriedocument',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriedocument',
            name='description_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriedocument',
            name='nom_de',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categoriedocument',
            name='nom_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categoriedocument',
            name='nom_fr',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categoriedocument',
            name='nom_it',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='description_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='notes_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='notes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='notes_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='notes_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typedocument',
            name='libelle_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='typedocument',
            name='libelle_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='typedocument',
            name='libelle_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='typedocument',
            name='libelle_it',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
