# Generated by Django 6.0.2 on 2026-02-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('USER', 'Utilisateur'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'Système')], db_index=True, help_text='Auteur du message (utilisateur, assistant ou système)', max_length=20, verbose_name='Rôle'),
        ),
    ]
