# Generated by Django 6.0.2

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_message_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('code', models.CharField(help_text='Code technique unique de la source', max_length=50, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(help_text='Nom affiché de la source', max_length=150, verbose_name='Libellé')),
                ('libelle_fr', models.CharField(help_text='Nom affiché de la source', max_length=150, null=True, verbose_name='Libellé')),
                ('libelle_de', models.CharField(help_text='Nom affiché de la source', max_length=150, null=True, verbose_name='Libellé')),
                ('libelle_it', models.CharField(help_text='Nom affiché de la source', max_length=150, null=True, verbose_name='Libellé')),
                ('libelle_en', models.CharField(help_text='Nom affiché de la source', max_length=150, null=True, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, help_text='Description détaillée de la source', verbose_name='Description')),
                ('description_fr', models.TextField(blank=True, help_text='Description détaillée de la source', null=True, verbose_name='Description')),
                ('description_de', models.TextField(blank=True, help_text='Description détaillée de la source', null=True, verbose_name='Description')),
                ('description_it', models.TextField(blank=True, help_text='Description détaillée de la source', null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, help_text='Description détaillée de la source', null=True, verbose_name='Description')),
                ('origine', models.CharField(choices=[('INTERNE', 'Interne (collaborateur fiduciaire)'), ('EXTERNE', 'Externe (client et ses collaborateurs)')], help_text='Interne = collaborateur STAFF de la fiduciaire, Externe = utilisateur CLIENT et ses collaborateurs', max_length=10, verbose_name='Origine')),
                ('module_applicatif', models.CharField(blank=True, help_text='Nom du module Django générant le document (ex: facturation, salaires)', max_length=50, verbose_name='Module applicatif')),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône (ex: upload, file-invoice)", max_length=50, verbose_name='Icône')),
                ('ordre', models.IntegerField(default=0, help_text="Position d'affichage dans les listes", verbose_name='Ordre')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Source de document',
                'verbose_name_plural': 'Sources de document',
                'db_table': 'sources_document',
                'ordering': ['origine', 'ordre', 'libelle'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.ForeignKey(
                blank=True,
                help_text='Origine du document (upload, module interne, import, etc.)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='documents',
                to='documents.sourcedocument',
                verbose_name='Source',
            ),
        ),
    ]
