# Data migration: populate SourceDocument with predefined sources

from django.db import migrations


SOURCES_PREDEFINIES = [
    # ═══════════════════════════════════════════════════════════════
    # SOURCES EXTERNES (uploads utilisateurs, clients, imports)
    # ═══════════════════════════════════════════════════════════════
    {
        'code': 'upload_utilisateur',
        'libelle_fr': 'Upload utilisateur',
        'libelle_de': 'Benutzer-Upload',
        'libelle_it': 'Caricamento utente',
        'libelle_en': 'User upload',
        'description_fr': 'Document uploadé manuellement par un collaborateur de la fiduciaire',
        'description_de': 'Dokument manuell von einem Treuhändermitarbeiter hochgeladen',
        'description_it': 'Documento caricato manualmente da un collaboratore della fiduciaria',
        'description_en': 'Document manually uploaded by a fiduciary employee',
        'origine': 'EXTERNE',
        'module_applicatif': '',
        'icone': 'upload',
        'ordre': 10,
    },
    {
        'code': 'upload_client',
        'libelle_fr': 'Upload client',
        'libelle_de': 'Kunden-Upload',
        'libelle_it': 'Caricamento cliente',
        'libelle_en': 'Client upload',
        'description_fr': 'Document déposé par un client externe via le portail client',
        'description_de': 'Dokument von einem externen Kunden über das Kundenportal hochgeladen',
        'description_it': 'Documento depositato da un cliente esterno tramite il portale clienti',
        'description_en': 'Document uploaded by an external client via the client portal',
        'origine': 'EXTERNE',
        'module_applicatif': '',
        'icone': 'user-upload',
        'ordre': 20,
    },
    {
        'code': 'import_csv',
        'libelle_fr': 'Import CSV/Excel',
        'libelle_de': 'CSV/Excel-Import',
        'libelle_it': 'Importazione CSV/Excel',
        'libelle_en': 'CSV/Excel import',
        'description_fr': 'Document ou données importés depuis un fichier CSV ou Excel',
        'description_de': 'Dokument oder Daten aus einer CSV- oder Excel-Datei importiert',
        'description_it': 'Documento o dati importati da un file CSV o Excel',
        'description_en': 'Document or data imported from a CSV or Excel file',
        'origine': 'EXTERNE',
        'module_applicatif': '',
        'icone': 'file-spreadsheet',
        'ordre': 30,
    },
    {
        'code': 'email_entrant',
        'libelle_fr': 'E-mail entrant',
        'libelle_de': 'Eingehende E-Mail',
        'libelle_it': 'E-mail in entrata',
        'libelle_en': 'Incoming email',
        'description_fr': 'Pièce jointe extraite d\'un e-mail reçu',
        'description_de': 'Anhang aus einer empfangenen E-Mail extrahiert',
        'description_it': 'Allegato estratto da un\'e-mail ricevuta',
        'description_en': 'Attachment extracted from a received email',
        'origine': 'EXTERNE',
        'module_applicatif': 'mailing',
        'icone': 'mail',
        'ordre': 40,
    },
    {
        'code': 'api_externe',
        'libelle_fr': 'API externe',
        'libelle_de': 'Externe API',
        'libelle_it': 'API esterna',
        'libelle_en': 'External API',
        'description_fr': 'Document reçu via une API tierce ou intégration externe',
        'description_de': 'Dokument über eine Drittanbieter-API oder externe Integration empfangen',
        'description_it': 'Documento ricevuto tramite un\'API di terze parti o integrazione esterna',
        'description_en': 'Document received via a third-party API or external integration',
        'origine': 'EXTERNE',
        'module_applicatif': '',
        'icone': 'plug',
        'ordre': 50,
    },
    {
        'code': 'scan',
        'libelle_fr': 'Numérisation / Scan',
        'libelle_de': 'Digitalisierung / Scan',
        'libelle_it': 'Scansione / Digitalizzazione',
        'libelle_en': 'Scanning / Digitization',
        'description_fr': 'Document numérisé depuis un scanner ou appareil mobile',
        'description_de': 'Dokument von einem Scanner oder Mobilgerät digitalisiert',
        'description_it': 'Documento digitalizzato da uno scanner o dispositivo mobile',
        'description_en': 'Document scanned from a scanner or mobile device',
        'origine': 'EXTERNE',
        'module_applicatif': '',
        'icone': 'scan',
        'ordre': 60,
    },
    {
        'code': 'portail_client',
        'libelle_fr': 'Portail client',
        'libelle_de': 'Kundenportal',
        'libelle_it': 'Portale clienti',
        'libelle_en': 'Client portal',
        'description_fr': 'Document déposé via le portail en libre-service du client',
        'description_de': 'Dokument über das Kunden-Selbstbedienungsportal hochgeladen',
        'description_it': 'Documento depositato tramite il portale self-service del cliente',
        'description_en': 'Document uploaded via the client self-service portal',
        'origine': 'EXTERNE',
        'module_applicatif': '',
        'icone': 'globe',
        'ordre': 70,
    },

    # ═══════════════════════════════════════════════════════════════
    # SOURCES INTERNES (générées par les modules du système)
    # ═══════════════════════════════════════════════════════════════
    {
        'code': 'facturation_pdf',
        'libelle_fr': 'Facture générée',
        'libelle_de': 'Generierte Rechnung',
        'libelle_it': 'Fattura generata',
        'libelle_en': 'Generated invoice',
        'description_fr': 'PDF de facture généré par le module de facturation',
        'description_de': 'Rechnungs-PDF vom Fakturierungsmodul generiert',
        'description_it': 'PDF di fattura generato dal modulo di fatturazione',
        'description_en': 'Invoice PDF generated by the billing module',
        'origine': 'INTERNE',
        'module_applicatif': 'facturation',
        'icone': 'file-invoice',
        'ordre': 100,
    },
    {
        'code': 'salaires_fiche',
        'libelle_fr': 'Fiche de salaire générée',
        'libelle_de': 'Generierte Lohnabrechnung',
        'libelle_it': 'Busta paga generata',
        'libelle_en': 'Generated payslip',
        'description_fr': 'Fiche de salaire PDF générée par le module salaires',
        'description_de': 'Lohnabrechnungs-PDF vom Lohnmodul generiert',
        'description_it': 'PDF della busta paga generato dal modulo stipendi',
        'description_en': 'Payslip PDF generated by the payroll module',
        'origine': 'INTERNE',
        'module_applicatif': 'salaires',
        'icone': 'file-text',
        'ordre': 110,
    },
    {
        'code': 'salaires_certificat',
        'libelle_fr': 'Certificat de salaire généré',
        'libelle_de': 'Generierter Lohnausweis',
        'libelle_it': 'Certificato di salario generato',
        'libelle_en': 'Generated salary certificate',
        'description_fr': 'Certificat de salaire annuel (formulaire 11) généré par le module salaires',
        'description_de': 'Jährlicher Lohnausweis (Formular 11) vom Lohnmodul generiert',
        'description_it': 'Certificato di salario annuale (formulario 11) generato dal modulo stipendi',
        'description_en': 'Annual salary certificate (form 11) generated by the payroll module',
        'origine': 'INTERNE',
        'module_applicatif': 'salaires',
        'icone': 'award',
        'ordre': 120,
    },
    {
        'code': 'salaires_certificat_travail',
        'libelle_fr': 'Certificat de travail généré',
        'libelle_de': 'Generiertes Arbeitszeugnis',
        'libelle_it': 'Certificato di lavoro generato',
        'libelle_en': 'Generated work certificate',
        'description_fr': 'Certificat de travail généré par le module salaires',
        'description_de': 'Arbeitszeugnis vom Lohnmodul generiert',
        'description_it': 'Certificato di lavoro generato dal modulo stipendi',
        'description_en': 'Work certificate generated by the payroll module',
        'origine': 'INTERNE',
        'module_applicatif': 'salaires',
        'icone': 'file-badge',
        'ordre': 130,
    },
    {
        'code': 'salaires_declaration',
        'libelle_fr': 'Déclaration cotisations générée',
        'libelle_de': 'Generierte Beitragserklärung',
        'libelle_it': 'Dichiarazione contributi generata',
        'libelle_en': 'Generated contributions declaration',
        'description_fr': 'Déclaration de cotisations sociales générée par le module salaires',
        'description_de': 'Sozialversicherungsbeitragserklärung vom Lohnmodul generiert',
        'description_it': 'Dichiarazione dei contributi sociali generata dal modulo stipendi',
        'description_en': 'Social contributions declaration generated by the payroll module',
        'origine': 'INTERNE',
        'module_applicatif': 'salaires',
        'icone': 'file-check',
        'ordre': 140,
    },
    {
        'code': 'comptabilite_export',
        'libelle_fr': 'Export comptable',
        'libelle_de': 'Buchhaltungsexport',
        'libelle_it': 'Esportazione contabile',
        'libelle_en': 'Accounting export',
        'description_fr': 'Balance, bilan ou export (CSV/Excel/PDF) généré par le module comptabilité',
        'description_de': 'Bilanz oder Export (CSV/Excel/PDF) vom Buchhaltungsmodul generiert',
        'description_it': 'Bilancio o esportazione (CSV/Excel/PDF) generato dal modulo contabilità',
        'description_en': 'Balance sheet or export (CSV/Excel/PDF) generated by the accounting module',
        'origine': 'INTERNE',
        'module_applicatif': 'comptabilite',
        'icone': 'calculator',
        'ordre': 150,
    },
    {
        'code': 'comptabilite_piece',
        'libelle_fr': 'Pièce comptable justificative',
        'libelle_de': 'Buchungsbeleg',
        'libelle_it': 'Documento giustificativo contabile',
        'libelle_en': 'Accounting supporting document',
        'description_fr': 'Document justificatif rattaché à une écriture comptable',
        'description_de': 'Beleg zu einer Buchung',
        'description_it': 'Documento giustificativo allegato a una registrazione contabile',
        'description_en': 'Supporting document attached to an accounting entry',
        'origine': 'EXTERNE',
        'module_applicatif': 'comptabilite',
        'icone': 'receipt',
        'ordre': 155,
    },
    {
        'code': 'comptabilite_pain001',
        'libelle_fr': 'Fichier paiement SEPA (pain.001)',
        'libelle_de': 'SEPA-Zahlungsdatei (pain.001)',
        'libelle_it': 'File di pagamento SEPA (pain.001)',
        'libelle_en': 'SEPA payment file (pain.001)',
        'description_fr': 'Fichier XML pain.001 généré pour les virements SEPA',
        'description_de': 'XML-Datei pain.001 für SEPA-Überweisungen generiert',
        'description_it': 'File XML pain.001 generato per i bonifici SEPA',
        'description_en': 'XML pain.001 file generated for SEPA transfers',
        'origine': 'INTERNE',
        'module_applicatif': 'comptabilite',
        'icone': 'bank',
        'ordre': 160,
    },
    {
        'code': 'comptabilite_camt053',
        'libelle_fr': 'Relevé bancaire importé (camt.053)',
        'libelle_de': 'Importierter Kontoauszug (camt.053)',
        'libelle_it': 'Estratto conto importato (camt.053)',
        'libelle_en': 'Imported bank statement (camt.053)',
        'description_fr': 'Relevé bancaire au format camt.053 importé dans la comptabilité',
        'description_de': 'Kontoauszug im camt.053-Format in die Buchhaltung importiert',
        'description_it': 'Estratto conto in formato camt.053 importato nella contabilità',
        'description_en': 'Bank statement in camt.053 format imported into accounting',
        'origine': 'EXTERNE',
        'module_applicatif': 'comptabilite',
        'icone': 'building-bank',
        'ordre': 165,
    },
    {
        'code': 'tva_declaration',
        'libelle_fr': 'Déclaration TVA générée',
        'libelle_de': 'Generierte MWST-Erklärung',
        'libelle_it': 'Dichiarazione IVA generata',
        'libelle_en': 'Generated VAT declaration',
        'description_fr': 'Déclaration TVA (PDF ou XML AFC) générée par le module TVA',
        'description_de': 'MWST-Erklärung (PDF oder XML ESTV) vom MWST-Modul generiert',
        'description_it': 'Dichiarazione IVA (PDF o XML AFC) generata dal modulo IVA',
        'description_en': 'VAT declaration (PDF or XML FTA) generated by the VAT module',
        'origine': 'INTERNE',
        'module_applicatif': 'tva',
        'icone': 'file-percent',
        'ordre': 170,
    },
    {
        'code': 'fiscalite_declaration',
        'libelle_fr': 'Déclaration fiscale générée',
        'libelle_de': 'Generierte Steuererklärung',
        'libelle_it': 'Dichiarazione fiscale generata',
        'libelle_en': 'Generated tax declaration',
        'description_fr': 'Document fiscal généré par le module fiscalité',
        'description_de': 'Steuerdokument vom Steuermodul generiert',
        'description_it': 'Documento fiscale generato dal modulo fiscalità',
        'description_en': 'Tax document generated by the tax module',
        'origine': 'INTERNE',
        'module_applicatif': 'fiscalite',
        'icone': 'landmark',
        'ordre': 180,
    },
    {
        'code': 'analytics_rapport',
        'libelle_fr': 'Rapport analytique généré',
        'libelle_de': 'Generierter Analysebericht',
        'libelle_it': 'Rapporto analitico generato',
        'libelle_en': 'Generated analytics report',
        'description_fr': 'Rapport PDF avec graphiques généré par le module analytics (Celery)',
        'description_de': 'PDF-Bericht mit Diagrammen vom Analytics-Modul generiert (Celery)',
        'description_it': 'Rapporto PDF con grafici generato dal modulo analytics (Celery)',
        'description_en': 'PDF report with charts generated by the analytics module (Celery)',
        'origine': 'INTERNE',
        'module_applicatif': 'analytics',
        'icone': 'chart-bar',
        'ordre': 190,
    },
    {
        'code': 'analytics_export',
        'libelle_fr': 'Export de données analytiques',
        'libelle_de': 'Analytischer Datenexport',
        'libelle_it': 'Esportazione dati analitici',
        'libelle_en': 'Analytics data export',
        'description_fr': 'Export de données (CSV/Excel) généré par le module analytics',
        'description_de': 'Datenexport (CSV/Excel) vom Analytics-Modul generiert',
        'description_it': 'Esportazione dati (CSV/Excel) generata dal modulo analytics',
        'description_en': 'Data export (CSV/Excel) generated by the analytics module',
        'origine': 'INTERNE',
        'module_applicatif': 'analytics',
        'icone': 'download',
        'ordre': 195,
    },
    {
        'code': 'editeur_export',
        'libelle_fr': 'Export éditeur collaboratif',
        'libelle_de': 'Export kollaborativer Editor',
        'libelle_it': 'Esportazione editor collaborativo',
        'libelle_en': 'Collaborative editor export',
        'description_fr': 'Document exporté depuis l\'éditeur collaboratif (La Suite Docs) vers la GED',
        'description_de': 'Dokument vom kollaborativen Editor (La Suite Docs) in die GED exportiert',
        'description_it': 'Documento esportato dall\'editor collaborativo (La Suite Docs) nella GED',
        'description_en': 'Document exported from the collaborative editor (La Suite Docs) to the DMS',
        'origine': 'INTERNE',
        'module_applicatif': 'editeur',
        'icone': 'edit',
        'ordre': 200,
    },
    {
        'code': 'mailing_piece_jointe',
        'libelle_fr': 'Pièce jointe e-mail sortant',
        'libelle_de': 'Anhang ausgehende E-Mail',
        'libelle_it': 'Allegato e-mail in uscita',
        'libelle_en': 'Outgoing email attachment',
        'description_fr': 'Pièce jointe archivée depuis un e-mail envoyé via le module mailing',
        'description_de': 'Archivierter Anhang einer über das Mailing-Modul gesendeten E-Mail',
        'description_it': 'Allegato archiviato da un\'e-mail inviata tramite il modulo mailing',
        'description_en': 'Attachment archived from an email sent via the mailing module',
        'origine': 'INTERNE',
        'module_applicatif': 'mailing',
        'icone': 'send',
        'ordre': 210,
    },
    {
        'code': 'core_export',
        'libelle_fr': 'Export générique système',
        'libelle_de': 'Generischer Systemexport',
        'libelle_it': 'Esportazione generica di sistema',
        'libelle_en': 'Generic system export',
        'description_fr': 'Document généré par le service d\'export centralisé (PDF/CSV/Excel/QR-facture)',
        'description_de': 'Dokument vom zentralisierten Exportdienst generiert (PDF/CSV/Excel/QR-Rechnung)',
        'description_it': 'Documento generato dal servizio di esportazione centralizzato (PDF/CSV/Excel/QR-fattura)',
        'description_en': 'Document generated by the centralized export service (PDF/CSV/Excel/QR-bill)',
        'origine': 'INTERNE',
        'module_applicatif': 'core',
        'icone': 'file-export',
        'ordre': 220,
    },
    {
        'code': 'systeme',
        'libelle_fr': 'Génération système',
        'libelle_de': 'Systemgenerierung',
        'libelle_it': 'Generazione di sistema',
        'libelle_en': 'System generation',
        'description_fr': 'Document créé automatiquement par le système (migration, traitement batch, etc.)',
        'description_de': 'Dokument automatisch vom System erstellt (Migration, Batch-Verarbeitung, etc.)',
        'description_it': 'Documento creato automaticamente dal sistema (migrazione, elaborazione batch, ecc.)',
        'description_en': 'Document automatically created by the system (migration, batch processing, etc.)',
        'origine': 'INTERNE',
        'module_applicatif': '',
        'icone': 'server',
        'ordre': 900,
    },
]


def populate_sources(apps, schema_editor):
    SourceDocument = apps.get_model('documents', 'SourceDocument')
    for source_data in SOURCES_PREDEFINIES:
        SourceDocument.objects.get_or_create(
            code=source_data['code'],
            defaults=source_data,
        )


def depopulate_sources(apps, schema_editor):
    SourceDocument = apps.get_model('documents', 'SourceDocument')
    codes = [s['code'] for s in SOURCES_PREDEFINIES]
    SourceDocument.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_sourcedocument_document_source'),
    ]

    operations = [
        migrations.RunPython(populate_sources, depopulate_sources),
    ]
