# Generated by Django 6.0 on 2025-12-17 22:27

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentembedding_textchunkembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='embedding', serialize=False, to='documents.document')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('model_used', models.CharField(choices=[('openai-small', 'OpenAI text-embedding-3-small (1536d)'), ('openai-large', 'OpenAI text-embedding-3-large (3072d)'), ('multilingual-mini', 'Multilingual MiniLM (384d)'), ('multilingual-mpnet', 'Multilingual MPNet (768d)')], default='openai-small', max_length=50)),
                ('dimensions', models.IntegerField(default=1536)),
                ('text_hash', models.CharField(help_text='Hash SHA-256 du texte utilisé', max_length=64)),
                ('text_length', models.IntegerField(help_text='Longueur du texte en caractères')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Embedding de document',
                'db_table': 'document_embeddings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TextChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('chunk_start', models.IntegerField(help_text='Position de début dans le texte')),
                ('chunk_end', models.IntegerField(help_text='Position de fin dans le texte')),
                ('chunk_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('model_used', models.CharField(default='openai-small', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Embedding de chunk',
                'db_table': 'text_chunk_embeddings',
                'managed': False,
            },
        ),
    ]
