# Generated by Django 6.0.3 on 2026-03-12 01:20

import core.storage
import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_populate_sources_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_parent',
        ),
        migrations.RemoveField(
            model_name='document',
            name='version',
        ),
        migrations.RemoveField(
            model_name='versiondocument',
            name='path_storage',
        ),
        migrations.AddField(
            model_name='versiondocument',
            name='fichier',
            field=models.FileField(blank=True, help_text='Copie du fichier dans MinIO/S3 pour cette version', null=True, storage=core.storage.S3DocumentStorage(), upload_to=documents.models.version_upload_path, verbose_name='Fichier de cette version'),
        ),
        migrations.AlterField(
            model_name='document',
            name='dossier',
            field=models.ForeignKey(blank=True, help_text='Dossier de classement. SET_NULL si le dossier est supprimé (le document reste).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.dossier', verbose_name='Dossier'),
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(blank=True, help_text='Fichier stocké dans S3/MinIO', null=True, storage=core.storage.S3DocumentStorage(), upload_to=documents.models.document_upload_path, verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='document',
            name='hash_fichier',
            field=models.CharField(db_index=True, help_text='Empreinte SHA-256 pour déduplication (non unique : un même fichier peut être dans plusieurs mandats)', max_length=64, verbose_name='Hash du fichier'),
        ),
        migrations.AlterField(
            model_name='sourcedocument',
            name='module_applicatif',
            field=models.CharField(blank=True, help_text='Nom du module Django associé (ex: facturation, salaires)', max_length=50, verbose_name='Module applicatif'),
        ),
        migrations.AlterField(
            model_name='versiondocument',
            name='modifie_par',
            field=models.ForeignKey(help_text='Utilisateur ayant créé cette version', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
    ]
