# Generated by Django 6.0 on 2026-01-06 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_conversation_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_utilisa_adc1dd_idx',
            old_name='conv_user_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_mandat__d70888_idx',
            old_name='conv_mandat_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messages_convers_3ebb41_idx',
            old_name='msg_conv_created_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messages_role_8be1df_idx',
            old_name='msg_role_idx',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
    ]
