# Generated by merge script
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_categoriedocument_langue_saisie_and_more"),
        ("documents", "0010_alter_categoriedocument_langue_saisie_and_more"),
    ]

    operations = [
    ]
