# Generated by Django 6.0.2 on 2026-02-11 16:24

import core.storage
import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0014_alter_classecomptable_description_and_more'),
        ('core', '0017_remove_collaborateurfiduciaire_unique_collaborateur_mandat_and_more'),
        ('documents', '0010_intelligence_models'),
        ('facturation', '0004_alter_facture_created_at_alter_facture_created_by_and_more'),
        ('salaires', '0008_declaration_cotisations_enhanced'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriedocument',
            options={'ordering': ['ordre', 'nom'], 'verbose_name': 'Catégorie de document', 'verbose_name_plural': 'Catégories de document'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-date_upload'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='documentembedding',
            options={'managed': False, 'verbose_name': 'Embedding de document', 'verbose_name_plural': 'Embeddings de document'},
        ),
        migrations.AlterModelOptions(
            name='dossier',
            options={'ordering': ['chemin_complet'], 'verbose_name': 'Dossier', 'verbose_name_plural': 'Dossiers'},
        ),
        migrations.AlterModelOptions(
            name='recherchedocument',
            options={'ordering': ['-date_recherche'], 'verbose_name': 'Recherche de document', 'verbose_name_plural': 'Recherches de document'},
        ),
        migrations.AlterModelOptions(
            name='textchunkembedding',
            options={'managed': False, 'verbose_name': 'Embedding de chunk', 'verbose_name_plural': 'Embeddings de chunk'},
        ),
        migrations.AlterModelOptions(
            name='traitementdocument',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Traitement de document', 'verbose_name_plural': 'Traitements de document'},
        ),
        migrations.AlterModelOptions(
            name='typedocument',
            options={'ordering': ['libelle'], 'verbose_name': 'Type de document', 'verbose_name_plural': 'Types de document'},
        ),
        migrations.AlterModelOptions(
            name='versiondocument',
            options={'ordering': ['-numero_version'], 'verbose_name': 'Version de document', 'verbose_name_plural': 'Versions de document'},
        ),
        migrations.RenameIndex(
            model_name='documentrelation',
            new_name='document_re_documen_02c188_idx',
            old_name='document_re_documen_42b6c9_idx',
        ),
        migrations.RenameIndex(
            model_name='documentrelation',
            new_name='document_re_score_s_6e5788_idx',
            old_name='document_re_score_s_a3f1e2_idx',
        ),
        # RemoveField path_storage + AddField fichier already applied in DB
        # (via migration 0009 stub that was applied directly)
        migrations.AlterField(
            model_name='categoriedocument',
            name='couleur',
            field=models.CharField(blank=True, help_text='Code couleur hexadécimal (ex: #FF5733)', max_length=7, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='categoriedocument',
            name='description',
            field=models.TextField(blank=True, help_text='Description de la catégorie', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='categoriedocument',
            name='description_de',
            field=models.TextField(blank=True, help_text='Description de la catégorie', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='categoriedocument',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description de la catégorie', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='categoriedocument',
            name='description_fr',
            field=models.TextField(blank=True, help_text='Description de la catégorie', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='categoriedocument',
            name='description_it',
            field=models.TextField(blank=True, help_text='Description de la catégorie', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='categoriedocument',
            name='icone',
            field=models.CharField(blank=True, help_text="Nom de l'icône (ex: folder, file-text)", max_length=50, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='categoriedocument',
            name='mots_cles',
            field=models.JSONField(blank=True, default=list, help_text='Mots-clés pour classification automatique', verbose_name='Mots-clés'),
        ),
        migrations.AlterField(
            model_name='categoriedocument',
            name='nom',
            field=models.CharField(help_text='Nom de la catégorie', max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='categoriedocument',
            name='nom_de',
            field=models.CharField(help_text='Nom de la catégorie', max_length=100, null=True, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='categoriedocument',
            name='nom_en',
            field=models.CharField(help_text='Nom de la catégorie', max_length=100, null=True, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='categoriedocument',
            name='nom_fr',
            field=models.CharField(help_text='Nom de la catégorie', max_length=100, null=True, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='categoriedocument',
            name='nom_it',
            field=models.CharField(help_text='Nom de la catégorie', max_length=100, null=True, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='categoriedocument',
            name='ordre',
            field=models.IntegerField(default=0, help_text="Position d'affichage dans la liste", verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='categoriedocument',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Catégorie de niveau supérieur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='documents.categoriedocument', verbose_name='Catégorie parente'),
        ),
        migrations.AlterField(
            model_name='categoriedocument',
            name='patterns_regex',
            field=models.JSONField(blank=True, default=list, help_text='Expressions régulières pour détection automatique', verbose_name='Patterns regex'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='contexte_systeme',
            field=models.TextField(blank=True, help_text="Instructions personnalisées pour l'assistant", verbose_name='Contexte système'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='description',
            field=models.TextField(blank=True, help_text='Description de la conversation', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Document spécifique comme contexte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='documents.document', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='mandat',
            field=models.ForeignKey(blank=True, help_text='Mandat pour le contexte documentaire', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='modele_ia',
            field=models.CharField(default='altiusone-chat', help_text="Modèle d'intelligence artificielle utilisé", max_length=50, verbose_name='Modèle IA'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='nombre_messages',
            field=models.IntegerField(default=0, help_text='Total des messages échangés', verbose_name='Nombre de messages'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='statut',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVEE', 'Archivee'), ('SUPPRIMEE', 'Supprimee')], db_index=True, default='ACTIVE', help_text='État de la conversation', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0.7, help_text='Créativité des réponses (0=déterministe, 1=créatif)', max_digits=3, verbose_name='Température'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='titre',
            field=models.CharField(blank=True, help_text='Titre de la conversation', max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='tokens_utilises',
            field=models.IntegerField(default=0, help_text='Consommation totale de tokens', verbose_name='Tokens utilisés'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='utilisateur',
            field=models.ForeignKey(help_text='Utilisateur propriétaire de la conversation', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='document',
            name='categorie',
            field=models.ForeignKey(blank=True, help_text='Catégorie de classement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.categoriedocument', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='document',
            name='commentaire_validation',
            field=models.TextField(blank=True, help_text='Remarques du validateur', verbose_name='Commentaire de validation'),
        ),
        migrations.AlterField(
            model_name='document',
            name='confidentiel',
            field=models.BooleanField(default=False, help_text='Marquer comme document confidentiel', verbose_name='Confidentiel'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_document',
            field=models.DateField(blank=True, db_index=True, help_text='Date figurant sur le document', null=True, verbose_name='Date du document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, help_text='Dernière modification', verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_upload',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date et heure de téléchargement', verbose_name="Date d'upload"),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_validation',
            field=models.DateTimeField(blank=True, help_text='Date et heure de validation', null=True, verbose_name='Date de validation'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, help_text='Description du document', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description_de',
            field=models.TextField(blank=True, help_text='Description du document', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description du document', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description_fr',
            field=models.TextField(blank=True, help_text='Description du document', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description_it',
            field=models.TextField(blank=True, help_text='Description du document', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_parent',
            field=models.ForeignKey(blank=True, help_text='Version précédente du document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='documents.document', verbose_name='Document parent'),
        ),
        migrations.AlterField(
            model_name='document',
            name='dossier',
            field=models.ForeignKey(blank=True, help_text='Dossier de classement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.dossier', verbose_name='Dossier'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ecriture_comptable',
            field=models.ForeignKey(blank=True, help_text='Écriture comptable associée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='comptabilite.ecriturecomptable', verbose_name='Écriture comptable'),
        ),
        migrations.AlterField(
            model_name='document',
            name='extension',
            field=models.CharField(help_text='Extension du fichier (pdf, jpg, etc.)', max_length=10, verbose_name='Extension'),
        ),
        migrations.AlterField(
            model_name='document',
            name='facture',
            field=models.ForeignKey(blank=True, help_text='Facture associée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='facturation.facture', verbose_name='Facture'),
        ),
        migrations.AlterField(
            model_name='document',
            name='fiche_salaire',
            field=models.ForeignKey(blank=True, help_text='Fiche de salaire associée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='salaires.fichesalaire', verbose_name='Fiche de salaire'),
        ),
        migrations.AlterField(
            model_name='document',
            name='hash_fichier',
            field=models.CharField(db_index=True, help_text='Empreinte SHA-256 pour déduplication', max_length=64, unique=True, verbose_name='Hash du fichier'),
        ),
        migrations.AlterField(
            model_name='document',
            name='mandat',
            field=models.ForeignKey(help_text='Mandat auquel appartient ce document', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AlterField(
            model_name='document',
            name='metadata_extraite',
            field=models.JSONField(blank=True, default=dict, help_text='Données extraites automatiquement (montants, dates, etc.)', verbose_name='Métadonnées extraites'),
        ),
        migrations.AlterField(
            model_name='document',
            name='mime_type',
            field=models.CharField(help_text='Type MIME du fichier', max_length=100, verbose_name='Type MIME'),
        ),
        migrations.AlterField(
            model_name='document',
            name='nom_fichier',
            field=models.CharField(db_index=True, help_text='Nom du fichier stocké', max_length=255, verbose_name='Nom du fichier'),
        ),
        migrations.AlterField(
            model_name='document',
            name='nom_original',
            field=models.CharField(help_text="Nom du fichier lors de l'upload", max_length=255, verbose_name='Nom original'),
        ),
        migrations.AlterField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes et remarques internes', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='document',
            name='notes_de',
            field=models.TextField(blank=True, help_text='Notes et remarques internes', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='document',
            name='notes_en',
            field=models.TextField(blank=True, help_text='Notes et remarques internes', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='document',
            name='notes_fr',
            field=models.TextField(blank=True, help_text='Notes et remarques internes', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='document',
            name='notes_it',
            field=models.TextField(blank=True, help_text='Notes et remarques internes', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ocr_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Score de confiance de l'OCR (0-100)", max_digits=5, null=True, verbose_name='Confiance OCR'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ocr_text',
            field=models.TextField(blank=True, help_text='Texte extrait par reconnaissance optique', verbose_name='Texte OCR'),
        ),
        migrations.AlterField(
            model_name='document',
            name='prediction_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Score de confiance de la prédiction (0-100)', max_digits=5, null=True, verbose_name='Confiance prédiction'),
        ),
        migrations.AlterField(
            model_name='document',
            name='prediction_type',
            field=models.CharField(blank=True, help_text="Type de document prédit par l'IA", max_length=100, verbose_name='Type prédit'),
        ),
        migrations.AlterField(
            model_name='document',
            name='statut_traitement',
            field=models.CharField(choices=[('UPLOAD', 'Uploadé'), ('OCR_EN_COURS', 'OCR en cours'), ('OCR_TERMINE', 'OCR terminé'), ('CLASSIFICATION_EN_COURS', 'Classification en cours'), ('CLASSIFICATION_TERMINEE', 'Classification terminée'), ('EXTRACTION_EN_COURS', 'Extraction données en cours'), ('EXTRACTION_TERMINEE', 'Extraction terminée'), ('VALIDE', 'Validé'), ('ERREUR', 'Erreur traitement')], db_index=True, default='UPLOAD', help_text='État du traitement automatique', max_length=30, verbose_name='Statut de traitement'),
        ),
        migrations.AlterField(
            model_name='document',
            name='statut_validation',
            field=models.CharField(blank=True, choices=[('EN_ATTENTE', 'En attente validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', help_text='État de la validation manuelle', max_length=20, null=True, verbose_name='Statut de validation'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Étiquettes manuelles', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tags_auto',
            field=models.JSONField(blank=True, default=list, help_text='Étiquettes générées automatiquement', verbose_name='Tags automatiques'),
        ),
        migrations.AlterField(
            model_name='document',
            name='taille',
            field=models.BigIntegerField(help_text='Taille du fichier en octets', verbose_name='Taille'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.ForeignKey(blank=True, help_text='Type de document identifié', null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.typedocument', verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='valide_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant validé le document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AlterField(
            model_name='document',
            name='version',
            field=models.IntegerField(default=1, help_text='Numéro de version du document', verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='documentrelation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='documentrelation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='documentrelation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='documentrelation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='acces_restreint',
            field=models.BooleanField(default=False, help_text="Limiter l'accès aux utilisateurs autorisés", verbose_name='Accès restreint'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='chemin_complet',
            field=models.CharField(db_index=True, help_text="Chemin d'accès complet dans l'arborescence", max_length=1000, verbose_name='Chemin complet'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client propriétaire du dossier', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='core.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='description',
            field=models.TextField(blank=True, help_text='Description du contenu du dossier', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='mandat',
            field=models.ForeignKey(blank=True, help_text='Mandat associé au dossier', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='niveau',
            field=models.IntegerField(default=0, help_text="Profondeur dans l'arborescence", verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='nom',
            field=models.CharField(help_text='Nom du dossier', max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='nombre_documents',
            field=models.IntegerField(default=0, help_text='Nombre de documents dans ce dossier', verbose_name='Nombre de documents'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Dossier contenant celui-ci', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_dossiers', to='documents.dossier', verbose_name='Dossier parent'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='proprietaire',
            field=models.ForeignKey(help_text='Utilisateur propriétaire du dossier', on_delete=django.db.models.deletion.PROTECT, related_name='dossiers_proprietaire', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Étiquettes pour faciliter la recherche', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='taille_totale',
            field=models.BigIntegerField(default=0, help_text='Taille totale des documents en octets', verbose_name='Taille totale'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='type_dossier',
            field=models.CharField(choices=[('RACINE', 'Racine'), ('CLIENT', 'Dossier client'), ('MANDAT', 'Dossier mandat'), ('EXERCICE', 'Exercice comptable'), ('STANDARD', 'Dossier standard'), ('ARCHIVE', 'Archive')], help_text='Catégorie du dossier', max_length=20, verbose_name='Type de dossier'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='utilisateurs_autorises',
            field=models.ManyToManyField(blank=True, help_text='Utilisateurs ayant accès si accès restreint', related_name='dossiers_autorises', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs autorisés'),
        ),
        migrations.AlterField(
            model_name='mandatdigest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='mandatdigest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='mandatdigest',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='mandatdigest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='mandatinsight',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='mandatinsight',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='mandatinsight',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='mandatinsight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='message',
            name='commentaire_feedback',
            field=models.TextField(blank=True, help_text='Explication du feedback', verbose_name='Commentaire feedback'),
        ),
        migrations.AlterField(
            model_name='message',
            name='contenu',
            field=models.TextField(help_text='Texte du message', verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(help_text='Conversation contenant ce message', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='documents.conversation', verbose_name='Conversation'),
        ),
        migrations.AlterField(
            model_name='message',
            name='documents_contexte',
            field=models.ManyToManyField(blank=True, help_text='Documents utilisés comme contexte pour ce message', related_name='messages_contexte', to='documents.document', verbose_name='Documents contexte'),
        ),
        migrations.AlterField(
            model_name='message',
            name='duree_ms',
            field=models.IntegerField(blank=True, help_text='Durée de génération en millisecondes', null=True, verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='message',
            name='feedback',
            field=models.CharField(blank=True, choices=[('POSITIF', 'Positif'), ('NEGATIF', 'Négatif')], help_text="Évaluation de la réponse par l'utilisateur", max_length=20, null=True, verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('USER', 'Utilisateur'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'Systeme')], db_index=True, help_text='Auteur du message (utilisateur, assistant ou système)', max_length=20, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sources',
            field=models.JSONField(blank=True, default=list, help_text="Sources citées par l'assistant", verbose_name='Sources'),
        ),
        migrations.AlterField(
            model_name='message',
            name='tokens_completion',
            field=models.IntegerField(default=0, help_text='Nombre de tokens générés en réponse', verbose_name='Tokens réponse'),
        ),
        migrations.AlterField(
            model_name='message',
            name='tokens_prompt',
            field=models.IntegerField(default=0, help_text='Nombre de tokens utilisés pour le prompt', verbose_name='Tokens prompt'),
        ),
        migrations.AlterField(
            model_name='recherchedocument',
            name='date_recherche',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date et heure de la recherche', verbose_name='Date de recherche'),
        ),
        migrations.AlterField(
            model_name='recherchedocument',
            name='documents_selectionnes',
            field=models.ManyToManyField(blank=True, help_text='Documents consultés parmi les résultats', to='documents.document', verbose_name='Documents sélectionnés'),
        ),
        migrations.AlterField(
            model_name='recherchedocument',
            name='duree_ms',
            field=models.IntegerField(help_text='Durée de la recherche en millisecondes', verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='recherchedocument',
            name='filtres',
            field=models.JSONField(blank=True, default=dict, help_text='Filtres appliqués à la recherche', verbose_name='Filtres'),
        ),
        migrations.AlterField(
            model_name='recherchedocument',
            name='mandat',
            field=models.ForeignKey(blank=True, help_text='Mandat dans lequel la recherche a été effectuée', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AlterField(
            model_name='recherchedocument',
            name='nombre_resultats',
            field=models.IntegerField(help_text='Nombre de documents trouvés', verbose_name='Nombre de résultats'),
        ),
        migrations.AlterField(
            model_name='recherchedocument',
            name='requete',
            field=models.TextField(help_text='Texte de la recherche', verbose_name='Requête'),
        ),
        migrations.AlterField(
            model_name='recherchedocument',
            name='utilisateur',
            field=models.ForeignKey(help_text='Utilisateur ayant effectué la recherche', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='traitementdocument',
            name='date_debut',
            field=models.DateTimeField(auto_now_add=True, help_text='Début du traitement', verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='traitementdocument',
            name='date_fin',
            field=models.DateTimeField(blank=True, help_text='Fin du traitement', null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='traitementdocument',
            name='document',
            field=models.ForeignKey(help_text='Document traité', on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='documents.document', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='traitementdocument',
            name='duree_secondes',
            field=models.IntegerField(blank=True, help_text='Durée du traitement en secondes', null=True, verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='traitementdocument',
            name='erreur',
            field=models.TextField(blank=True, help_text="Message d'erreur en cas d'échec", verbose_name='Erreur'),
        ),
        migrations.AlterField(
            model_name='traitementdocument',
            name='moteur',
            field=models.CharField(blank=True, help_text='Outil utilisé (Tesseract, OpenAI GPT-4, etc.)', max_length=100, verbose_name='Moteur'),
        ),
        migrations.AlterField(
            model_name='traitementdocument',
            name='resultat',
            field=models.JSONField(blank=True, default=dict, help_text='Données résultant du traitement', verbose_name='Résultat'),
        ),
        migrations.AlterField(
            model_name='traitementdocument',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ERREUR', 'Erreur')], help_text='État du traitement', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='traitementdocument',
            name='type_traitement',
            field=models.CharField(choices=[('OCR', 'OCR / Extraction texte'), ('CLASSIFICATION', 'Classification automatique'), ('EXTRACTION', 'Extraction métadonnées'), ('COMPRESSION', 'Compression'), ('CONVERSION', 'Conversion format'), ('WATERMARK', 'Ajout watermark')], help_text='Nature du traitement effectué', max_length=20, verbose_name='Type de traitement'),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='categorie',
            field=models.ForeignKey(help_text='Catégorie à laquelle appartient ce type', on_delete=django.db.models.deletion.PROTECT, related_name='types_document', to='documents.categoriedocument', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='champs_extraire',
            field=models.JSONField(blank=True, default=list, help_text='Liste des champs à extraire automatiquement (montant, date, etc.)', verbose_name='Champs à extraire'),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='code',
            field=models.CharField(help_text='Code unique du type de document', max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='libelle',
            field=models.CharField(help_text='Nom affiché du type de document', max_length=100, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='libelle_de',
            field=models.CharField(help_text='Nom affiché du type de document', max_length=100, null=True, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='libelle_en',
            field=models.CharField(help_text='Nom affiché du type de document', max_length=100, null=True, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='libelle_fr',
            field=models.CharField(help_text='Nom affiché du type de document', max_length=100, null=True, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='libelle_it',
            field=models.CharField(help_text='Nom affiché du type de document', max_length=100, null=True, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='template_extraction',
            field=models.JSONField(blank=True, default=dict, help_text="Configuration du template pour l'extraction AI/OCR", verbose_name="Template d'extraction"),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='type_document',
            field=models.CharField(choices=[('FACTURE_VENTE', 'Facture de vente'), ('FACTURE_ACHAT', "Facture d'achat"), ('DEVIS', 'Devis'), ('BON_COMMANDE', 'Bon de commande'), ('BON_LIVRAISON', 'Bon de livraison'), ('RELEVE_BANQUE', 'Relevé bancaire'), ('JUSTIFICATIF', 'Justificatif'), ('CONTRAT', 'Contrat'), ('STATUTS', 'Statuts'), ('PV_ASSEMBLEE', 'PV Assemblée'), ('DECLARATION_TVA', 'Déclaration TVA'), ('FICHE_SALAIRE', 'Fiche de salaire'), ('CERTIFICAT_SALAIRE', 'Certificat de salaire'), ('ATTESTATION', 'Attestation'), ('COURRIER', 'Courrier'), ('EMAIL', 'Email'), ('AUTRE', 'Autre')], help_text='Catégorie prédéfinie du document', max_length=50, verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='validateurs',
            field=models.ManyToManyField(blank=True, help_text='Utilisateurs habilités à valider ce type de document', related_name='types_doc_validation', to=settings.AUTH_USER_MODEL, verbose_name='Validateurs'),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='validation_requise',
            field=models.BooleanField(default=False, help_text='Exiger une validation manuelle pour ce type', verbose_name='Validation requise'),
        ),
        migrations.AlterField(
            model_name='versiondocument',
            name='commentaire',
            field=models.TextField(blank=True, help_text='Description des modifications', verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='versiondocument',
            name='date_modification',
            field=models.DateTimeField(auto_now_add=True, help_text='Date de création de cette version', verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='versiondocument',
            name='document',
            field=models.ForeignKey(help_text='Document concerné', on_delete=django.db.models.deletion.CASCADE, related_name='historique_versions', to='documents.document', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='versiondocument',
            name='hash_fichier',
            field=models.CharField(help_text='Empreinte SHA-256 de cette version', max_length=64, verbose_name='Hash du fichier'),
        ),
        migrations.AlterField(
            model_name='versiondocument',
            name='modifie_par',
            field=models.ForeignKey(help_text='Utilisateur ayant créé cette version', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AlterField(
            model_name='versiondocument',
            name='numero_version',
            field=models.IntegerField(help_text='Numéro séquentiel de la version', verbose_name='Numéro de version'),
        ),
        migrations.AlterField(
            model_name='versiondocument',
            name='path_storage',
            field=models.CharField(help_text='Emplacement du fichier dans le stockage', max_length=500, verbose_name='Chemin de stockage'),
        ),
        migrations.AlterField(
            model_name='versiondocument',
            name='taille',
            field=models.BigIntegerField(help_text='Taille du fichier en octets', verbose_name='Taille'),
        ),
    ]
