# Generated by Django 6.0.3 on 2026-04-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_categoriedocument_langue_saisie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='commentaire_validation_de',
            field=models.TextField(blank=True, help_text='Remarques du validateur', null=True, verbose_name='Commentaire de validation'),
        ),
        migrations.AddField(
            model_name='document',
            name='commentaire_validation_en',
            field=models.TextField(blank=True, help_text='Remarques du validateur', null=True, verbose_name='Commentaire de validation'),
        ),
        migrations.AddField(
            model_name='document',
            name='commentaire_validation_fr',
            field=models.TextField(blank=True, help_text='Remarques du validateur', null=True, verbose_name='Commentaire de validation'),
        ),
        migrations.AddField(
            model_name='document',
            name='commentaire_validation_it',
            field=models.TextField(blank=True, help_text='Remarques du validateur', null=True, verbose_name='Commentaire de validation'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='description_de',
            field=models.TextField(blank=True, help_text='Description du contenu du dossier', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description du contenu du dossier', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='description_fr',
            field=models.TextField(blank=True, help_text='Description du contenu du dossier', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='description_it',
            field=models.TextField(blank=True, help_text='Description du contenu du dossier', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='nom_de',
            field=models.CharField(help_text='Nom du dossier', max_length=255, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='nom_en',
            field=models.CharField(help_text='Nom du dossier', max_length=255, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='nom_fr',
            field=models.CharField(help_text='Nom du dossier', max_length=255, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='nom_it',
            field=models.CharField(help_text='Nom du dossier', max_length=255, null=True, verbose_name='Nom'),
        ),
    ]
