# Generated by Django 5.2.8 on 2025-11-13 00:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('numero_piece', models.CharField(db_index=True, max_length=50)),
                ('numero_ligne', models.IntegerField(default=1)),
                ('date_ecriture', models.DateField(db_index=True)),
                ('date_valeur', models.DateField(blank=True, null=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('compte_auxiliaire', models.CharField(blank=True, max_length=50)),
                ('libelle', models.TextField()),
                ('libelle_complement', models.CharField(blank=True, max_length=255)),
                ('montant_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('devise', models.CharField(default='CHF', max_length=3)),
                ('taux_change', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('code_tva', models.CharField(blank=True, max_length=10)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('code_lettrage', models.CharField(blank=True, db_index=True, max_length=20)),
                ('date_lettrage', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validée'), ('LETTRE', 'Lettrée'), ('CLOTURE', 'Clôturée'), ('EXTOURNE', 'Extournée')], db_index=True, default='BROUILLON', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'db_table': 'ecritures_comptables',
                'ordering': ['date_ecriture', 'numero_piece', 'numero_ligne'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('libelle', models.CharField(max_length=100)),
                ('type_journal', models.CharField(choices=[('VTE', 'Ventes'), ('ACH', 'Achats'), ('BNQ', 'Banque'), ('CAS', 'Caisse'), ('OD', 'Opérations diverses'), ('ANO', 'A-nouveaux'), ('EXT', 'Extourne')], max_length=10)),
                ('numerotation_auto', models.BooleanField(default=True)),
                ('prefixe_piece', models.CharField(blank=True, max_length=10)),
                ('dernier_numero', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Journal',
                'db_table': 'journaux',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Lettrage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code_lettrage', models.CharField(max_length=20, unique=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_lettrage', models.DateField()),
                ('complet', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Lettrage',
                'db_table': 'lettrages',
            },
        ),
        migrations.CreateModel(
            name='PieceComptable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('numero_piece', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date_piece', models.DateField(db_index=True)),
                ('libelle', models.TextField()),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('equilibree', models.BooleanField(db_index=True, default=True)),
                ('statut', models.CharField(default='BROUILLON', max_length=20)),
            ],
            options={
                'verbose_name': 'Pièce comptable',
                'db_table': 'pieces_comptables',
                'ordering': ['-date_piece', 'numero_piece'],
            },
        ),
        migrations.CreateModel(
            name='PlanComptable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('nom', models.CharField(max_length=100)),
                ('type_plan', models.CharField(choices=[('PME', 'Plan comptable PME'), ('GENERAL', 'Plan comptable général'), ('ENTREPRISE', 'Plan comptable entreprise'), ('PERSONNALISE', 'Personnalisé')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_template', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Plan comptable',
                'db_table': 'plans_comptables',
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('numero', models.CharField(db_index=True, max_length=20)),
                ('libelle', models.CharField(max_length=255)),
                ('libelle_court', models.CharField(blank=True, max_length=100)),
                ('type_compte', models.CharField(choices=[('ACTIF', 'Actif'), ('PASSIF', 'Passif'), ('CHARGE', 'Charge'), ('PRODUIT', 'Produit')], max_length=10)),
                ('classe', models.IntegerField(choices=[(1, 'Classe 1 - Actifs circulants'), (2, 'Classe 2 - Actifs immobilisés'), (3, 'Classe 3 - Capitaux de tiers à court terme'), (4, 'Classe 4 - Capitaux de tiers à long terme'), (5, 'Classe 5 - Capitaux propres'), (6, 'Classe 6 - Charges'), (7, 'Classe 7 - Produits'), (8, 'Classe 8 - Résultats'), (9, 'Classe 9 - Comptes de bouclements')])),
                ('niveau', models.IntegerField(default=1, help_text='Niveau hiérarchique')),
                ('est_collectif', models.BooleanField(default=False, help_text='Compte collectif (total)')),
                ('imputable', models.BooleanField(default=True, help_text='Peut recevoir des écritures')),
                ('lettrable', models.BooleanField(default=False, help_text='Lettrage possible')),
                ('obligatoire_tiers', models.BooleanField(default=False)),
                ('soumis_tva', models.BooleanField(default=False)),
                ('code_tva_defaut', models.CharField(blank=True, help_text='Code TVA par défaut (200, 205, etc.)', max_length=10)),
                ('solde_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('solde_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('compte_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_comptes', to='comptabilite.compte')),
            ],
            options={
                'verbose_name': 'Compte',
                'db_table': 'comptes',
                'ordering': ['numero'],
            },
        ),
    ]
