# Generated by Django 6.0.2 on 2026-02-15 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0001_initial'),
        ('core', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classecomptable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='compte',
            name='classe_comptable',
            field=models.ForeignKey(blank=True, help_text='Classe comptable de référence (1=Actifs, 2=Passifs, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes', to='comptabilite.classecomptable', verbose_name='Classe comptable'),
        ),
        migrations.AddField(
            model_name='compte',
            name='compte_parent',
            field=models.ForeignKey(blank=True, help_text='Compte de niveau supérieur pour la hiérarchie', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_comptes', to='comptabilite.compte', verbose_name='Compte parent'),
        ),
        migrations.AddField(
            model_name='compte',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='compte',
            field=models.ForeignKey(help_text='Compte comptable mouvementé', on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='comptabilite.compte', verbose_name='Compte'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='ecriture_extournee',
            field=models.ForeignKey(blank=True, help_text="Écriture d'origine si celle-ci est une extourne", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extournes', to='comptabilite.ecriturecomptable', verbose_name='Écriture extournée'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='exercice',
            field=models.ForeignKey(help_text="Exercice comptable de l'écriture", on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='core.exercicecomptable', verbose_name='Exercice comptable'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='mandat',
            field=models.ForeignKey(help_text='Mandat concerné par cette écriture', on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='piece_justificative',
            field=models.ForeignKey(blank=True, help_text="Document justificatif associé à l'écriture", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures', to='documents.document', verbose_name='Pièce justificative'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='valide_par',
            field=models.ForeignKey(help_text="Utilisateur ayant validé l'écriture", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='journal',
            name='compte_contrepartie_defaut',
            field=models.ForeignKey(blank=True, help_text='Compte utilisé par défaut pour la contrepartie des écritures', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comptabilite.compte', verbose_name='Compte de contrepartie par défaut'),
        ),
        migrations.AddField(
            model_name='journal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='journal',
            name='mandat',
            field=models.ForeignKey(help_text='Mandat auquel appartient ce journal', on_delete=django.db.models.deletion.CASCADE, related_name='journaux', to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='journal',
            field=models.ForeignKey(help_text="Journal comptable dans lequel est enregistrée l'écriture", on_delete=django.db.models.deletion.PROTECT, to='comptabilite.journal', verbose_name='Journal'),
        ),
        migrations.AddField(
            model_name='lettrage',
            name='compte',
            field=models.ForeignKey(help_text='Compte comptable concerné par le lettrage', on_delete=django.db.models.deletion.PROTECT, to='comptabilite.compte', verbose_name='Compte'),
        ),
        migrations.AddField(
            model_name='lettrage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='lettrage',
            name='lettre_par',
            field=models.ForeignKey(help_text='Utilisateur ayant effectué le lettrage', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Lettré par'),
        ),
        migrations.AddField(
            model_name='lettrage',
            name='mandat',
            field=models.ForeignKey(help_text='Mandat concerné par ce lettrage', on_delete=django.db.models.deletion.CASCADE, to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AddField(
            model_name='piececomptable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='piececomptable',
            name='documents_justificatifs',
            field=models.ManyToManyField(blank=True, help_text='Documents justificatifs attachés à cette pièce', related_name='pieces_comptables', to='documents.document', verbose_name='Documents justificatifs'),
        ),
        migrations.AddField(
            model_name='piececomptable',
            name='dossier',
            field=models.ForeignKey(blank=True, help_text='Dossier de classement des justificatifs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_comptables', to='documents.dossier', verbose_name='Dossier'),
        ),
        migrations.AddField(
            model_name='piececomptable',
            name='journal',
            field=models.ForeignKey(blank=True, help_text="Journal comptable (optionnel si le mandat n'en a pas)", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pieces', to='comptabilite.journal', verbose_name='Journal'),
        ),
        migrations.AddField(
            model_name='piececomptable',
            name='mandat',
            field=models.ForeignKey(help_text='Mandat concerné par cette pièce', on_delete=django.db.models.deletion.CASCADE, related_name='pieces_comptables', to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AddField(
            model_name='piececomptable',
            name='valide_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant validé la pièce', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='piece',
            field=models.ForeignKey(blank=True, help_text='Pièce comptable regroupant les écritures', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='comptabilite.piececomptable', verbose_name='Pièce comptable'),
        ),
        migrations.AddField(
            model_name='plancomptable',
            name='base_sur',
            field=models.ForeignKey(blank=True, help_text='Plan template de base dont celui-ci dérive', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derives', to='comptabilite.plancomptable', verbose_name='Basé sur'),
        ),
        migrations.AddField(
            model_name='plancomptable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='plancomptable',
            name='mandat',
            field=models.ForeignKey(blank=True, help_text='Mandat utilisant ce plan comptable (vide pour les templates)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans_comptables', to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AddField(
            model_name='compte',
            name='plan_comptable',
            field=models.ForeignKey(help_text='Plan comptable auquel appartient ce compte', on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='comptabilite.plancomptable', verbose_name='Plan comptable'),
        ),
        migrations.AddField(
            model_name='typepiececomptable',
            name='compte_charge_defaut',
            field=models.ForeignKey(blank=True, help_text='Compte de charge utilisé par défaut pour ce type de pièce', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comptabilite.compte', verbose_name='Compte de charge par défaut'),
        ),
        migrations.AddField(
            model_name='typepiececomptable',
            name='compte_produit_defaut',
            field=models.ForeignKey(blank=True, help_text='Compte de produit utilisé par défaut pour ce type de pièce', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comptabilite.compte', verbose_name='Compte de produit par défaut'),
        ),
        migrations.AddField(
            model_name='typepiececomptable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='piececomptable',
            name='type_piece',
            field=models.ForeignKey(help_text='Type de pièce comptable (facture, avoir, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='pieces', to='comptabilite.typepiececomptable', verbose_name='Type de pièce'),
        ),
        migrations.AddField(
            model_name='typeplancomptable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='plancomptable',
            name='type_plan',
            field=models.ForeignKey(help_text='Type de plan comptable (PME, OHADA, Swiss GAAP, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='comptabilite.typeplancomptable', verbose_name='Type de plan'),
        ),
        migrations.AddField(
            model_name='classecomptable',
            name='type_plan',
            field=models.ForeignKey(help_text='Type de plan comptable auquel appartient cette classe', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='comptabilite.typeplancomptable', verbose_name='Type de plan'),
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together={('mandat', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='lettrage',
            unique_together={('mandat', 'compte', 'code_lettrage')},
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['mandat', 'date_ecriture'], name='ecritures_c_mandat__a1e52b_idx'),
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['compte', 'date_ecriture'], name='ecritures_c_compte__836f38_idx'),
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['numero_piece'], name='ecritures_c_numero__c22218_idx'),
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['code_lettrage'], name='ecritures_c_code_le_f35e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['statut'], name='ecritures_c_statut_fb346c_idx'),
        ),
        migrations.AddIndex(
            model_name='compte',
            index=models.Index(fields=['plan_comptable', 'numero'], name='comptes_plan_co_6db345_idx'),
        ),
        migrations.AddIndex(
            model_name='compte',
            index=models.Index(fields=['type_compte', 'classe'], name='comptes_type_co_fb38c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compte',
            unique_together={('plan_comptable', 'numero')},
        ),
        migrations.AddIndex(
            model_name='piececomptable',
            index=models.Index(fields=['mandat', 'date_piece'], name='pieces_comp_mandat__9297f7_idx'),
        ),
        migrations.AddIndex(
            model_name='piececomptable',
            index=models.Index(fields=['journal', 'date_piece'], name='pieces_comp_journal_d26772_idx'),
        ),
        migrations.AddIndex(
            model_name='piececomptable',
            index=models.Index(fields=['type_piece', 'statut'], name='pieces_comp_type_pi_1d34b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classecomptable',
            unique_together={('type_plan', 'numero')},
        ),
    ]
