# Generated by Django 5.2.8 on 2025-11-13 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0001_initial'),
        ('core', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='comptabilite.compte'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='ecriture_extournee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extournes', to='comptabilite.ecriturecomptable'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='core.exercicecomptable'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='mandat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='core.mandat'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='piece_justificative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures', to='documents.document'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='valide_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journal',
            name='compte_contrepartie_defaut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comptabilite.compte'),
        ),
        migrations.AddField(
            model_name='journal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journal',
            name='mandat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux', to='core.mandat'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptabilite.journal'),
        ),
        migrations.AddField(
            model_name='lettrage',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptabilite.compte'),
        ),
        migrations.AddField(
            model_name='lettrage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lettrage',
            name='lettre_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lettrage',
            name='mandat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mandat'),
        ),
        migrations.AddField(
            model_name='piececomptable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='piececomptable',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptabilite.journal'),
        ),
        migrations.AddField(
            model_name='piececomptable',
            name='mandat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mandat'),
        ),
        migrations.AddField(
            model_name='plancomptable',
            name='base_sur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derives', to='comptabilite.plancomptable'),
        ),
        migrations.AddField(
            model_name='plancomptable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plancomptable',
            name='mandat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans_comptables', to='core.mandat'),
        ),
        migrations.AddField(
            model_name='compte',
            name='plan_comptable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='comptabilite.plancomptable'),
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together={('mandat', 'code')},
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['mandat', 'date_ecriture'], name='ecritures_c_mandat__a1e52b_idx'),
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['compte', 'date_ecriture'], name='ecritures_c_compte__836f38_idx'),
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['numero_piece'], name='ecritures_c_numero__c22218_idx'),
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['code_lettrage'], name='ecritures_c_code_le_f35e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['statut'], name='ecritures_c_statut_fb346c_idx'),
        ),
        migrations.AddIndex(
            model_name='compte',
            index=models.Index(fields=['plan_comptable', 'numero'], name='comptes_plan_co_6db345_idx'),
        ),
        migrations.AddIndex(
            model_name='compte',
            index=models.Index(fields=['type_compte', 'classe'], name='comptes_type_co_fb38c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compte',
            unique_together={('plan_comptable', 'numero')},
        ),
    ]
