# Generated by Django 6.0.2 on 2026-02-20 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_initial'),
        ('core', '0003_alter_comptebancaire_devise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='devise',
            field=models.ForeignKey(db_column='devise', default='CHF', help_text='Code ISO de la devise (CHF, EUR, USD)', on_delete=django.db.models.deletion.PROTECT, to='core.devise', verbose_name='Devise'),
        ),
    ]
