# Generated by Django 5.2.8 on 2025-11-18 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_initial'),
        ('core', '0002_client_description_client_description_de_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lettrage',
            options={'verbose_name': 'Lettrage', 'verbose_name_plural': 'Lettrages'},
        ),
        migrations.AlterModelOptions(
            name='piececomptable',
            options={'ordering': ['-date_piece', 'numero_piece'], 'verbose_name': 'Pièce comptable', 'verbose_name_plural': 'Pièces comptables'},
        ),
        migrations.AddField(
            model_name='compte',
            name='libelle_court_de',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compte',
            name='libelle_court_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compte',
            name='libelle_court_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compte',
            name='libelle_court_it',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compte',
            name='libelle_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compte',
            name='libelle_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compte',
            name='libelle_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compte',
            name='libelle_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lettrage',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('ANNULE', 'Annulé')], default='ACTIF', max_length=20),
        ),
        migrations.AddField(
            model_name='plancomptable',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plancomptable',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plancomptable',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plancomptable',
            name='description_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plancomptable',
            name='nom_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plancomptable',
            name='nom_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plancomptable',
            name='nom_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plancomptable',
            name='nom_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('COMPTABILISE', 'Comptabilisé')], db_index=True, default='BROUILLON', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='lettrage',
            unique_together={('mandat', 'compte', 'code_lettrage')},
        ),
        migrations.AddIndex(
            model_name='piececomptable',
            index=models.Index(fields=['mandat', 'date_piece'], name='pieces_comp_mandat__9297f7_idx'),
        ),
        migrations.AddIndex(
            model_name='piececomptable',
            index=models.Index(fields=['journal', 'date_piece'], name='pieces_comp_journal_d26772_idx'),
        ),
    ]
