# Generated by Django 5.2.8 on 2025-11-19 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0003_alter_lettrage_options_alter_piececomptable_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='lettrage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='lettrage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='lettrage',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='lettrage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
    ]
