# Generated by Django 5.2.8 on 2025-11-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0004_alter_compte_created_at_alter_compte_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancomptable',
            name='nom',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='nom_de',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='nom_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='nom_fr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='nom_it',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
