# Generated by Django 5.2.8 on 2025-11-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0005_alter_plancomptable_nom_alter_plancomptable_nom_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancomptable',
            name='type_plan',
            field=models.CharField(choices=[('PME', 'Plan comptable PME'), ('GENERAL', 'Plan comptable général'), ('ENTREPRISE', 'Plan comptable entreprise'), ('PERSONNALISE', 'Personnalisé'), ('OHADA', 'Plan comptable OHADA'), ('SWISSGAAP', 'Plan comptable Swiss GAAP')], max_length=20),
        ),
    ]
