# Generated by Django 6.0 on 2026-01-07 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0007_typeplancomptable_classecomptable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compte',
            options={'ordering': ['numero'], 'verbose_name': 'Compte', 'verbose_name_plural': 'Comptes'},
        ),
        migrations.AlterModelOptions(
            name='ecriturecomptable',
            options={'ordering': ['date_ecriture', 'numero_piece', 'numero_ligne'], 'verbose_name': 'Écriture comptable', 'verbose_name_plural': 'Écritures comptables'},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['code'], 'verbose_name': 'Journal', 'verbose_name_plural': 'Journaux'},
        ),
        migrations.AlterModelOptions(
            name='plancomptable',
            options={'ordering': ['-created_at'], 'verbose_name': 'Plan comptable', 'verbose_name_plural': 'Plans comptables'},
        ),
        migrations.RemoveField(
            model_name='classecomptable',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='typeplancomptable',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='classecomptable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='classecomptable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='classecomptable',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='classecomptable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='classe',
            field=models.IntegerField(help_text='Numéro de classe (1-9)'),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='base_sur',
            field=models.ForeignKey(blank=True, help_text='Plan template de base', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derives', to='comptabilite.plancomptable'),
        ),
        migrations.AlterField(
            model_name='typeplancomptable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='typeplancomptable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='typeplancomptable',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='typeplancomptable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
    ]
