# Generated by Django 6.0.2 on 2026-02-22 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0007_populate_devise_fields'),
        ('core', '0008_alter_comptebancaire_devise_alter_tiers_devise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='devise',
            field=models.ForeignKey(db_column='devise', help_text='Code ISO de la devise', on_delete=django.db.models.deletion.PROTECT, to='core.devise', verbose_name='Devise'),
        ),
    ]
