# Generated by Django 6.0 on 2026-01-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0009_piece_comptable_enrichment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piececomptable',
            options={'ordering': ['-date_piece', '-numero_piece'], 'verbose_name': 'Pièce comptable', 'verbose_name_plural': 'Pièces comptables'},
        ),
        migrations.RenameIndex(
            model_name='piececomptable',
            new_name='pieces_comp_type_pi_e73264_idx',
            old_name='pieces_comp_type_pi_idx',
        ),
    ]
