# Generated by Django 6.0 on 2026-01-07 12:32
"""
Migration pour créer TypePieceComptable et migrer les données existantes.

Étapes:
1. Créer le modèle TypePieceComptable
2. Insérer les types par défaut
3. Ajouter le nouveau champ FK (nullable temporairement)
4. Migrer les anciennes données vers les nouveaux types
5. Supprimer l'ancien champ
6. Renommer le nouveau champ
"""
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_default_types(apps, schema_editor):
    """Crée les types de pièces par défaut"""
    TypePieceComptable = apps.get_model('comptabilite', 'TypePieceComptable')

    default_types = [
        {'code': 'FAC_ACH', 'libelle': "Facture d'achat", 'categorie': 'ACHAT', 'prefixe_numero': 'FA', 'ordre': 1, 'is_system': True},
        {'code': 'FAC_VTE', 'libelle': "Facture de vente", 'categorie': 'VENTE', 'prefixe_numero': 'FV', 'ordre': 2, 'is_system': True},
        {'code': 'AVOIR_ACH', 'libelle': "Avoir reçu", 'categorie': 'ACHAT', 'prefixe_numero': 'AA', 'ordre': 3, 'is_system': True},
        {'code': 'AVOIR_VTE', 'libelle': "Avoir émis", 'categorie': 'VENTE', 'prefixe_numero': 'AV', 'ordre': 4, 'is_system': True},
        {'code': 'NDF', 'libelle': "Note de frais", 'categorie': 'ACHAT', 'prefixe_numero': 'NF', 'ordre': 5, 'is_system': True},
        {'code': 'REL_BNQ', 'libelle': "Relevé bancaire", 'categorie': 'BANQUE', 'prefixe_numero': 'BQ', 'ordre': 6, 'is_system': True},
        {'code': 'CAISSE', 'libelle': "Pièce de caisse", 'categorie': 'CAISSE', 'prefixe_numero': 'CA', 'ordre': 7, 'is_system': True},
        {'code': 'SALAIRE', 'libelle': "Fiche de salaire", 'categorie': 'SALAIRE', 'prefixe_numero': 'SA', 'ordre': 8, 'is_system': True},
        {'code': 'OD', 'libelle': "Opération diverse", 'categorie': 'OD', 'prefixe_numero': 'OD', 'ordre': 9, 'is_system': True},
        {'code': 'AUTRE', 'libelle': "Autre", 'categorie': 'AUTRE', 'prefixe_numero': 'AU', 'ordre': 99, 'is_system': True},
    ]

    for type_data in default_types:
        TypePieceComptable.objects.get_or_create(
            code=type_data['code'],
            defaults=type_data
        )


def migrate_piece_types(apps, schema_editor):
    """Migre les anciennes valeurs de type_piece vers les nouvelles FK"""
    PieceComptable = apps.get_model('comptabilite', 'PieceComptable')
    TypePieceComptable = apps.get_model('comptabilite', 'TypePieceComptable')

    # Mapping ancien code -> nouveau code
    mapping = {
        'FACTURE_ACHAT': 'FAC_ACH',
        'FACTURE_VENTE': 'FAC_VTE',
        'NOTE_FRAIS': 'NDF',
        'RELEVE_BANQUE': 'REL_BNQ',
        'CAISSE': 'CAISSE',
        'OD': 'OD',
        'AVOIR': 'AVOIR_ACH',  # Par défaut avoir reçu
        'SALAIRE': 'SALAIRE',
        'AUTRE': 'AUTRE',
    }

    # Type par défaut
    type_autre = TypePieceComptable.objects.filter(code='AUTRE').first()

    for piece in PieceComptable.objects.all():
        old_type = piece.type_piece_old
        new_code = mapping.get(old_type, 'AUTRE')
        new_type = TypePieceComptable.objects.filter(code=new_code).first() or type_autre
        piece.type_piece_new = new_type
        piece.save(update_fields=['type_piece_new'])


def reverse_migrate_piece_types(apps, schema_editor):
    """Reverse: remet les anciennes valeurs"""
    PieceComptable = apps.get_model('comptabilite', 'PieceComptable')

    # Mapping inverse
    mapping = {
        'FAC_ACH': 'FACTURE_ACHAT',
        'FAC_VTE': 'FACTURE_VENTE',
        'NDF': 'NOTE_FRAIS',
        'REL_BNQ': 'RELEVE_BANQUE',
        'CAISSE': 'CAISSE',
        'OD': 'OD',
        'AVOIR_ACH': 'AVOIR',
        'AVOIR_VTE': 'AVOIR',
        'SALAIRE': 'SALAIRE',
        'AUTRE': 'AUTRE',
    }

    for piece in PieceComptable.objects.all():
        if piece.type_piece_new:
            piece.type_piece_old = mapping.get(piece.type_piece_new.code, 'AUTRE')
            piece.save(update_fields=['type_piece_old'])


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0010_alter_piececomptable_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Créer le modèle TypePieceComptable
        migrations.CreateModel(
            name='TypePieceComptable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('code', models.CharField(db_index=True, help_text='Code unique (FAC_ACH, FAC_VTE, NDF, etc.)', max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(choices=[('ACHAT', 'Achats'), ('VENTE', 'Ventes'), ('BANQUE', 'Banque'), ('CAISSE', 'Caisse'), ('OD', 'Opérations diverses'), ('SALAIRE', 'Salaires'), ('AUTRE', 'Autre')], db_index=True, default='AUTRE', max_length=20)),
                ('prefixe_numero', models.CharField(blank=True, help_text='Préfixe pour la numérotation automatique (ex: FAC, AVR)', max_length=10)),
                ('taux_tva_defaut', models.DecimalField(blank=True, decimal_places=2, help_text='Taux de TVA par défaut (ex: 8.10)', max_digits=5, null=True)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage dans les listes")),
                ('is_system', models.BooleanField(default=False, help_text='Type système créé par défaut')),
                ('compte_charge_defaut', models.ForeignKey(blank=True, help_text='Compte de charge par défaut', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comptabilite.compte')),
                ('compte_produit_defaut', models.ForeignKey(blank=True, help_text='Compte de produit par défaut', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comptabilite.compte')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Type de pièce comptable',
                'verbose_name_plural': 'Types de pièces comptables',
                'db_table': 'types_pieces_comptables',
                'ordering': ['ordre', 'code'],
            },
        ),

        # 2. Insérer les types par défaut
        migrations.RunPython(create_default_types, migrations.RunPython.noop),

        # 3. Renommer l'ancien champ type_piece
        migrations.RenameField(
            model_name='piececomptable',
            old_name='type_piece',
            new_name='type_piece_old',
        ),

        # 4. Ajouter le nouveau champ FK (nullable temporairement)
        migrations.AddField(
            model_name='piececomptable',
            name='type_piece_new',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='pieces',
                to='comptabilite.typepiececomptable',
                help_text='Type de pièce comptable'
            ),
        ),

        # 5. Migrer les données
        migrations.RunPython(migrate_piece_types, reverse_migrate_piece_types),

        # 6. Supprimer l'ancien champ
        migrations.RemoveField(
            model_name='piececomptable',
            name='type_piece_old',
        ),

        # 7. Renommer le nouveau champ
        migrations.RenameField(
            model_name='piececomptable',
            old_name='type_piece_new',
            new_name='type_piece',
        ),

        # 8. Rendre le champ non-nullable et mettre à jour les contraintes
        migrations.AlterField(
            model_name='piececomptable',
            name='type_piece',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='pieces',
                to='comptabilite.typepiececomptable',
                help_text='Type de pièce comptable'
            ),
        ),

        # 9. Recréer l'index
        migrations.AddIndex(
            model_name='piececomptable',
            index=models.Index(fields=['type_piece', 'statut'], name='pieces_comp_type_pi_1d34b4_idx'),
        ),
    ]
