# Generated by Django 6.0.3 on 2026-03-24 09:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0011_contrats_et_analytique'),
        ('core', '0025_immobilisations_releves_cours'),
        ('documents', '0009_contrats_et_analytique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveBancaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('langue_saisie', models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie')),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_fin', models.DateField(verbose_name='Date fin')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('solde_debut', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Solde début')),
                ('solde_fin', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Solde fin')),
                ('format_import', models.CharField(blank=True, help_text='CSV, MT940, CAMT.053, etc.', max_length=20, verbose_name='Format')),
                ('nb_lignes', models.IntegerField(default=0, verbose_name='Nb lignes')),
                ('nb_rapprochees', models.IntegerField(default=0, verbose_name='Nb rapprochées')),
                ('ecart', models.DecimalField(decimal_places=2, default=0, help_text='Différence entre solde relevé et solde comptable', max_digits=15, verbose_name='Écart')),
                ('statut', models.CharField(choices=[('IMPORTE', 'Importé'), ('EN_COURS', 'Rapprochement en cours'), ('RAPPROCHE', 'Rapproché'), ('VALIDE', 'Validé')], db_index=True, default='IMPORTE', max_length=20, verbose_name='Statut')),
                ('compte_bancaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves', to='core.comptebancaire', verbose_name='Compte bancaire')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('devise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.devise', verbose_name='Devise')),
                ('fichier_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releves_bancaires', to='documents.document', verbose_name='Fichier source')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releves_bancaires', to='comptabilite.journal', verbose_name='Journal bancaire')),
                ('mandat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_bancaires', to='core.mandat', verbose_name='Mandat')),
            ],
            options={
                'verbose_name': 'Relevé bancaire',
                'verbose_name_plural': 'Relevés bancaires',
                'db_table': 'releves_bancaires',
                'ordering': ['-date_fin'],
            },
        ),
        migrations.CreateModel(
            name='LigneReleve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('langue_saisie', models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie')),
                ('date_valeur', models.DateField(verbose_name='Date valeur')),
                ('date_operation', models.DateField(blank=True, null=True, verbose_name='Date opération')),
                ('libelle', models.CharField(max_length=500, verbose_name='Libellé')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='Référence')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Positif = crédit, négatif = débit', max_digits=15, verbose_name='Montant')),
                ('statut', models.CharField(choices=[('NON_RAPPROCHEE', 'Non rapprochée'), ('RAPPROCHEE', 'Rapprochée'), ('IGNOREE', 'Ignorée')], db_index=True, default='NON_RAPPROCHEE', max_length=20, verbose_name='Statut')),
                ('date_rapprochement', models.DateTimeField(blank=True, null=True, verbose_name='Date rapprochement')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('ecriture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_releve', to='comptabilite.ecriturecomptable', verbose_name='Écriture rapprochée')),
                ('releve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.relevebancaire', verbose_name='Relevé')),
            ],
            options={
                'verbose_name': 'Ligne de relevé',
                'verbose_name_plural': 'Lignes de relevé',
                'db_table': 'lignes_releve',
                'ordering': ['date_valeur'],
            },
        ),
        migrations.CreateModel(
            name='Immobilisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('langue_saisie', models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie')),
                ('numero', models.CharField(max_length=50, verbose_name='Numéro inventaire')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('categorie', models.CharField(blank=True, help_text='Code ParametreMetier (module=comptabilite, categorie=type_immobilisation)', max_length=50, verbose_name='Catégorie')),
                ('date_acquisition', models.DateField(verbose_name="Date d'acquisition")),
                ('date_mise_en_service', models.DateField(blank=True, null=True, verbose_name='Date de mise en service')),
                ('valeur_acquisition', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Valeur d'acquisition")),
                ('fournisseur', models.CharField(blank=True, max_length=255, verbose_name='Fournisseur')),
                ('numero_facture', models.CharField(blank=True, max_length=100, verbose_name='N° facture')),
                ('methode_amortissement', models.CharField(choices=[('LINEAIRE', 'Linéaire'), ('DEGRESSIF', 'Dégressif'), ('UNITE_PRODUCTION', 'Unités de production')], default='LINEAIRE', max_length=20, verbose_name="Méthode d'amortissement")),
                ('duree_amortissement_mois', models.IntegerField(help_text='Durée de vie utile en mois', verbose_name='Durée amort. (mois)')),
                ('taux_amortissement', models.DecimalField(blank=True, decimal_places=2, help_text='Pour méthode dégressive (ex: 25.00)', max_digits=6, null=True, verbose_name="Taux d'amortissement (%)")),
                ('valeur_residuelle', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valeur résiduelle')),
                ('amortissement_cumule', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Amortissement cumulé')),
                ('valeur_nette_comptable', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valeur nette comptable')),
                ('date_cession', models.DateField(blank=True, null=True, verbose_name='Date de cession')),
                ('prix_cession', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Prix de cession')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('AMORTI', 'Totalement amorti'), ('CEDE', 'Cédé'), ('MIS_AU_REBUT', 'Mis au rebut')], db_index=True, default='ACTIF', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('compte_amort_cumule', models.ForeignKey(blank=True, help_text='Correctif actif, si méthode indirecte (ex: 1509)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='immobilisations_amort_cumule', to='comptabilite.compte', verbose_name='Compte amort. cumulé')),
                ('compte_amortissement', models.ForeignKey(help_text='Compte de charge (ex: 6800)', on_delete=django.db.models.deletion.PROTECT, related_name='immobilisations_amort', to='comptabilite.compte', verbose_name='Compte amortissement')),
                ('compte_immobilisation', models.ForeignKey(help_text='Compte actif au bilan (ex: 1500)', on_delete=django.db.models.deletion.PROTECT, related_name='immobilisations_actif', to='comptabilite.compte', verbose_name='Compte immobilisation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('devise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.devise', verbose_name='Devise')),
                ('mandat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immobilisations', to='core.mandat', verbose_name='Mandat')),
            ],
            options={
                'verbose_name': 'Immobilisation',
                'verbose_name_plural': 'Immobilisations',
                'db_table': 'immobilisations',
                'ordering': ['numero'],
                'indexes': [models.Index(fields=['mandat', 'statut'], name='immobilisat_mandat__892bb8_idx')],
                'unique_together': {('mandat', 'numero')},
            },
        ),
        migrations.AddIndex(
            model_name='relevebancaire',
            index=models.Index(fields=['mandat', 'compte_bancaire'], name='releves_ban_mandat__66f087_idx'),
        ),
        migrations.AddIndex(
            model_name='lignereleve',
            index=models.Index(fields=['releve', 'statut'], name='lignes_rele_releve__f02647_idx'),
        ),
    ]
