# Generated by Django 6.0 on 2026-01-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0012_journal_optionnel'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='piececomptable',
            name='unique_numero_piece_par_mandat',
        ),
        migrations.RemoveIndex(
            model_name='piececomptable',
            name='pieces_comp_type_pi_e73264_idx',
        ),
    ]
