# Generated by Django 6.0.3 on 2026-03-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0012_immobilisations_releves_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axeanalytique',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='axeanalytique',
            name='obligatoire',
            field=models.BooleanField(default=False, help_text='Si coché, chaque écriture doit être ventilée sur cet axe', verbose_name='Obligatoire'),
        ),
        migrations.AlterField(
            model_name='classecomptable',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='lettrage',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='sectionanalytique',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='typepiececomptable',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='typeplancomptable',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='ventilationanalytique',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='ventilationanalytique',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Montant calculé (écriture × pourcentage / 100)', max_digits=15, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='ventilationanalytique',
            name='pourcentage',
            field=models.DecimalField(decimal_places=2, help_text="Part de l'écriture affectée à cette section (0-100)", max_digits=6, verbose_name='Pourcentage'),
        ),
    ]
