# Generated by Django 6.0.2 on 2026-02-11 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0013_remove_piececomptable_unique_numero_piece_par_mandat_and_more'),
        ('core', '0017_remove_collaborateurfiduciaire_unique_collaborateur_mandat_and_more'),
        ('documents', '0010_intelligence_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classecomptable',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée de la classe comptable', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='classecomptable',
            name='libelle',
            field=models.CharField(help_text='Libellé de la classe (ex: Actifs, Passifs)', max_length=200, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='classecomptable',
            name='numero',
            field=models.IntegerField(help_text='Numéro de la classe comptable (1, 2, 3...)', verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='classecomptable',
            name='numero_debut',
            field=models.CharField(blank=True, help_text='Premier numéro de compte de cette classe (ex: 1000)', max_length=10, verbose_name='Numéro de début'),
        ),
        migrations.AlterField(
            model_name='classecomptable',
            name='numero_fin',
            field=models.CharField(blank=True, help_text='Dernier numéro de compte de cette classe (ex: 1999)', max_length=10, verbose_name='Numéro de fin'),
        ),
        migrations.AlterField(
            model_name='classecomptable',
            name='type_compte',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('PASSIF', 'Passif'), ('CHARGE', 'Charge'), ('PRODUIT', 'Produit'), ('RESULTAT', 'Résultat')], help_text='Nature des comptes de cette classe (Actif, Passif, etc.)', max_length=10, verbose_name='Type de compte'),
        ),
        migrations.AlterField(
            model_name='classecomptable',
            name='type_plan',
            field=models.ForeignKey(help_text='Type de plan comptable auquel appartient cette classe', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='comptabilite.typeplancomptable', verbose_name='Type de plan'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='classe',
            field=models.IntegerField(help_text='Numéro de classe comptable (1-9)', verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='classe_comptable',
            field=models.ForeignKey(blank=True, help_text='Classe comptable de référence (1=Actifs, 2=Passifs, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes', to='comptabilite.classecomptable', verbose_name='Classe comptable'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='code_tva_defaut',
            field=models.CharField(blank=True, help_text='Code TVA appliqué par défaut (200, 205, 300, etc.)', max_length=10, verbose_name='Code TVA par défaut'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='compte_parent',
            field=models.ForeignKey(blank=True, help_text='Compte de niveau supérieur pour la hiérarchie', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_comptes', to='comptabilite.compte', verbose_name='Compte parent'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='est_collectif',
            field=models.BooleanField(default=False, help_text='Compte collectif (total) qui regroupe des sous-comptes', verbose_name='Compte collectif'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='imputable',
            field=models.BooleanField(default=True, help_text='Indique si le compte peut recevoir des écritures comptables', verbose_name='Imputable'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='lettrable',
            field=models.BooleanField(default=False, help_text='Indique si le lettrage est possible sur ce compte', verbose_name='Lettrable'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='libelle',
            field=models.CharField(help_text='Libellé complet du compte', max_length=255, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='libelle_court',
            field=models.CharField(blank=True, help_text='Libellé abrégé pour les états financiers', max_length=100, verbose_name='Libellé court'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='libelle_court_de',
            field=models.CharField(blank=True, help_text='Libellé abrégé pour les états financiers', max_length=100, null=True, verbose_name='Libellé court'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='libelle_court_en',
            field=models.CharField(blank=True, help_text='Libellé abrégé pour les états financiers', max_length=100, null=True, verbose_name='Libellé court'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='libelle_court_fr',
            field=models.CharField(blank=True, help_text='Libellé abrégé pour les états financiers', max_length=100, null=True, verbose_name='Libellé court'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='libelle_court_it',
            field=models.CharField(blank=True, help_text='Libellé abrégé pour les états financiers', max_length=100, null=True, verbose_name='Libellé court'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='libelle_de',
            field=models.CharField(help_text='Libellé complet du compte', max_length=255, null=True, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='libelle_en',
            field=models.CharField(help_text='Libellé complet du compte', max_length=255, null=True, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='libelle_fr',
            field=models.CharField(help_text='Libellé complet du compte', max_length=255, null=True, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='libelle_it',
            field=models.CharField(help_text='Libellé complet du compte', max_length=255, null=True, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='niveau',
            field=models.IntegerField(default=1, help_text='Niveau hiérarchique du compte (1=principal, 2=sous-compte, etc.)', verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='numero',
            field=models.CharField(db_index=True, help_text='Numéro du compte (ex: 1000, 1100, 6000)', max_length=20, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='obligatoire_tiers',
            field=models.BooleanField(default=False, help_text="Exige la saisie d'un tiers lors des écritures", verbose_name='Tiers obligatoire'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='plan_comptable',
            field=models.ForeignKey(help_text='Plan comptable auquel appartient ce compte', on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='comptabilite.plancomptable', verbose_name='Plan comptable'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='solde_credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumul des montants au crédit', max_digits=15, verbose_name='Solde crédit'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='solde_debit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumul des montants au débit', max_digits=15, verbose_name='Solde débit'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='soumis_tva',
            field=models.BooleanField(default=False, help_text='Indique si les opérations sur ce compte sont soumises à TVA', verbose_name='Soumis à TVA'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='type_compte',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('PASSIF', 'Passif'), ('CHARGE', 'Charge'), ('PRODUIT', 'Produit')], help_text='Nature du compte (Actif, Passif, Charge, Produit)', max_length=10, verbose_name='Type de compte'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='code_lettrage',
            field=models.CharField(blank=True, db_index=True, help_text='Code identifiant le groupe de lettrage', max_length=20, verbose_name='Code de lettrage'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='code_tva',
            field=models.CharField(blank=True, help_text='Code TVA applicable (200, 205, 300, etc.)', max_length=10, verbose_name='Code TVA'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='compte',
            field=models.ForeignKey(help_text='Compte comptable mouvementé', on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='comptabilite.compte', verbose_name='Compte'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='compte_auxiliaire',
            field=models.CharField(blank=True, help_text='Compte auxiliaire (tiers, analytique)', max_length=50, verbose_name='Compte auxiliaire'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='date_echeance',
            field=models.DateField(blank=True, help_text="Date d'échéance du paiement", null=True, verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='date_ecriture',
            field=models.DateField(db_index=True, help_text="Date de l'écriture comptable", verbose_name="Date d'écriture"),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='date_lettrage',
            field=models.DateField(blank=True, help_text="Date à laquelle l'écriture a été lettrée", null=True, verbose_name='Date de lettrage'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='date_valeur',
            field=models.DateField(blank=True, help_text='Date de valeur bancaire', null=True, verbose_name='Date de valeur'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='date_validation',
            field=models.DateTimeField(blank=True, help_text="Date et heure de validation de l'écriture", null=True, verbose_name='Date de validation'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='devise',
            field=models.CharField(default='CHF', help_text='Code ISO de la devise (CHF, EUR, USD)', max_length=3, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='ecriture_extournee',
            field=models.ForeignKey(blank=True, help_text="Écriture d'origine si celle-ci est une extourne", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extournes', to='comptabilite.ecriturecomptable', verbose_name='Écriture extournée'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='exercice',
            field=models.ForeignKey(help_text="Exercice comptable de l'écriture", on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='core.exercicecomptable', verbose_name='Exercice comptable'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='journal',
            field=models.ForeignKey(help_text="Journal comptable dans lequel est enregistrée l'écriture", on_delete=django.db.models.deletion.PROTECT, to='comptabilite.journal', verbose_name='Journal'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='libelle',
            field=models.TextField(help_text="Libellé de l'écriture comptable", verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='libelle_complement',
            field=models.CharField(blank=True, help_text="Informations complémentaires sur l'écriture", max_length=255, verbose_name='Complément de libellé'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='mandat',
            field=models.ForeignKey(help_text='Mandat concerné par cette écriture', on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='montant_credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant au crédit (en devise du compte)', max_digits=15, verbose_name='Montant crédit'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='montant_debit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant au débit (en devise du compte)', max_digits=15, verbose_name='Montant débit'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de TVA calculé', max_digits=15, verbose_name='Montant TVA'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='numero_ligne',
            field=models.IntegerField(default=1, help_text='Numéro de ligne dans la pièce', verbose_name='Numéro de ligne'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='numero_piece',
            field=models.CharField(db_index=True, help_text='Numéro de la pièce comptable', max_length=50, verbose_name='Numéro de pièce'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='piece',
            field=models.ForeignKey(blank=True, help_text='Pièce comptable regroupant les écritures', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='comptabilite.piececomptable', verbose_name='Pièce comptable'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='piece_justificative',
            field=models.ForeignKey(blank=True, help_text="Document justificatif associé à l'écriture", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures', to='documents.document', verbose_name='Pièce justificative'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validée'), ('LETTRE', 'Lettrée'), ('CLOTURE', 'Clôturée'), ('EXTOURNE', 'Extournée')], db_index=True, default='BROUILLON', help_text="Statut de l'écriture (Brouillon, Validée, etc.)", max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='taux_change',
            field=models.DecimalField(decimal_places=6, default=1, help_text='Taux de change vers la devise de référence', max_digits=10, verbose_name='Taux de change'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='valide_par',
            field=models.ForeignKey(help_text="Utilisateur ayant validé l'écriture", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='code',
            field=models.CharField(db_index=True, help_text='Code unique du journal (VTE, ACH, BNQ, etc.)', max_length=10, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='compte_contrepartie_defaut',
            field=models.ForeignKey(blank=True, help_text='Compte utilisé par défaut pour la contrepartie des écritures', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comptabilite.compte', verbose_name='Compte de contrepartie par défaut'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='dernier_numero',
            field=models.IntegerField(default=0, help_text='Dernier numéro de pièce utilisé dans ce journal', verbose_name='Dernier numéro'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='libelle',
            field=models.CharField(help_text='Libellé du journal', max_length=100, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='mandat',
            field=models.ForeignKey(help_text='Mandat auquel appartient ce journal', on_delete=django.db.models.deletion.CASCADE, related_name='journaux', to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='numerotation_auto',
            field=models.BooleanField(default=True, help_text='Active la numérotation automatique des pièces', verbose_name='Numérotation automatique'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='prefixe_piece',
            field=models.CharField(blank=True, help_text='Préfixe ajouté aux numéros de pièces (ex: FA, AV)', max_length=10, verbose_name='Préfixe des pièces'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='type_journal',
            field=models.CharField(choices=[('VTE', 'Ventes'), ('ACH', 'Achats'), ('BNQ', 'Banque'), ('CAS', 'Caisse'), ('OD', 'Opérations diverses'), ('ANO', 'A-nouveaux'), ('EXT', 'Extourne')], help_text='Type de journal (Ventes, Achats, Banque, etc.)', max_length=10, verbose_name='Type de journal'),
        ),
        migrations.AlterField(
            model_name='lettrage',
            name='code_lettrage',
            field=models.CharField(help_text='Code unique identifiant ce lettrage', max_length=20, unique=True, verbose_name='Code de lettrage'),
        ),
        migrations.AlterField(
            model_name='lettrage',
            name='complet',
            field=models.BooleanField(default=False, help_text='Indique si le lettrage est complet (solde = 0)', verbose_name='Complet'),
        ),
        migrations.AlterField(
            model_name='lettrage',
            name='compte',
            field=models.ForeignKey(help_text='Compte comptable concerné par le lettrage', on_delete=django.db.models.deletion.PROTECT, to='comptabilite.compte', verbose_name='Compte'),
        ),
        migrations.AlterField(
            model_name='lettrage',
            name='date_lettrage',
            field=models.DateField(help_text='Date à laquelle le lettrage a été effectué', verbose_name='Date de lettrage'),
        ),
        migrations.AlterField(
            model_name='lettrage',
            name='lettre_par',
            field=models.ForeignKey(help_text='Utilisateur ayant effectué le lettrage', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Lettré par'),
        ),
        migrations.AlterField(
            model_name='lettrage',
            name='mandat',
            field=models.ForeignKey(help_text='Mandat concerné par ce lettrage', on_delete=django.db.models.deletion.CASCADE, to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AlterField(
            model_name='lettrage',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, help_text='Montant total des écritures lettrées', max_digits=15, verbose_name='Montant total'),
        ),
        migrations.AlterField(
            model_name='lettrage',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Solde résiduel du lettrage (0 si complet)', max_digits=15, verbose_name='Solde'),
        ),
        migrations.AlterField(
            model_name='lettrage',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('ANNULE', 'Annulé')], default='ACTIF', help_text='Statut du lettrage (Actif ou Annulé)', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='date_piece',
            field=models.DateField(db_index=True, help_text='Date de la pièce comptable', verbose_name='Date de pièce'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='date_validation',
            field=models.DateTimeField(blank=True, help_text='Date et heure de validation de la pièce', null=True, verbose_name='Date de validation'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='documents_justificatifs',
            field=models.ManyToManyField(blank=True, help_text='Documents justificatifs attachés à cette pièce', related_name='pieces_comptables', to='documents.document', verbose_name='Documents justificatifs'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='dossier',
            field=models.ForeignKey(blank=True, help_text='Dossier de classement des justificatifs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_comptables', to='documents.dossier', verbose_name='Dossier'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='equilibree',
            field=models.BooleanField(db_index=True, default=True, help_text='Indique si la pièce est équilibrée (débit = crédit)', verbose_name='Équilibrée'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='journal',
            field=models.ForeignKey(blank=True, help_text="Journal comptable (optionnel si le mandat n'en a pas)", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pieces', to='comptabilite.journal', verbose_name='Journal'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='libelle',
            field=models.TextField(help_text='Description de la pièce comptable', verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='mandat',
            field=models.ForeignKey(help_text='Mandat concerné par cette pièce', on_delete=django.db.models.deletion.CASCADE, related_name='pieces_comptables', to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='metadata_ocr',
            field=models.JSONField(blank=True, default=dict, help_text='Métadonnées extraites automatiquement par OCR', verbose_name='Métadonnées OCR'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='montant_ht',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant hors taxes', max_digits=15, null=True, verbose_name='Montant HT'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='montant_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant toutes taxes comprises', max_digits=15, null=True, verbose_name='Montant TTC'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='montant_tva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant de la TVA', max_digits=15, null=True, verbose_name='Montant TVA'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='numero_piece',
            field=models.CharField(db_index=True, help_text='Numéro unique de la pièce comptable', max_length=50, verbose_name='Numéro de pièce'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='reference_externe',
            field=models.CharField(blank=True, help_text='Référence externe (ex: numéro facture fournisseur)', max_length=100, verbose_name='Référence externe'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('COMPTABILISE', 'Comptabilisé')], db_index=True, default='BROUILLON', help_text='Statut de la pièce comptable', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='tiers_nom',
            field=models.CharField(blank=True, help_text='Nom du fournisseur ou client', max_length=200, verbose_name='Nom du tiers'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='tiers_numero_tva',
            field=models.CharField(blank=True, help_text='Numéro de TVA du fournisseur ou client', max_length=50, verbose_name='N° TVA du tiers'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='total_credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Somme des montants au crédit', max_digits=15, verbose_name='Total crédit'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='total_debit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Somme des montants au débit', max_digits=15, verbose_name='Total débit'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='type_piece',
            field=models.ForeignKey(help_text='Type de pièce comptable (facture, avoir, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='pieces', to='comptabilite.typepiececomptable', verbose_name='Type de pièce'),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='valide_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant validé la pièce', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='base_sur',
            field=models.ForeignKey(blank=True, help_text='Plan template de base dont celui-ci dérive', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derives', to='comptabilite.plancomptable', verbose_name='Basé sur'),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='description',
            field=models.TextField(blank=True, help_text='Description du plan comptable', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='description_de',
            field=models.TextField(blank=True, help_text='Description du plan comptable', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description du plan comptable', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='description_fr',
            field=models.TextField(blank=True, help_text='Description du plan comptable', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='description_it',
            field=models.TextField(blank=True, help_text='Description du plan comptable', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='is_template',
            field=models.BooleanField(db_index=True, default=False, help_text='Indique si ce plan est un modèle réutilisable', verbose_name='Est un template'),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='mandat',
            field=models.ForeignKey(blank=True, help_text='Mandat utilisant ce plan comptable (vide pour les templates)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans_comptables', to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='nom',
            field=models.CharField(help_text='Nom du plan comptable', max_length=300, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='nom_de',
            field=models.CharField(help_text='Nom du plan comptable', max_length=300, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='nom_en',
            field=models.CharField(help_text='Nom du plan comptable', max_length=300, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='nom_fr',
            field=models.CharField(help_text='Nom du plan comptable', max_length=300, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='nom_it',
            field=models.CharField(help_text='Nom du plan comptable', max_length=300, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='plancomptable',
            name='type_plan',
            field=models.ForeignKey(help_text='Type de plan comptable (PME, OHADA, Swiss GAAP, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='comptabilite.typeplancomptable', verbose_name='Type de plan'),
        ),
        migrations.AlterField(
            model_name='typepiececomptable',
            name='categorie',
            field=models.CharField(choices=[('ACHAT', 'Achats'), ('VENTE', 'Ventes'), ('BANQUE', 'Banque'), ('CAISSE', 'Caisse'), ('OD', 'Opérations diverses'), ('SALAIRE', 'Salaires'), ('AUTRE', 'Autre')], db_index=True, default='AUTRE', help_text='Catégorie de la pièce (Achats, Ventes, Banque, etc.)', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='typepiececomptable',
            name='code',
            field=models.CharField(db_index=True, help_text='Code unique du type de pièce (FAC_ACH, FAC_VTE, NDF, etc.)', max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='typepiececomptable',
            name='compte_charge_defaut',
            field=models.ForeignKey(blank=True, help_text='Compte de charge utilisé par défaut pour ce type de pièce', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comptabilite.compte', verbose_name='Compte de charge par défaut'),
        ),
        migrations.AlterField(
            model_name='typepiececomptable',
            name='compte_produit_defaut',
            field=models.ForeignKey(blank=True, help_text='Compte de produit utilisé par défaut pour ce type de pièce', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comptabilite.compte', verbose_name='Compte de produit par défaut'),
        ),
        migrations.AlterField(
            model_name='typepiececomptable',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée du type de pièce', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='typepiececomptable',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Indique si ce type est créé par défaut et non supprimable', verbose_name='Type système'),
        ),
        migrations.AlterField(
            model_name='typepiececomptable',
            name='libelle',
            field=models.CharField(help_text='Libellé du type de pièce', max_length=100, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='typepiececomptable',
            name='ordre',
            field=models.IntegerField(default=0, help_text="Ordre d'affichage dans les listes de sélection", verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='typepiececomptable',
            name='prefixe_numero',
            field=models.CharField(blank=True, help_text='Préfixe pour la numérotation automatique (ex: FAC, AVR)', max_length=10, verbose_name='Préfixe de numéro'),
        ),
        migrations.AlterField(
            model_name='typepiececomptable',
            name='taux_tva_defaut',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taux de TVA appliqué par défaut (ex: 8.10)', max_digits=5, null=True, verbose_name='Taux TVA par défaut'),
        ),
        migrations.AlterField(
            model_name='typeplancomptable',
            name='code',
            field=models.CharField(db_index=True, help_text='Code unique du type de plan (PME, OHADA, SWISSGAAP, etc.)', max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='typeplancomptable',
            name='date_publication',
            field=models.DateField(blank=True, help_text='Date de publication officielle de cette version', null=True, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='typeplancomptable',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée du plan comptable', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='typeplancomptable',
            name='nom',
            field=models.CharField(help_text='Nom complet du type de plan comptable', max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='typeplancomptable',
            name='norme_comptable',
            field=models.CharField(blank=True, help_text='Norme comptable de référence (CO, OHADA, IFRS, etc.)', max_length=100, verbose_name='Norme comptable'),
        ),
        migrations.AlterField(
            model_name='typeplancomptable',
            name='ordre',
            field=models.IntegerField(default=0, help_text="Ordre d'affichage dans les listes de sélection", verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='typeplancomptable',
            name='pays',
            field=models.CharField(blank=True, help_text="Pays d'application (Suisse, Zone OHADA, etc.)", max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='typeplancomptable',
            name='region',
            field=models.CharField(blank=True, help_text="Région ou zone économique d'application", max_length=100, verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='typeplancomptable',
            name='version',
            field=models.CharField(blank=True, help_text='Version du plan comptable', max_length=20, verbose_name='Version'),
        ),
    ]
