# Generated by Django 6.0.3 on 2026-04-03 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0013_alter_axeanalytique_langue_saisie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteParDefaut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('langue_saisie', models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie')),
                ('type_compte', models.CharField(choices=[('CREANCES_CLIENTS', 'Créances clients'), ('BANQUE', 'Compte banque principal'), ('TVA_DUE', 'TVA due'), ('TVA_PREALABLE', 'Impôt préalable (TVA récupérable)'), ('PRODUITS', 'Compte de produits (ventes)'), ('CHARGES', 'Compte de charges (achats)'), ('CAISSE', 'Caisse'), ('CAPITAL', 'Capital')], help_text='Rôle fonctionnel de ce compte dans le plan comptable', max_length=30, verbose_name='Type de compte')),
                ('compte', models.ForeignKey(help_text='Compte comptable utilisé par défaut pour ce rôle', on_delete=django.db.models.deletion.PROTECT, related_name='roles_par_defaut', to='comptabilite.compte', verbose_name='Compte')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('plan_comptable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_par_defaut', to='comptabilite.plancomptable', verbose_name='Plan comptable')),
            ],
            options={
                'verbose_name': 'Compte par défaut',
                'verbose_name_plural': 'Comptes par défaut',
                'db_table': 'comptes_par_defaut',
                'ordering': ['plan_comptable', 'type_compte'],
                'unique_together': {('plan_comptable', 'type_compte')},
            },
        ),
    ]
