# Generated by Django 6.0.2 on 2026-02-20 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_comptebancaire_devise'),
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='devise',
            field=models.ForeignKey(db_column='devise', default='CHF', help_text='Devise du paiement', on_delete=django.db.models.deletion.PROTECT, to='core.devise', verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='tarifmandat',
            name='devise',
            field=models.ForeignKey(db_column='devise', default='CHF', help_text='Devise du tarif', on_delete=django.db.models.deletion.PROTECT, to='core.devise', verbose_name='Devise'),
        ),
    ]
