# Generated by Django 5.2.8 on 2025-11-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='qr_reference',
            field=models.CharField(blank=True, help_text='Référence QR structurée', max_length=27, null=True, unique=True),
        ),
    ]
