# Generated by Django 6.0.2 on 2026-02-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0004_alter_facture_created_at_alter_facture_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date_emission', 'numero_facture'], 'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AlterModelOptions(
            name='lignefacture',
            options={'ordering': ['facture', 'ordre'], 'verbose_name': 'Ligne de facture', 'verbose_name_plural': 'Lignes de facture'},
        ),
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-date_paiement'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AlterModelOptions(
            name='prestation',
            options={'ordering': ['code'], 'verbose_name': 'Prestation', 'verbose_name_plural': 'Prestations'},
        ),
        migrations.AlterModelOptions(
            name='relance',
            options={'ordering': ['-date_relance'], 'verbose_name': 'Relance', 'verbose_name_plural': 'Relances'},
        ),
        migrations.AlterModelOptions(
            name='timetracking',
            options={'ordering': ['-date_travail', 'utilisateur'], 'verbose_name': 'Suivi du temps', 'verbose_name_plural': 'Suivis du temps'},
        ),
    ]
