# Generated by Django 6.0.2 on 2026-02-11 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0014_alter_classecomptable_description_and_more'),
        ('core', '0017_remove_collaborateurfiduciaire_unique_collaborateur_mandat_and_more'),
        ('facturation', '0005_alter_facture_options_alter_lignefacture_options_and_more'),
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracking',
            name='operation',
            field=models.ForeignKey(blank=True, help_text='Opération liée dans le module projets', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temps_passes', to='projets.operation', verbose_name='Opération'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(help_text='Client facturé', on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='core.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='conclusion',
            field=models.TextField(blank=True, help_text='Texte de conclusion/remerciements', verbose_name='Conclusion'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='conditions_paiement',
            field=models.TextField(blank=True, help_text='Conditions de paiement spécifiques', verbose_name='Conditions de paiement'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='creee_par',
            field=models.ForeignKey(help_text='Utilisateur ayant créé la facture', on_delete=django.db.models.deletion.PROTECT, related_name='factures_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_derniere_relance',
            field=models.DateField(blank=True, help_text='Date de la dernière relance envoyée', null=True, verbose_name='Date dernière relance'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_echeance',
            field=models.DateField(db_index=True, help_text='Date limite de paiement', verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_emission',
            field=models.DateField(db_index=True, help_text="Date d'émission de la facture", verbose_name="Date d'émission"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_paiement_complet',
            field=models.DateField(blank=True, help_text='Date à laquelle la facture a été entièrement payée', null=True, verbose_name='Date de paiement complet'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_service_debut',
            field=models.DateField(blank=True, help_text='Date de début de la période facturée', null=True, verbose_name='Début de période'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_service_fin',
            field=models.DateField(blank=True, help_text='Date de fin de la période facturée', null=True, verbose_name='Fin de période'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_validation',
            field=models.DateTimeField(blank=True, help_text='Date et heure de validation', null=True, verbose_name='Date de validation'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='delai_paiement_jours',
            field=models.IntegerField(default=30, help_text='Nombre de jours accordés pour le paiement', verbose_name='Délai de paiement (jours)'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='ecriture_comptable',
            field=models.ForeignKey(blank=True, help_text='Pièce comptable associée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='comptabilite.piececomptable', verbose_name='Pièce comptable'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='facture_origine',
            field=models.ForeignKey(blank=True, help_text="Facture d'origine pour un avoir", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoirs', to='facturation.facture', verbose_name="Facture d'origine"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='fichier_pdf',
            field=models.FileField(blank=True, help_text='Fichier PDF de la facture', null=True, upload_to='factures/pdf/', verbose_name='Fichier PDF'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='introduction',
            field=models.TextField(blank=True, help_text="Texte d'introduction de la facture", verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='mandat',
            field=models.ForeignKey(help_text='Mandat concerné par cette facture', on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant total hors taxes', max_digits=15, verbose_name='Montant HT'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant total déjà payé', max_digits=15, verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_restant',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant restant à payer', max_digits=15, verbose_name='Montant restant'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant total toutes taxes comprises', max_digits=15, verbose_name='Montant TTC'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant total de la TVA', max_digits=15, verbose_name='Montant TVA'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='motif_annulation',
            field=models.TextField(blank=True, help_text="Raison de l'annulation ou de l'avoir", verbose_name="Motif d'annulation"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='nombre_relances',
            field=models.IntegerField(default=0, help_text='Nombre de relances envoyées', verbose_name='Nombre de relances'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes internes non visibles sur la facture', verbose_name='Notes internes'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero_facture',
            field=models.CharField(db_index=True, help_text='Numéro unique de la facture', max_length=50, unique=True, verbose_name='Numéro de facture'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text='Image du QR code généré', null=True, upload_to='factures/qr/', verbose_name='Image QR code'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='qr_iban',
            field=models.CharField(blank=True, help_text='IBAN pour le QR-Bill', max_length=34, verbose_name='IBAN QR'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='qr_reference',
            field=models.CharField(blank=True, help_text='Référence QR structurée pour le paiement suisse', max_length=27, null=True, unique=True, verbose_name='Référence QR'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='remise_montant',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de la remise calculée', max_digits=10, verbose_name='Montant remise'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='remise_pourcent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage de remise globale', max_digits=5, verbose_name='Remise (%)'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PROFORMA', 'Pro forma'), ('EMISE', 'Émise'), ('ENVOYEE', 'Envoyée'), ('RELANCEE', 'Relancée'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée'), ('PAYEE', 'Payée'), ('EN_RETARD', 'En retard'), ('ANNULEE', 'Annulée'), ('AVOIR', 'Avoir')], db_index=True, default='BROUILLON', help_text='Statut actuel de la facture', max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('FACTURE', 'Facture'), ('AVOIR', 'Avoir'), ('ACOMPTE', "Facture d'acompte")], default='FACTURE', help_text='Type de document (Facture, Avoir, Acompte)', max_length=20, verbose_name='Type de facture'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='validee_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant validé la facture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='description',
            field=models.TextField(help_text='Description de la ligne', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='description_detaillee',
            field=models.TextField(blank=True, help_text='Description détaillée additionnelle', verbose_name='Description détaillée'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='facture',
            field=models.ForeignKey(help_text='Facture à laquelle appartient cette ligne', on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.facture', verbose_name='Facture'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, help_text='Montant hors taxes de la ligne', max_digits=15, verbose_name='Montant HT'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, help_text='Montant toutes taxes comprises', max_digits=15, verbose_name='Montant TTC'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, help_text='Montant de TVA calculé', max_digits=15, verbose_name='Montant TVA'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='ordre',
            field=models.IntegerField(default=0, help_text="Ordre d'affichage de la ligne", verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='prestation',
            field=models.ForeignKey(blank=True, help_text='Prestation associée à cette ligne', null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturation.prestation', verbose_name='Prestation'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='prix_unitaire_ht',
            field=models.DecimalField(decimal_places=2, help_text='Prix unitaire hors taxes', max_digits=10, verbose_name='Prix unitaire HT'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Quantité facturée', max_digits=10, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='remise_pourcent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage de remise sur cette ligne', max_digits=5, verbose_name='Remise (%)'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=8.1, help_text='Taux de TVA appliqué', max_digits=5, verbose_name='Taux TVA'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='temps_factures',
            field=models.ManyToManyField(blank=True, help_text='Temps de travail associés à cette ligne', related_name='lignes_facture', to='facturation.timetracking', verbose_name='Temps facturés'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='unite',
            field=models.CharField(default='heure', help_text='Unité de mesure', max_length=50, verbose_name='Unité'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateField(db_index=True, help_text='Date du paiement', verbose_name='Date de paiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_validation',
            field=models.DateTimeField(blank=True, help_text='Date et heure de validation', null=True, verbose_name='Date de validation'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='devise',
            field=models.CharField(default='CHF', help_text='Devise du paiement', max_length=3, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='ecriture_comptable',
            field=models.ForeignKey(blank=True, help_text='Écriture comptable associée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='comptabilite.ecriturecomptable', verbose_name='Écriture comptable'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='facture',
            field=models.ForeignKey(help_text='Facture concernée par ce paiement', on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='facturation.facture', verbose_name='Facture'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('VIREMENT', 'Virement bancaire'), ('QR_BILL', 'QR-Bill'), ('CARTE', 'Carte bancaire'), ('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('COMPENSATION', 'Compensation'), ('AUTRE', 'Autre')], help_text='Mode de paiement utilisé', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Montant du paiement', max_digits=15, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes concernant ce paiement', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference',
            field=models.CharField(blank=True, help_text='Référence bancaire ou numéro de transaction', max_length=100, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='valide',
            field=models.BooleanField(default=False, help_text='Indique si le paiement est validé', verbose_name='Validé'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='valide_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant validé le paiement', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='actif',
            field=models.BooleanField(default=True, help_text='Indique si la prestation est active', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='code',
            field=models.CharField(db_index=True, help_text='Code unique de la prestation', max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='compte_produit',
            field=models.ForeignKey(blank=True, help_text='Compte comptable de produit associé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comptabilite.compte', verbose_name='Compte de produit'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée de la prestation', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='description_de',
            field=models.TextField(blank=True, help_text='Description détaillée de la prestation', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description détaillée de la prestation', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='description_fr',
            field=models.TextField(blank=True, help_text='Description détaillée de la prestation', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='description_it',
            field=models.TextField(blank=True, help_text='Description détaillée de la prestation', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='libelle',
            field=models.CharField(help_text='Libellé de la prestation', max_length=255, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='libelle_de',
            field=models.CharField(help_text='Libellé de la prestation', max_length=255, null=True, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='libelle_en',
            field=models.CharField(help_text='Libellé de la prestation', max_length=255, null=True, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='libelle_fr',
            field=models.CharField(help_text='Libellé de la prestation', max_length=255, null=True, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='libelle_it',
            field=models.CharField(help_text='Libellé de la prestation', max_length=255, null=True, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='prix_unitaire_ht',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix unitaire hors taxes par défaut', max_digits=10, null=True, verbose_name='Prix unitaire HT'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='soumis_tva',
            field=models.BooleanField(default=True, help_text='Indique si la prestation est soumise à TVA', verbose_name='Soumis à TVA'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='taux_horaire',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taux horaire de facturation', max_digits=10, null=True, verbose_name='Taux horaire'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='taux_tva_defaut',
            field=models.DecimalField(decimal_places=2, default=8.1, help_text='Taux de TVA appliqué par défaut', max_digits=5, verbose_name='Taux TVA par défaut'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='type_prestation',
            field=models.CharField(choices=[('COMPTABILITE', 'Comptabilité'), ('TVA', 'TVA'), ('SALAIRES', 'Salaires'), ('CONSEIL', 'Conseil'), ('AUDIT', 'Audit'), ('FISCALITE', 'Fiscalité'), ('JURIDIQUE', 'Juridique'), ('CREATION', 'Création entreprise'), ('AUTRE', 'Autre')], help_text='Catégorie de la prestation', max_length=20, verbose_name='Type de prestation'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='unite',
            field=models.CharField(default='heure', help_text='Unité de facturation (heure, jour, forfait, unité)', max_length=50, verbose_name='Unité'),
        ),
        migrations.AlterField(
            model_name='relance',
            name='date_echeance',
            field=models.DateField(help_text='Nouvelle date limite de paiement', verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='relance',
            name='date_envoi',
            field=models.DateField(blank=True, help_text="Date d'envoi de la relance", null=True, verbose_name="Date d'envoi"),
        ),
        migrations.AlterField(
            model_name='relance',
            name='date_relance',
            field=models.DateField(auto_now_add=True, help_text='Date de création de la relance', verbose_name='Date de relance'),
        ),
        migrations.AlterField(
            model_name='relance',
            name='envoyee',
            field=models.BooleanField(default=False, help_text='Indique si la relance a été envoyée', verbose_name='Envoyée'),
        ),
        migrations.AlterField(
            model_name='relance',
            name='facture',
            field=models.ForeignKey(help_text='Facture concernée par cette relance', on_delete=django.db.models.deletion.CASCADE, related_name='relances', to='facturation.facture', verbose_name='Facture'),
        ),
        migrations.AlterField(
            model_name='relance',
            name='fichier_pdf',
            field=models.FileField(blank=True, help_text='Fichier PDF de la relance', null=True, upload_to='factures/relances/', verbose_name='Fichier PDF'),
        ),
        migrations.AlterField(
            model_name='relance',
            name='montant_frais',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant des frais de relance', max_digits=10, verbose_name='Frais de relance'),
        ),
        migrations.AlterField(
            model_name='relance',
            name='montant_interets',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant des intérêts de retard', max_digits=10, verbose_name='Intérêts de retard'),
        ),
        migrations.AlterField(
            model_name='relance',
            name='niveau',
            field=models.IntegerField(choices=[(1, '1ère relance'), (2, '2ème relance'), (3, '3ème relance'), (4, 'Mise en demeure')], help_text='Niveau de la relance (1ère, 2ème, etc.)', verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='relance',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes concernant cette relance', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='date_facturation',
            field=models.DateField(blank=True, help_text='Date à laquelle ce temps a été facturé', null=True, verbose_name='Date de facturation'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='date_travail',
            field=models.DateField(db_index=True, help_text='Date à laquelle le travail a été effectué', verbose_name='Date du travail'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='description',
            field=models.TextField(help_text='Description du travail effectué', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='duree_minutes',
            field=models.IntegerField(help_text='Durée du travail en minutes', verbose_name='Durée (minutes)'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='facturable',
            field=models.BooleanField(default=True, help_text='Indique si ce temps est facturable au client', verbose_name='Facturable'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='facture',
            field=models.ForeignKey(blank=True, help_text='Facture associée si ce temps a été facturé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temps_factures', to='facturation.facture', verbose_name='Facture'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='heure_debut',
            field=models.TimeField(blank=True, help_text='Heure de début du travail', null=True, verbose_name='Heure de début'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='heure_fin',
            field=models.TimeField(blank=True, help_text='Heure de fin du travail', null=True, verbose_name='Heure de fin'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='mandat',
            field=models.ForeignKey(help_text='Mandat concerné par ce temps de travail', on_delete=django.db.models.deletion.CASCADE, related_name='temps_travail', to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, help_text='Montant hors taxes calculé', max_digits=10, verbose_name='Montant HT'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='notes_internes',
            field=models.TextField(blank=True, help_text='Notes internes non visibles sur la facture', verbose_name='Notes internes'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='prestation',
            field=models.ForeignKey(help_text='Type de prestation effectuée', on_delete=django.db.models.deletion.PROTECT, related_name='temps_travail', to='facturation.prestation', verbose_name='Prestation'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='taux_horaire',
            field=models.DecimalField(decimal_places=2, help_text='Taux horaire appliqué pour ce travail', max_digits=10, verbose_name='Taux horaire'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='utilisateur',
            field=models.ForeignKey(help_text='Collaborateur ayant effectué le travail', on_delete=django.db.models.deletion.PROTECT, related_name='temps_travail', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='valide',
            field=models.BooleanField(default=False, help_text='Indique si ce temps a été validé', verbose_name='Validé'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='valide_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant validé ce temps', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
    ]
