# Generated by Django 6.0.2 on 2026-02-13 12:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_parent_client_hierarchy'),
        ('facturation', '0006_timetracking_operation_alter_facture_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracking',
            name='coordonnees',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Position GPS lors de la saisie', null=True, srid=4326, verbose_name='Coordonnées'),
        ),
        migrations.CreateModel(
            name='ZoneGeographique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('nom', models.CharField(help_text='Nom de la zone géographique', max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, help_text='Description de la zone', verbose_name='Description')),
                ('geometrie', django.contrib.gis.db.models.fields.PolygonField(help_text='Polygone délimitant la zone', srid=4326, verbose_name='Géométrie')),
                ('couleur', models.CharField(default='#3388ff', help_text="Couleur d'affichage (hex)", max_length=7, verbose_name='Couleur')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Zone géographique',
                'verbose_name_plural': 'Zones géographiques',
                'db_table': 'zones_geographiques',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='timetracking',
            name='zone_geographique',
            field=models.ForeignKey(blank=True, help_text='Zone géographique associée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temps_travail', to='facturation.zonegeographique', verbose_name='Zone géographique'),
        ),
        migrations.CreateModel(
            name='TarifMandat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('taux_horaire', models.DecimalField(decimal_places=2, help_text='Taux horaire spécifique pour ce mandat/prestation', max_digits=10, verbose_name='Taux horaire')),
                ('prix_forfaitaire', models.DecimalField(blank=True, decimal_places=2, help_text='Prix forfaitaire optionnel', max_digits=10, null=True, verbose_name='Prix forfaitaire')),
                ('devise', models.CharField(default='CHF', help_text='Devise du tarif', max_length=3, verbose_name='Devise')),
                ('date_debut', models.DateField(blank=True, help_text='Début de validité du tarif', null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, help_text='Fin de validité du tarif', null=True, verbose_name='Date de fin')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('mandat', models.ForeignKey(help_text='Mandat concerné', on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='core.mandat', verbose_name='Mandat')),
                ('prestation', models.ForeignKey(help_text='Prestation concernée', on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_mandat', to='facturation.prestation', verbose_name='Prestation')),
            ],
            options={
                'verbose_name': 'Tarif mandat',
                'verbose_name_plural': 'Tarifs mandat',
                'db_table': 'tarifs_mandat',
                'ordering': ['mandat', 'prestation'],
                'unique_together': {('mandat', 'prestation')},
            },
        ),
    ]
