# Generated by Django 6.0.2 on 2026-02-13 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0007_add_zone_tarif_and_timetracking_geo'),
        ('projets', '0002_operation_m2m_assignation'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracking',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Position/lot lié dans le module projets', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temps_passes', to='projets.position', verbose_name='Position'),
        ),
    ]
