# Generated by Django 6.0.2 on 2026-02-23 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tache_add_assignes_m2m_prestation'),
        ('facturation', '0013_prestation_type_fk_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracking',
            name='tache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temps_travail', to='core.tache', verbose_name='Tâche'),
        ),
    ]
