# Generated by Django 6.0.3 on 2026-03-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0014_tache_add_assignes_m2m_prestation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('FACTURE', 'Facture'), ('DEVIS', 'Devis'), ('AVOIR', 'Avoir'), ('ACOMPTE', "Facture d'acompte")], default='FACTURE', help_text='Type de document (Facture, Avoir, Acompte)', max_length=20, verbose_name='Type de facture'),
        ),
    ]
