# Generated by Django 6.0.3 on 2026-03-12 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0016_categorie_temps_and_type_entree'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='timetracking',
            new_name='time_tracki_type_en_0e3488_idx',
            old_name='facturation_tt_type_user_date',
        ),
    ]
