# Generated by Django 6.0.3 on 2026-03-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_seed_reference_tables'),
        ('facturation', '0017_rename_facturation_tt_type_user_date_time_tracki_type_en_0e3488_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='types_mandats',
            field=models.ManyToManyField(blank=True, help_text='Types de mandats auxquels cette prestation est associée', related_name='prestations', to='core.typemandat', verbose_name='Types de mandats'),
        ),
    ]
