# Generated by Django 6.0.3 on 2026-04-03 00:39

import core.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0009_classecomptable_langue_saisie_compte_langue_saisie_and_more'),
        ('facturation', '0018_prestation_types_mandats_m2m'),
        ('projets', '0002_operation_langue_saisie_operationnote_langue_saisie_and_more'),
        ('tva', '0010_codetva_langue_saisie_configurationtva_langue_saisie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='facture',
            name='mentions_legales_generees',
            field=models.TextField(blank=True, help_text='Mentions légales générées automatiquement selon le régime fiscal', verbose_name='Mentions légales'),
        ),
        migrations.AddField(
            model_name='facture',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Position/lot du projet concerné', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='projets.position', verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='facture',
            name='type_operation_tva',
            field=models.CharField(choices=[('NATIONALE', 'Vente nationale'), ('EXPORT', 'Exportation'), ('INTRACOM', 'Intracommunautaire'), ('AUTOLIQUIDATION', 'Autoliquidation')], default='NATIONALE', help_text='Détermine le traitement TVA : nationale, export (0%), intracommunautaire, autoliquidation', max_length=20, verbose_name="Type d'opération TVA"),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='compte_produit',
            field=models.ForeignKey(blank=True, help_text='Compte comptable de produit (override la prestation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_facture', to='comptabilite.compte', verbose_name='Compte de produit'),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='prestation',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='relance',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='tarifmandat',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='zonegeographique',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='fichier_pdf',
            field=models.FileField(blank=True, help_text='Fichier PDF de la facture', max_length=500, null=True, storage=core.storage.S3InvoiceStorage(), upload_to='factures/pdf/', verbose_name='Fichier PDF'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text='Image du QR code généré', max_length=500, null=True, storage=core.storage.S3InvoiceStorage(), upload_to='factures/qr/', verbose_name='Image QR code'),
        ),
        migrations.AlterField(
            model_name='relance',
            name='fichier_pdf',
            field=models.FileField(blank=True, help_text='Fichier PDF de la relance', max_length=500, null=True, storage=core.storage.S3InvoiceStorage(), upload_to='factures/relances/', verbose_name='Fichier PDF'),
        ),
        migrations.CreateModel(
            name='MentionLegale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('langue_saisie', models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie')),
                ('code', models.CharField(help_text='Code technique (ex: TVA_NUMBER, PENALITES_RETARD, EXONERATION)', max_length=50, verbose_name='Code')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('texte', models.TextField(help_text='Supporte les variables : {tva_number}, {ide_number}, {raison_sociale}, {siret}, {rccm}', verbose_name='Texte de la mention')),
                ('type_document', models.CharField(choices=[('TOUS', 'Tous les documents'), ('FACTURE', 'Factures uniquement'), ('DEVIS', 'Devis uniquement'), ('AVOIR', 'Avoirs uniquement')], default='TOUS', max_length=20, verbose_name='Type de document')),
                ('obligatoire', models.BooleanField(default=True, help_text='Si True, la mention est ajoutée automatiquement au document', verbose_name='Obligatoire')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('regime_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions_legales', to='tva.regimefiscal', verbose_name='Régime fiscal')),
            ],
            options={
                'verbose_name': 'Mention légale',
                'verbose_name_plural': 'Mentions légales',
                'db_table': 'mentions_legales',
                'ordering': ['regime_fiscal', 'ordre'],
                'unique_together': {('regime_fiscal', 'code')},
            },
        ),
        migrations.CreateModel(
            name='NiveauRelance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('langue_saisie', models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie')),
                ('niveau', models.PositiveIntegerField(help_text='Numéro du niveau de relance (1, 2, 3, 4…)', verbose_name='Niveau')),
                ('libelle', models.CharField(help_text='Ex: 1ère relance, Mise en demeure, Sommation', max_length=100, verbose_name='Libellé')),
                ('delai_jours', models.PositiveIntegerField(help_text='Nouveau délai de paiement accordé en jours', verbose_name='Délai accordé (jours)')),
                ('frais', models.DecimalField(decimal_places=2, default=0, help_text='Montant des frais facturés pour cette relance', max_digits=10, verbose_name='Frais de relance')),
                ('interets', models.BooleanField(default=False, help_text='Appliquer des intérêts de retard à ce niveau', verbose_name='Intérêts moratoires')),
                ('taux_interet', models.DecimalField(decimal_places=2, default=0, help_text='Taux annuel des intérêts moratoires (ex: 5% en Suisse)', max_digits=5, verbose_name="Taux d'intérêt annuel (%)")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('regime_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux_relance', to='tva.regimefiscal', verbose_name='Régime fiscal')),
            ],
            options={
                'verbose_name': 'Niveau de relance',
                'verbose_name_plural': 'Niveaux de relance',
                'db_table': 'niveaux_relance',
                'ordering': ['regime_fiscal', 'niveau'],
                'unique_together': {('regime_fiscal', 'niveau')},
            },
        ),
    ]
