# Generated by Django 6.0.3 on 2026-03-19 20:22

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0019_lignefacture_compte_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='fichier_pdf',
            field=models.FileField(blank=True, help_text='Fichier PDF de la facture', max_length=500, null=True, storage=core.storage.S3InvoiceStorage(), upload_to='factures/pdf/', verbose_name='Fichier PDF'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text='Image du QR code généré', max_length=500, null=True, storage=core.storage.S3InvoiceStorage(), upload_to='factures/qr/', verbose_name='Image QR code'),
        ),
        migrations.AlterField(
            model_name='relance',
            name='fichier_pdf',
            field=models.FileField(blank=True, help_text='Fichier PDF de la relance', max_length=500, null=True, storage=core.storage.S3InvoiceStorage(), upload_to='factures/relances/', verbose_name='Fichier PDF'),
        ),
    ]
