# Generated by Django 6.0.3 on 2026-03-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0020_storage_s3'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='prestation',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='relance',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='tarifmandat',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='zonegeographique',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
    ]
