# Generated by Django 6.0.3 on 2026-03-24 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0021_langue_saisie'),
        ('projets', '0002_langue_saisie'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Position/lot du projet concerné', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='projets.position', verbose_name='Position'),
        ),
    ]
