# Generated by Django 5.2.8 on 2025-11-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='fonction_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='fonction_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='fonction_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='fonction_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='remarques_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='remarques_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='remarques_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='remarques_it',
            field=models.TextField(blank=True, null=True),
        ),
    ]
