# Generated by Django 6.0 on 2025-12-16 13:41

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0003_alter_certificatsalaire_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='nationalite',
            field=django_countries.fields.CountryField(default='CH', max_length=2, verbose_name='Nationalité'),
        ),
    ]
