# Generated by Django 6.0 on 2025-12-16 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0004_alter_employe_nationalite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='conjoint_travaille',
            field=models.BooleanField(default=False, help_text='Le conjoint exerce-t-il une activité lucrative?', verbose_name='Conjoint actif'),
        ),
        migrations.AddField(
            model_name='employe',
            name='date_validite_permis',
            field=models.DateField(blank=True, null=True, verbose_name='Validité du permis'),
        ),
        migrations.AddField(
            model_name='employe',
            name='revenus_conjoint',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pour détermination du barème IS', max_digits=12, null=True, verbose_name='Revenus annuels du conjoint'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='type_permis',
            field=models.CharField(blank=True, choices=[('B', 'Permis B - Autorisation de séjour'), ('C', "Permis C - Autorisation d'établissement"), ('L', 'Permis L - Autorisation de courte durée'), ('G', 'Permis G - Frontalier'), ('F', 'Permis F - Admission provisoire'), ('N', "Permis N - Requérant d'asile"), ('S', 'Permis S - Protection provisoire')], max_length=2),
        ),
        migrations.CreateModel(
            name='CertificatTravail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('type_certificat', models.CharField(choices=[('COMPLET', 'Certificat complet (qualifié)'), ('SIMPLE', 'Attestation de travail (simple)'), ('INTERMEDIAIRE', 'Certificat intermédiaire')], default='COMPLET', max_length=20, verbose_name='Type de certificat')),
                ('date_debut_emploi', models.DateField(verbose_name="Date de début d'emploi")),
                ('date_fin_emploi', models.DateField(blank=True, null=True, verbose_name="Date de fin d'emploi")),
                ('fonction_principale', models.CharField(max_length=150, verbose_name='Fonction principale')),
                ('departement', models.CharField(blank=True, max_length=100, verbose_name='Département')),
                ('taux_occupation', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name="Taux d'occupation (%)")),
                ('description_taches', models.TextField(blank=True, help_text='Description détaillée des principales responsabilités et tâches', verbose_name='Description des tâches')),
                ('evaluation_qualite_travail', models.IntegerField(blank=True, choices=[(1, 'Insuffisant'), (2, 'Satisfaisant'), (3, 'Bien'), (4, 'Très bien'), (5, 'Excellent')], null=True, verbose_name='Qualité du travail')),
                ('evaluation_quantite_travail', models.IntegerField(blank=True, choices=[(1, 'Insuffisant'), (2, 'Satisfaisant'), (3, 'Bien'), (4, 'Très bien'), (5, 'Excellent')], null=True, verbose_name='Quantité de travail')),
                ('evaluation_competences', models.IntegerField(blank=True, choices=[(1, 'Insuffisant'), (2, 'Satisfaisant'), (3, 'Bien'), (4, 'Très bien'), (5, 'Excellent')], null=True, verbose_name='Compétences professionnelles')),
                ('evaluation_comportement', models.IntegerField(blank=True, choices=[(1, 'Insuffisant'), (2, 'Satisfaisant'), (3, 'Bien'), (4, 'Très bien'), (5, 'Excellent')], null=True, verbose_name='Comportement')),
                ('evaluation_relations', models.IntegerField(blank=True, choices=[(1, 'Insuffisant'), (2, 'Satisfaisant'), (3, 'Bien'), (4, 'Très bien'), (5, 'Excellent')], null=True, verbose_name='Relations avec collègues/clients')),
                ('evaluation_autonomie', models.IntegerField(blank=True, choices=[(1, 'Insuffisant'), (2, 'Satisfaisant'), (3, 'Bien'), (4, 'Très bien'), (5, 'Excellent')], null=True, verbose_name='Autonomie et initiative')),
                ('texte_evaluation', models.TextField(blank=True, help_text='Évaluation rédigée des performances et du comportement', verbose_name="Texte d'évaluation")),
                ('motif_depart', models.CharField(blank=True, choices=[('DEMISSION', 'Démission'), ('FIN_CONTRAT', 'Fin de contrat'), ('LICENCIEMENT', 'Licenciement'), ('LICENCIEMENT_ECO', 'Licenciement économique'), ('RETRAITE', 'Retraite'), ('ACCORD_MUTUEL', "Résiliation d'un commun accord"), ('DECES', 'Décès'), ('', 'Non spécifié')], max_length=20, verbose_name='Motif de départ')),
                ('formule_fin', models.TextField(blank=True, help_text="Remerciements et vœux pour l'avenir", verbose_name='Formule de fin')),
                ('formations_suivies', models.TextField(blank=True, help_text="Formations internes ou externes suivies durant l'emploi", verbose_name='Formations suivies')),
                ('projets_speciaux', models.TextField(blank=True, help_text='Projets particuliers ou missions spéciales', verbose_name='Projets spéciaux')),
                ('date_demande', models.DateField(blank=True, null=True, verbose_name='Date de demande')),
                ('date_emission', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='salaires/certificats_travail/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('emis_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificats_travail_emis', to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats_travail', to='salaires.employe')),
            ],
            options={
                'verbose_name': 'Certificat de travail',
                'verbose_name_plural': 'Certificats de travail',
                'db_table': 'certificats_travail',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='EnfantEmploye',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('type_allocation', models.CharField(choices=[('NAISSANCE', 'Allocation de naissance'), ('ENFANT', 'Allocation pour enfant (0-16 ans)'), ('FORMATION', 'Allocation de formation (16-25 ans)'), ('AUCUNE', "Pas d'allocation")], default='ENFANT', max_length=20, verbose_name="Type d'allocation")),
                ('en_formation', models.BooleanField(default=False, help_text="Suit une formation (apprentissage, études) - pour allocation formation jusqu'à 25 ans", verbose_name='En formation')),
                ('date_fin_formation', models.DateField(blank=True, null=True, verbose_name='Fin de formation prévue')),
                ('garde_partagee', models.BooleanField(default=False, help_text="L'enfant est en garde partagée avec l'autre parent", verbose_name='Garde partagée')),
                ('pourcentage_garde', models.IntegerField(default=100, help_text='Pourcentage de garde (100 si garde complète, 50 si partagée)', verbose_name='% de garde')),
                ('autre_parent_recoit_allocation', models.BooleanField(default=False, help_text="L'autre parent perçoit-il déjà des allocations pour cet enfant?", verbose_name='Autre parent reçoit allocation')),
                ('montant_allocation', models.DecimalField(blank=True, decimal_places=2, help_text="Montant mensuel de l'allocation (si différent du standard)", max_digits=8, null=True, verbose_name='Montant mensuel')),
                ('remarques', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='salaires.employe')),
            ],
            options={
                'verbose_name': 'Enfant',
                'verbose_name_plural': 'Enfants',
                'db_table': 'enfants_employes',
                'ordering': ['date_naissance'],
            },
        ),
    ]
