# Generated by Django 6.0.2 on 2026-02-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0004_employe_devise_salaire_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='salaire_brut_mensuel',
            field=models.DecimalField(decimal_places=2, help_text='Salaire brut mensuel', max_digits=10, verbose_name='Salaire brut mensuel'),
        ),
    ]
