# Generated by Django 6.0.2 on 2026-02-11 16:24

import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0014_alter_classecomptable_description_and_more'),
        ('core', '0017_remove_collaborateurfiduciaire_unique_collaborateur_mandat_and_more'),
        ('salaires', '0008_declaration_cotisations_enhanced'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatsalaire',
            options={'ordering': ['-annee'], 'verbose_name': 'Certificat de salaire', 'verbose_name_plural': 'Certificats de salaire'},
        ),
        migrations.AlterModelOptions(
            name='declarationcotisations',
            options={'ordering': ['-annee', '-periode_fin', 'organisme'], 'verbose_name': 'Déclaration de cotisations', 'verbose_name_plural': 'Déclarations de cotisations'},
        ),
        migrations.AddField(
            model_name='declarationcotisationsligne',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='declarationcotisationsligne',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='certificatsalaire',
            name='ac_annuel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='[Obsolète] Inclus dans chiffre_9_cotisations', max_digits=10, verbose_name='AC annuel (legacy)'),
        ),
        migrations.AlterField(
            model_name='certificatsalaire',
            name='allocations_familiales_annuel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='[Obsolète] Les allocations ne figurent pas sur le formulaire 11', max_digits=10, verbose_name='Allocations familiales annuelles (legacy)'),
        ),
        migrations.AlterField(
            model_name='certificatsalaire',
            name='annee',
            field=models.IntegerField(db_index=True, help_text='Année fiscale du certificat', verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='certificatsalaire',
            name='avs_annuel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='[Obsolète] Utiliser chiffre_9_cotisations', max_digits=10, verbose_name='AVS annuel (legacy)'),
        ),
        migrations.AlterField(
            model_name='certificatsalaire',
            name='date_debut',
            field=models.DateField(help_text="Début de la période d'emploi pour cette année (Section C)", verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='certificatsalaire',
            name='date_fin',
            field=models.DateField(help_text="Fin de la période d'emploi pour cette année (Section C)", verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='certificatsalaire',
            name='date_generation',
            field=models.DateTimeField(auto_now_add=True, help_text='Date de création du certificat', verbose_name='Date de génération'),
        ),
        migrations.AlterField(
            model_name='certificatsalaire',
            name='employe',
            field=models.ForeignKey(help_text='Employé concerné', on_delete=django.db.models.deletion.CASCADE, related_name='certificats_salaire', to='salaires.employe', verbose_name='Employé'),
        ),
        migrations.AlterField(
            model_name='certificatsalaire',
            name='fichier_pdf',
            field=models.FileField(blank=True, help_text='Certificat de salaire au format PDF', null=True, upload_to='salaires/certificats/', verbose_name='Fichier PDF'),
        ),
        migrations.AlterField(
            model_name='certificatsalaire',
            name='frais_deplacement',
            field=models.DecimalField(decimal_places=2, default=0, help_text='[Obsolète] Utiliser chiffre_12_transport', max_digits=10, verbose_name='Frais de déplacement (legacy)'),
        ),
        migrations.AlterField(
            model_name='certificatsalaire',
            name='frais_repas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='[Obsolète] Utiliser chiffre_13_*', max_digits=10, verbose_name='Frais de repas (legacy)'),
        ),
        migrations.AlterField(
            model_name='certificatsalaire',
            name='genere_par',
            field=models.ForeignKey(help_text='Utilisateur ayant généré le certificat', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Généré par'),
        ),
        migrations.AlterField(
            model_name='certificatsalaire',
            name='impot_source_annuel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total impôt à la source retenu (info uniquement, pas sur formulaire 11)', max_digits=10, verbose_name='Impôt à la source annuel'),
        ),
        migrations.AlterField(
            model_name='certificatsalaire',
            name='lpp_annuel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='[Obsolète] Utiliser chiffre_10_1_lpp_ordinaire', max_digits=10, verbose_name='LPP annuel (legacy)'),
        ),
        migrations.AlterField(
            model_name='certificatsalaire',
            name='primes_annuelles',
            field=models.DecimalField(decimal_places=2, default=0, help_text='[Obsolète] Inclus dans chiffre_3_irregulier', max_digits=10, verbose_name='Primes annuelles (legacy)'),
        ),
        migrations.AlterField(
            model_name='certificatsalaire',
            name='salaire_brut_annuel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='[Obsolète] Utiliser chiffre_1_salaire', max_digits=12, verbose_name='Salaire brut annuel (legacy)'),
        ),
        migrations.AlterField(
            model_name='certificatsalaire',
            name='treizieme_salaire_annuel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='[Obsolète] Inclus dans chiffre_3_irregulier', max_digits=10, verbose_name='13ème salaire annuel (legacy)'),
        ),
        migrations.AlterField(
            model_name='declarationcotisations',
            name='date_paiement',
            field=models.DateField(blank=True, help_text='Date effective du paiement', null=True, verbose_name='Date de paiement'),
        ),
        migrations.AlterField(
            model_name='declarationcotisations',
            name='fichier_declaration',
            field=models.FileField(blank=True, help_text='Document de déclaration généré', null=True, upload_to='salaires/declarations/', verbose_name='Fichier déclaration'),
        ),
        migrations.AlterField(
            model_name='declarationcotisations',
            name='numero_reference',
            field=models.CharField(blank=True, help_text="Référence attribuée par l'organisme", max_length=50, verbose_name='Numéro de référence'),
        ),
        migrations.AlterField(
            model_name='declarationcotisations',
            name='periode_debut',
            field=models.DateField(help_text='Premier jour de la période déclarée', verbose_name='Début de période'),
        ),
        migrations.AlterField(
            model_name='declarationcotisations',
            name='periode_fin',
            field=models.DateField(help_text='Dernier jour de la période déclarée', verbose_name='Fin de période'),
        ),
        migrations.AlterField(
            model_name='declarationcotisationsligne',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='declarationcotisationsligne',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='declarationcotisationsligne',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='adresse',
            field=models.ForeignKey(help_text='Adresse de domicile', on_delete=django.db.models.deletion.PROTECT, related_name='employes', to='core.adresse', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='banque',
            field=models.CharField(blank=True, help_text="Nom de l'établissement bancaire", max_length=100, verbose_name='Banque'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='config_cotisations',
            field=models.JSONField(blank=True, default=dict, help_text='Paramétrage des cotisations sociales au format JSON', verbose_name='Configuration cotisations'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_entree',
            field=models.DateField(db_index=True, help_text='Date de début du contrat', verbose_name="Date d'entrée"),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_fin_periode_essai',
            field=models.DateField(blank=True, help_text="Date de fin de la période d'essai", null=True, verbose_name="Fin période d'essai"),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_naissance',
            field=models.DateField(help_text="Date de naissance de l'employé", verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_sortie',
            field=models.DateField(blank=True, db_index=True, help_text='Date de fin du contrat', null=True, verbose_name='Date de sortie'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='departement',
            field=models.CharField(blank=True, help_text='Service ou département', max_length=100, verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(blank=True, help_text='Adresse email personnelle', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='etat_civil',
            field=models.CharField(choices=[('CELIBATAIRE', 'Célibataire'), ('MARIE', 'Marié(e)'), ('DIVORCE', 'Divorcé(e)'), ('VEUF', 'Veuf/Veuve'), ('SEPARE', 'Séparé(e)'), ('PARTENARIAT', 'Partenariat enregistré')], help_text='Situation matrimoniale', max_length=20, verbose_name='État civil'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='fonction',
            field=models.CharField(help_text='Intitulé du poste', max_length=100, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='fonction_de',
            field=models.CharField(help_text='Intitulé du poste', max_length=100, null=True, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='fonction_en',
            field=models.CharField(help_text='Intitulé du poste', max_length=100, null=True, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='fonction_fr',
            field=models.CharField(help_text='Intitulé du poste', max_length=100, null=True, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='fonction_it',
            field=models.CharField(help_text='Intitulé du poste', max_length=100, null=True, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='iban',
            field=models.CharField(blank=True, help_text='Numéro IBAN pour le versement du salaire', max_length=34, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='jours_vacances_annuel',
            field=models.IntegerField(default=20, help_text='Nombre de jours de vacances annuels', verbose_name='Jours de vacances'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='lieu_naissance',
            field=models.CharField(blank=True, help_text='Ville et pays de naissance', max_length=100, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='mandat',
            field=models.ForeignKey(help_text='Mandat employeur', on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='core.mandat', verbose_name='Mandat'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='matricule',
            field=models.CharField(db_index=True, help_text="Numéro d'identification interne", max_length=50, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='mobile',
            field=models.CharField(blank=True, help_text='Numéro de téléphone portable', max_length=20, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='montant_13eme',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant du 13ème salaire (si différent du salaire mensuel)', max_digits=10, null=True, verbose_name='Montant 13ème'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='nationalite',
            field=django_countries.fields.CountryField(default='CH', help_text="Nationalité de l'employé", max_length=2, verbose_name='Nationalité'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='nom',
            field=models.CharField(db_index=True, help_text='Nom de famille', max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='nom_naissance',
            field=models.CharField(blank=True, help_text='Nom de famille à la naissance (si différent)', max_length=100, verbose_name='Nom de naissance'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='nombre_enfants',
            field=models.IntegerField(default=0, help_text="Nombre d'enfants à charge", verbose_name="Nombre d'enfants"),
        ),
        migrations.AlterField(
            model_name='employe',
            name='nombre_heures_semaine',
            field=models.DecimalField(decimal_places=2, default=42, help_text="Nombre d'heures de travail hebdomadaires", max_digits=5, verbose_name='Heures par semaine'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='prenom',
            field=models.CharField(help_text='Prénom(s)', max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='remarques',
            field=models.TextField(blank=True, help_text='Notes et observations', verbose_name='Remarques'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='remarques_de',
            field=models.TextField(blank=True, help_text='Notes et observations', null=True, verbose_name='Remarques'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='remarques_en',
            field=models.TextField(blank=True, help_text='Notes et observations', null=True, verbose_name='Remarques'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='remarques_fr',
            field=models.TextField(blank=True, help_text='Notes et observations', null=True, verbose_name='Remarques'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='remarques_it',
            field=models.TextField(blank=True, help_text='Notes et observations', null=True, verbose_name='Remarques'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='salaire_brut_mensuel',
            field=models.DecimalField(decimal_places=2, help_text='Salaire brut mensuel en CHF', max_digits=10, verbose_name='Salaire brut mensuel'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='salaire_horaire',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salaire horaire en CHF (si applicable)', max_digits=10, null=True, verbose_name='Salaire horaire'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('X', 'Autre')], help_text="Sexe de l'employé", max_length=1, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('CONGE', 'En congé'), ('DEMISSION', 'Démission'), ('LICENCIE', 'Licencié'), ('RETRAITE', 'Retraité')], db_index=True, default='ACTIF', help_text="Statut actuel de l'employé", max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='taux_occupation',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Taux en % (100 = temps plein)', max_digits=5, verbose_name="Taux d'occupation"),
        ),
        migrations.AlterField(
            model_name='employe',
            name='telephone',
            field=models.CharField(blank=True, help_text='Numéro de téléphone fixe', max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='treizieme_salaire',
            field=models.BooleanField(default=True, help_text="L'employé bénéficie-t-il d'un 13ème salaire ?", verbose_name='13ème salaire'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'Contrat durée indéterminée'), ('CDD', 'Contrat durée déterminée'), ('APPRENTI', 'Apprentissage'), ('STAGE', 'Stage'), ('TEMPORAIRE', 'Temporaire')], help_text='Nature du contrat de travail', max_length=20, verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='ac_employe',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Assurance chômage employé en CHF', max_digits=10, verbose_name='AC'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='ac_employeur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Part patronale assurance chômage en CHF', max_digits=10, verbose_name='AC employeur'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='ac_supp_employe',
            field=models.DecimalField(decimal_places=2, default=0, help_text="AC supplémentaire (salaires > 148'200) en CHF", max_digits=10, verbose_name='AC supp.'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='af_employeur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Allocations familiales (charge patronale) en CHF', max_digits=10, verbose_name='AF employeur'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='allocations_familiales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Allocations familiales en CHF', max_digits=10, verbose_name='Allocations familiales'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='annee',
            field=models.IntegerField(help_text='Année de la fiche', verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='autres_allocations',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Autres allocations en CHF', max_digits=10, verbose_name='Autres allocations'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='autres_deductions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Autres retenues en CHF', max_digits=10, verbose_name='Autres déductions'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='avance_salaire',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Retenue pour avance consentie en CHF', max_digits=10, verbose_name='Avance sur salaire'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='avs_employe',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cotisation AVS/AI/APG employé en CHF', max_digits=10, verbose_name='AVS/AI/APG'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='avs_employeur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Part patronale AVS/AI/APG en CHF', max_digits=10, verbose_name='AVS employeur'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='cout_total_employeur',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Coût complet pour l'employeur en CHF", max_digits=10, verbose_name='Coût total employeur'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='date_paiement',
            field=models.DateField(blank=True, help_text='Date effective du paiement', null=True, verbose_name='Date de paiement'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='date_validation',
            field=models.DateTimeField(blank=True, help_text='Date et heure de validation', null=True, verbose_name='Date de validation'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='ecriture_comptable',
            field=models.ForeignKey(blank=True, help_text='Pièce comptable associée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_salaire', to='comptabilite.piececomptable', verbose_name='Pièce comptable'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='employe',
            field=models.ForeignKey(help_text='Employé concerné', on_delete=django.db.models.deletion.CASCADE, related_name='fiches_salaire', to='salaires.employe', verbose_name='Employé'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='fichier_pdf',
            field=models.FileField(blank=True, help_text='Fiche de salaire au format PDF', null=True, upload_to='salaires/fiches/', verbose_name='Fichier PDF'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='heures_supp_montant',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rémunération des heures supplémentaires en CHF', max_digits=10, verbose_name='Montant heures supp.'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='heures_supplementaires',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Heures supplémentaires effectuées', max_digits=6, verbose_name='Heures supplémentaires'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='heures_travaillees',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Nombre d'heures travaillées", max_digits=6, verbose_name='Heures travaillées'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='ijm_employe',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Indemnités journalières maladie employé en CHF', max_digits=10, verbose_name='IJM'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='impot_source',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Retenue d'impôt à la source en CHF", max_digits=10, verbose_name='Impôt à la source'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='indemnites',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Indemnités diverses en CHF', max_digits=10, verbose_name='Indemnités'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='jours_absence',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Jours d'absence (hors vacances et maladie)", max_digits=5, verbose_name="Jours d'absence"),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='jours_maladie',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Jours d'absence pour maladie", max_digits=5, verbose_name='Jours de maladie'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='jours_travailles',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Nombre de jours effectivement travaillés', max_digits=5, verbose_name='Jours travaillés'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='jours_vacances',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Jours de vacances pris', max_digits=5, verbose_name='Jours de vacances'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='laa_employe',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Assurance accidents employé en CHF', max_digits=10, verbose_name='LAA'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='laa_employeur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Part patronale assurance accidents en CHF', max_digits=10, verbose_name='LAA employeur'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='laac_employe',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Assurance accidents complémentaire en CHF', max_digits=10, verbose_name='LAAC'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='lpp_employe',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cotisation 2ème pilier employé en CHF', max_digits=10, verbose_name='LPP'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='lpp_employeur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Part patronale 2ème pilier en CHF', max_digits=10, verbose_name='LPP employeur'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='mois',
            field=models.IntegerField(help_text='Mois de la fiche (1-12)', verbose_name='Mois'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='numero_fiche',
            field=models.CharField(db_index=True, help_text='Identifiant unique de la fiche', max_length=50, unique=True, verbose_name='Numéro de fiche'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='periode',
            field=models.DateField(db_index=True, help_text='Premier jour du mois concerné', verbose_name='Période'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='primes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Primes et bonus en CHF', max_digits=10, verbose_name='Primes'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='remarques',
            field=models.TextField(blank=True, help_text='Notes et observations', verbose_name='Remarques'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='saisie_salaire',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Retenue pour saisie de salaire en CHF', max_digits=10, verbose_name='Saisie sur salaire'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='salaire_base',
            field=models.DecimalField(decimal_places=2, help_text='Salaire mensuel de base en CHF', max_digits=10, verbose_name='Salaire de base'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='salaire_brut_total',
            field=models.DecimalField(decimal_places=2, help_text='Total du salaire brut en CHF', max_digits=10, verbose_name='Salaire brut total'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='salaire_net',
            field=models.DecimalField(decimal_places=2, help_text='Salaire net à payer en CHF', max_digits=10, verbose_name='Salaire net'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validée'), ('PAYE', 'Payée'), ('COMPTABILISE', 'Comptabilisée')], db_index=True, default='BROUILLON', help_text='État de la fiche de salaire', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='total_charges_patronales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total des charges employeur en CHF', max_digits=10, verbose_name='Total charges patronales'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='total_cotisations_employe',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total des cotisations salariales en CHF', max_digits=10, verbose_name='Total cotisations employé'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total de toutes les déductions en CHF', max_digits=10, verbose_name='Total déductions'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='treizieme_mois',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Part du 13ème salaire versée ce mois', max_digits=10, verbose_name='13ème mois'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='valide_par',
            field=models.ForeignKey(help_text='Utilisateur ayant validé la fiche', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AlterField(
            model_name='tauxcotisation',
            name='actif',
            field=models.BooleanField(default=True, help_text='Indique si ce taux est actuellement applicable', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='tauxcotisation',
            name='date_debut',
            field=models.DateField(help_text="Date d'entrée en vigueur", verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='tauxcotisation',
            name='date_fin',
            field=models.DateField(blank=True, help_text='Date de fin de validité', null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='tauxcotisation',
            name='libelle',
            field=models.CharField(help_text='Description de la cotisation', max_length=100, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='tauxcotisation',
            name='repartition',
            field=models.CharField(choices=[('EMPLOYEUR', 'Employeur uniquement'), ('EMPLOYE', 'Employé uniquement'), ('PARTAGE', 'Partagé employeur/employé')], help_text='Mode de répartition de la cotisation', max_length=20, verbose_name='Répartition'),
        ),
        migrations.AlterField(
            model_name='tauxcotisation',
            name='salaire_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Plafond de salaire soumis en CHF', max_digits=10, null=True, verbose_name='Salaire maximum'),
        ),
        migrations.AlterField(
            model_name='tauxcotisation',
            name='salaire_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salaire minimum soumis à cotisation en CHF', max_digits=10, null=True, verbose_name='Salaire minimum'),
        ),
        migrations.AlterField(
            model_name='tauxcotisation',
            name='taux_employe',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Part employé en %', max_digits=5, verbose_name='Taux employé'),
        ),
        migrations.AlterField(
            model_name='tauxcotisation',
            name='taux_employeur',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Part employeur en %', max_digits=5, verbose_name='Taux employeur'),
        ),
        migrations.AlterField(
            model_name='tauxcotisation',
            name='taux_total',
            field=models.DecimalField(decimal_places=4, help_text='Taux total en % (employeur + employé)', max_digits=5, verbose_name='Taux total'),
        ),
        migrations.AlterField(
            model_name='tauxcotisation',
            name='type_cotisation',
            field=models.CharField(choices=[('AVS', 'AVS/AI/APG'), ('AC', 'Assurance chômage'), ('AC_SUPP', "AC supplément (>148'200)"), ('LPP', 'LPP (2e pilier)'), ('LAA', 'LAA Accidents'), ('LAAC', 'LAAC Accidents complémentaire'), ('IJM', 'Indemnités journalières maladie'), ('AF', 'Allocations familiales')], help_text='Nature de la cotisation sociale', max_length=20, unique=True, verbose_name='Type de cotisation'),
        ),
        migrations.AlterUniqueTogether(
            name='declarationcotisations',
            unique_together={('mandat', 'organisme', 'annee', 'mois', 'trimestre')},
        ),
    ]
