# Generated by Django 6.0.2 on 2026-02-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0010_salaires_regime_devise_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatsalaire',
            name='chiffre_2_1_repas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valeur des repas gratuits', max_digits=10, verbose_name='2.1 Repas'),
        ),
        migrations.AlterField(
            model_name='declarationcotisations',
            name='cotisation_ac_supp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='AC sur salaires dépassant le seuil plafond', max_digits=12, verbose_name='AC supplémentaire'),
        ),
        migrations.AlterField(
            model_name='declarationcotisations',
            name='masse_salariale_brute',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total des salaires bruts', max_digits=15, verbose_name='Masse salariale brute'),
        ),
        migrations.AlterField(
            model_name='declarationcotisations',
            name='masse_salariale_soumise',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total des salaires soumis à cotisation', max_digits=15, verbose_name='Masse salariale soumise'),
        ),
        migrations.AlterField(
            model_name='declarationcotisations',
            name='montant_cotisations',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total des cotisations dues', max_digits=12, verbose_name='Montant total'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='salaire_horaire',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salaire horaire (si applicable)', max_digits=10, null=True, verbose_name='Salaire horaire'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='ac_employe',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Assurance chômage employé', max_digits=10, verbose_name='AC'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='ac_employeur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Part patronale assurance chômage', max_digits=10, verbose_name='AC employeur'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='ac_supp_employe',
            field=models.DecimalField(decimal_places=2, default=0, help_text='AC supplémentaire (salaires > seuil plafond)', max_digits=10, verbose_name='AC supp.'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='af_employeur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Allocations familiales (charge patronale)', max_digits=10, verbose_name='AF employeur'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='allocations_familiales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Allocations familiales', max_digits=10, verbose_name='Allocations familiales'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='autres_allocations',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Autres allocations', max_digits=10, verbose_name='Autres allocations'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='autres_deductions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Autres retenues', max_digits=10, verbose_name='Autres déductions'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='avance_salaire',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Retenue pour avance consentie', max_digits=10, verbose_name='Avance sur salaire'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='avs_employe',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cotisation AVS/AI/APG employé', max_digits=10, verbose_name='AVS/AI/APG'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='avs_employeur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Part patronale AVS/AI/APG', max_digits=10, verbose_name='AVS employeur'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='cout_total_employeur',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Coût complet pour l'employeur", max_digits=10, verbose_name='Coût total employeur'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='heures_supp_montant',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rémunération des heures supplémentaires', max_digits=10, verbose_name='Montant heures supp.'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='ijm_employe',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Indemnités journalières maladie employé', max_digits=10, verbose_name='IJM'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='impot_source',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Retenue d'impôt à la source", max_digits=10, verbose_name='Impôt à la source'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='indemnites',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Indemnités diverses', max_digits=10, verbose_name='Indemnités'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='laa_employe',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Assurance accidents employé', max_digits=10, verbose_name='LAA'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='laa_employeur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Part patronale assurance accidents', max_digits=10, verbose_name='LAA employeur'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='laac_employe',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Assurance accidents complémentaire', max_digits=10, verbose_name='LAAC'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='lpp_employe',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cotisation 2ème pilier employé', max_digits=10, verbose_name='LPP'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='lpp_employeur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Part patronale 2ème pilier', max_digits=10, verbose_name='LPP employeur'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='primes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Primes et bonus', max_digits=10, verbose_name='Primes'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='saisie_salaire',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Retenue pour saisie de salaire', max_digits=10, verbose_name='Saisie sur salaire'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='salaire_base',
            field=models.DecimalField(decimal_places=2, help_text='Salaire mensuel de base', max_digits=10, verbose_name='Salaire de base'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='salaire_brut_total',
            field=models.DecimalField(decimal_places=2, help_text='Total du salaire brut', max_digits=10, verbose_name='Salaire brut total'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='salaire_net',
            field=models.DecimalField(decimal_places=2, help_text='Salaire net à payer', max_digits=10, verbose_name='Salaire net'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='total_charges_patronales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total des charges employeur', max_digits=10, verbose_name='Total charges patronales'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='total_cotisations_employe',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total des cotisations salariales', max_digits=10, verbose_name='Total cotisations employé'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total de toutes les déductions', max_digits=10, verbose_name='Total déductions'),
        ),
        migrations.AlterField(
            model_name='tauxcotisation',
            name='salaire_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Plafond de salaire soumis', max_digits=10, null=True, verbose_name='Salaire maximum'),
        ),
        migrations.AlterField(
            model_name='tauxcotisation',
            name='salaire_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salaire minimum soumis à cotisation', max_digits=10, null=True, verbose_name='Salaire minimum'),
        ),
    ]
