# Generated by Django 6.0.3 on 2026-03-19 20:22

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0011_alter_certificatsalaire_chiffre_2_1_repas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatsalaire',
            name='fichier_pdf',
            field=models.FileField(blank=True, help_text='Certificat de salaire au format PDF', max_length=500, null=True, storage=core.storage.S3SalairesStorage(), upload_to='salaires/certificats/', verbose_name='Fichier PDF'),
        ),
        migrations.AlterField(
            model_name='certificattravail',
            name='fichier_pdf',
            field=models.FileField(blank=True, max_length=500, null=True, storage=core.storage.S3SalairesStorage(), upload_to='salaires/certificats_travail/'),
        ),
        migrations.AlterField(
            model_name='declarationcotisations',
            name='fichier_declaration',
            field=models.FileField(blank=True, help_text='Document de déclaration généré', max_length=500, null=True, storage=core.storage.S3SalairesStorage(), upload_to='salaires/declarations/', verbose_name='Fichier déclaration'),
        ),
        migrations.AlterField(
            model_name='fichesalaire',
            name='fichier_pdf',
            field=models.FileField(blank=True, help_text='Fiche de salaire au format PDF', max_length=500, null=True, storage=core.storage.S3SalairesStorage(), upload_to='salaires/fiches/', verbose_name='Fichier PDF'),
        ),
    ]
