# Generated by Django 6.0.3 on 2026-03-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0012_storage_s3'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatsalaire',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='certificattravail',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='declarationcotisations',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='declarationcotisationsligne',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='employe',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='enfantemploye',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='fichesalaire',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
        migrations.AddField(
            model_name='tauxcotisation',
            name='langue_saisie',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie'),
        ),
    ]
