# Generated by Django 6.0.3 on 2026-03-24 22:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0013_langue_saisie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='canton_imposition',
            field=models.CharField(blank=True, help_text='Canton pour le barème impôt source (ex: GE, VD, ZH)', max_length=2, verbose_name='Canton imposition IS'),
        ),
        migrations.AddField(
            model_name='employe',
            name='eglise_is',
            field=models.BooleanField(default=False, help_text='Affecte le barème IS dans certains cantons', verbose_name='Impôt ecclésiastique'),
        ),
        migrations.AddField(
            model_name='employe',
            name='nombre_enfants_is',
            field=models.IntegerField(default=0, help_text="Nombre d'enfants pour le calcul du barème IS", verbose_name="Nombre d'enfants IS"),
        ),
        migrations.AddField(
            model_name='employe',
            name='numero_securite_sociale',
            field=models.CharField(blank=True, help_text='Numéro universel (N° AVS en CH, N° sécu en FR, INPS au Mali, etc.)', max_length=50, verbose_name='N° sécurité sociale'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='barreme_is',
            field=models.CharField(blank=True, help_text='Ex: A0, A1, B0, B1, C0, C1, etc.', max_length=10, verbose_name='Barème IS'),
        ),
        migrations.CreateModel(
            name='LigneCotisationFiche',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('langue_saisie', models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie')),
                ('libelle', models.CharField(blank=True, help_text='Auto-rempli depuis TauxCotisation si vide', max_length=200, verbose_name='Libellé')),
                ('base_calcul', models.DecimalField(decimal_places=2, default=0, help_text='Salaire soumis à cette cotisation', max_digits=15, verbose_name='Base de calcul')),
                ('taux_employe', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Taux employé (%)')),
                ('taux_employeur', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Taux employeur (%)')),
                ('montant_employe', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant employé')),
                ('montant_employeur', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant employeur')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_cotisations', to='salaires.fichesalaire', verbose_name='Fiche de salaire')),
                ('taux_cotisation', models.ForeignKey(help_text='Référence au taux configuré (type, régime, taux)', on_delete=django.db.models.deletion.PROTECT, related_name='lignes_fiches', to='salaires.tauxcotisation', verbose_name='Type de cotisation')),
            ],
            options={
                'verbose_name': 'Ligne de cotisation',
                'verbose_name_plural': 'Lignes de cotisation',
                'db_table': 'lignes_cotisation_fiche',
                'ordering': ['fiche', 'ordre'],
                'indexes': [models.Index(fields=['fiche', 'taux_cotisation'], name='lignes_coti_fiche_i_1d4a15_idx')],
            },
        ),
    ]
