# Generated by merge script
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("salaires", "0013_employe_canton_imposition_employe_eglise_is_and_more"),
        ("salaires", "0014_employe_canton_imposition_employe_eglise_is_and_more"),
    ]

    operations = [
    ]
