# Generated by Django 6.0.3 on 2026-04-03 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0014_employe_canton_imposition_employe_eglise_is_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationFamiliale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('langue_saisie', models.CharField(blank=True, db_index=True, default='', help_text='Langue dans laquelle les données ont été saisies (auto-détecté)', max_length=5, verbose_name='Langue de saisie')),
                ('canton', models.CharField(help_text="Code canton (GE, VD, ZH…) ou 'DEFAULT' pour le minimum fédéral", max_length=5, verbose_name='Canton / Région')),
                ('type_allocation', models.CharField(choices=[('ENFANT', 'Allocation pour enfant'), ('FORMATION', 'Allocation de formation'), ('NAISSANCE', 'Allocation de naissance'), ('ADOPTION', "Allocation d'adoption")], max_length=20, verbose_name="Type d'allocation")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant mensuel')),
                ('date_debut', models.DateField(help_text='Date de début de validité de ce barème', verbose_name='Valide dès')),
                ('date_fin', models.DateField(blank=True, help_text='Laisser vide si toujours en vigueur', null=True, verbose_name="Valide jusqu'au")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Allocation familiale',
                'verbose_name_plural': 'Allocations familiales',
                'db_table': 'allocations_familiales',
                'ordering': ['canton', 'type_allocation', '-date_debut'],
                'unique_together': {('canton', 'type_allocation', 'date_debut')},
            },
        ),
    ]
