# Generated by Django 6.0.3 on 2026-04-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0015_allocationfamiliale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tauxcotisation',
            name='type_cotisation',
            field=models.CharField(choices=[('AVS', 'AVS/AI/APG'), ('AC', 'Assurance chômage'), ('AC_SUPP', 'AC supplément (>seuil plafond)'), ('LPP', 'LPP (2e pilier)'), ('LAA', 'LAA Accidents'), ('LAAC', 'LAAC Accidents complémentaire'), ('IJM', 'Indemnités journalières maladie'), ('AF', 'Allocations familiales'), ('CNPS_VIE', 'CNPS Assurance vieillesse'), ('CNPS_AF', 'CNPS Allocations familiales'), ('CNPS_AT', 'CNPS Accidents du travail'), ('CSS', 'CSS Sécurité sociale'), ('IPRES_GEN', 'IPRES Régime général'), ('IPRES_CAD', 'IPRES Régime cadre'), ('IPM', 'IPM Maladie'), ('CFCE', 'CFCE Formation professionnelle'), ('CNPS_CI_RET', 'CNPS-CI Retraite'), ('CNPS_CI_PF', 'CNPS-CI Prestations familiales'), ('CNPS_CI_AT', 'CNPS-CI Accidents du travail'), ('CMU_CI', 'CMU Couverture maladie universelle'), ('FNE', 'FNE Emploi'), ('INPS_RET', 'INPS Retraite'), ('INPS_PF', 'INPS Prestations familiales'), ('INPS_AT', 'INPS Accidents du travail'), ('AMO_ML', 'AMO Assurance maladie obligatoire'), ('CNSS_BF_RET', 'CNSS Retraite'), ('CNSS_BF_PF', 'CNSS Prestations familiales'), ('CNSS_BF_AT', 'CNSS Accidents du travail'), ('CNSS_NE_RET', 'CNSS Retraite'), ('CNSS_NE_PF', 'CNSS Prestations familiales'), ('CNSS_NE_AT', 'CNSS Accidents du travail'), ('AUTRE', 'Autre cotisation')], help_text='Nature de la cotisation sociale', max_length=20, verbose_name='Type de cotisation'),
        ),
    ]
