# Generated by Django 6.0.3 on 2026-04-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0016_alter_tauxcotisation_type_cotisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='departement_de',
            field=models.CharField(blank=True, help_text='Service ou département', max_length=100, null=True, verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='employe',
            name='departement_en',
            field=models.CharField(blank=True, help_text='Service ou département', max_length=100, null=True, verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='employe',
            name='departement_fr',
            field=models.CharField(blank=True, help_text='Service ou département', max_length=100, null=True, verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='employe',
            name='departement_it',
            field=models.CharField(blank=True, help_text='Service ou département', max_length=100, null=True, verbose_name='Département'),
        ),
    ]
