# Generated by Django 6.0.2 on 2026-02-15 08:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('numero', models.CharField(max_length=20, verbose_name='Numéro')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('budget_prevu', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Budget prévu')),
                ('cout_reel', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Coût réel')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('duree_estimee_heures', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Durée estimée (heures)')),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('EN_ATTENTE', 'En attente'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='A_FAIRE', max_length=20, verbose_name='Statut')),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=20, verbose_name='Priorité')),
                ('adresse', models.CharField(blank=True, max_length=500, verbose_name='Adresse')),
                ('coordonnees', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Coordonnées')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('assigne_a', models.ManyToManyField(blank=True, related_name='operations_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('contacts_assignes', models.ManyToManyField(blank=True, related_name='operations_assignees', to='core.contact', verbose_name='Contacts assignés')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('depend_de', models.ManyToManyField(blank=True, related_name='bloque', to='projets.operation', verbose_name='Dépend de')),
            ],
            options={
                'verbose_name': 'Opération',
                'verbose_name_plural': 'Opérations',
                'db_table': 'operations',
                'ordering': ['position', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='OperationNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projets.operation', verbose_name='Opération')),
            ],
            options={
                'verbose_name': "Note d'opération",
                'verbose_name_plural': "Notes d'opération",
                'db_table': 'operation_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('numero', models.CharField(max_length=20, verbose_name='Numéro')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('budget_prevu', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Budget prévu')),
                ('budget_reel', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Budget réel')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('adresse', models.CharField(blank=True, max_length=500, verbose_name='Adresse')),
                ('coordonnees', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Coordonnées')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=20, verbose_name='Statut')),
                ('prestataire_nom', models.CharField(blank=True, max_length=255, verbose_name='Nom du prestataire')),
                ('prestataire_contact', models.CharField(blank=True, max_length=255, verbose_name='Contact du prestataire')),
                ('est_sous_traite', models.BooleanField(default=False, verbose_name='Sous-traité')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('devise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.devise', verbose_name='Devise')),
                ('mandat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.mandat', verbose_name='Mandat')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'db_table': 'positions',
                'ordering': ['mandat', 'ordre'],
                'unique_together': {('mandat', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='projets.position', verbose_name='Position'),
        ),
    ]
