# Generated by Django 6.0.2 on 2026-02-11 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_collaborateurfiduciaire_unique_collaborateur_mandat_and_more'),
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='contacts_assignes',
            field=models.ManyToManyField(blank=True, related_name='operations_assignees', to='core.contact', verbose_name='Contacts assignés'),
        ),
        migrations.RemoveField(
            model_name='operation',
            name='assigne_a',
        ),
        migrations.AddField(
            model_name='operation',
            name='assigne_a',
            field=models.ManyToManyField(blank=True, related_name='operations_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à'),
        ),
    ]
