# Generated by Django 6.0.3 on 2026-04-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_langue_saisie'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='operation',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='operation',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='operation',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='operation',
            name='titre_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='operation',
            name='titre_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='operation',
            name='titre_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='operation',
            name='titre_it',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='operationnote',
            name='contenu_de',
            field=models.TextField(null=True, verbose_name='Contenu'),
        ),
        migrations.AddField(
            model_name='operationnote',
            name='contenu_en',
            field=models.TextField(null=True, verbose_name='Contenu'),
        ),
        migrations.AddField(
            model_name='operationnote',
            name='contenu_fr',
            field=models.TextField(null=True, verbose_name='Contenu'),
        ),
        migrations.AddField(
            model_name='operationnote',
            name='contenu_it',
            field=models.TextField(null=True, verbose_name='Contenu'),
        ),
        migrations.AddField(
            model_name='position',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='position',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='position',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='position',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='position',
            name='titre_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='position',
            name='titre_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='position',
            name='titre_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='position',
            name='titre_it',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
    ]
