# comptabilite/management/commands/load_ohada_chart_of_accounts.py
"""
Commande pour charger le plan comptable SYSCOHADA révisé 2017.

Usage:
    python manage.py load_ohada_chart_of_accounts
    python manage.py load_ohada_chart_of_accounts --mandat-id <uuid>
    python manage.py load_ohada_chart_of_accounts --force
"""

from django.core.management.base import BaseCommand
from django.db import transaction
from comptabilite.models import TypePlanComptable, ClasseComptable, PlanComptable, Compte


class Command(BaseCommand):
    help = "Charge le plan comptable OHADA (SYSCOHADA révisé 2017)"

    def add_arguments(self, parser):
        parser.add_argument(
            "--mandat-id",
            type=str,
            help="UUID du mandat auquel rattacher le plan (optionnel, crée un template si omis)",
        )
        parser.add_argument(
            "--force",
            action="store_true",
            help="Force la recréation même si le plan existe déjà",
        )

    def handle(self, *args, **options):
        self.stdout.write(
            self.style.WARNING("📊 Chargement du plan comptable OHADA (SYSCOHADA révisé)...")
        )

        with transaction.atomic():
            type_plan = self._get_or_create_type_plan()
            plan = self._get_or_create_plan(options, type_plan)
            accounts_data = self._get_ohada_accounts()
            created_count, updated_count = self._create_accounts(
                plan, type_plan, accounts_data, options["force"]
            )

            self.stdout.write(
                self.style.SUCCESS(
                    f'✅ Plan "{plan.nom}" : {created_count} comptes créés, {updated_count} mis à jour'
                )
            )
            return str(plan.id)

    def _get_or_create_type_plan(self):
        """Récupère ou crée le type de plan comptable OHADA."""
        try:
            return TypePlanComptable.objects.get(code="OHADA")
        except TypePlanComptable.DoesNotExist:
            self.stdout.write(
                self.style.WARNING("  ⚠ Type de plan OHADA non trouvé, création...")
            )

            type_plan = TypePlanComptable.objects.create(
                code="OHADA",
                nom="Plan Comptable OHADA",
                description="Système comptable OHADA pour les pays de la zone OHADA",
                pays="Zone OHADA",
                region="Afrique",
                norme_comptable="SYSCOHADA révisé",
                version="2017",
                ordre=2,
            )

            classes = [
                {'numero': 1, 'libelle': 'Comptes de ressources durables', 'type_compte': 'PASSIF', 'numero_debut': '1000', 'numero_fin': '1999'},
                {'numero': 2, 'libelle': "Comptes d'actif immobilisé", 'type_compte': 'ACTIF', 'numero_debut': '2000', 'numero_fin': '2999'},
                {'numero': 3, 'libelle': 'Comptes de stocks', 'type_compte': 'ACTIF', 'numero_debut': '3000', 'numero_fin': '3999'},
                {'numero': 4, 'libelle': 'Comptes de tiers', 'type_compte': 'ACTIF', 'numero_debut': '4000', 'numero_fin': '4999'},
                {'numero': 5, 'libelle': 'Comptes de trésorerie', 'type_compte': 'ACTIF', 'numero_debut': '5000', 'numero_fin': '5999'},
                {'numero': 6, 'libelle': 'Comptes de charges des activités ordinaires', 'type_compte': 'CHARGE', 'numero_debut': '6000', 'numero_fin': '6999'},
                {'numero': 7, 'libelle': 'Comptes de produits des activités ordinaires', 'type_compte': 'PRODUIT', 'numero_debut': '7000', 'numero_fin': '7999'},
                {'numero': 8, 'libelle': 'Comptes des autres charges et produits', 'type_compte': 'RESULTAT', 'numero_debut': '8000', 'numero_fin': '8999'},
                {'numero': 9, 'libelle': 'Comptes des engagements hors bilan', 'type_compte': 'ACTIF', 'numero_debut': '9000', 'numero_fin': '9999'},
            ]

            for c in classes:
                ClasseComptable.objects.create(
                    type_plan=type_plan,
                    numero=c['numero'],
                    libelle=c['libelle'],
                    type_compte=c['type_compte'],
                    numero_debut=c.get('numero_debut', ''),
                    numero_fin=c.get('numero_fin', ''),
                )

            self.stdout.write(self.style.SUCCESS("  ✓ Type de plan OHADA créé"))
            return type_plan

    def _get_or_create_plan(self, options, type_plan):
        """Crée ou récupère le plan comptable OHADA."""
        from core.models import Mandat

        mandat = None
        if options["mandat_id"]:
            mandat = Mandat.objects.get(pk=options["mandat_id"])

        defaults = {
            "nom_fr": "Plan Comptable OHADA",
            "nom_de": "OHADA-Kontenrahmen",
            "nom_it": "Piano Contabile OHADA",
            "nom_en": "OHADA Chart of Accounts",
            "description_fr": "Plan comptable SYSCOHADA révisé 2017",
            "description_de": "SYSCOHADA revidierter Kontenrahmen 2017",
            "description_it": "Piano contabile SYSCOHADA revisionato 2017",
            "description_en": "Revised SYSCOHADA chart of accounts 2017",
            "type_plan": type_plan,
            "is_template": mandat is None,
            "mandat": mandat,
        }

        if mandat:
            plan, created = PlanComptable.objects.get_or_create(
                mandat=mandat, type_plan=type_plan, defaults=defaults
            )
        else:
            plan, created = PlanComptable.objects.get_or_create(
                is_template=True, type_plan=type_plan, defaults=defaults
            )

        if created:
            self.stdout.write(self.style.SUCCESS(f"  ✓ Plan créé: {plan.nom}"))
        else:
            self.stdout.write(f"  → Plan existant: {plan.nom}")
            if options["force"]:
                for key, value in defaults.items():
                    if key != 'type_plan':
                        setattr(plan, key, value)
                plan.save()
                self.stdout.write("  → Traductions mises à jour")

        return plan

    def _create_accounts(self, plan, type_plan, accounts_data, force_update=False):
        """Crée les comptes avec hiérarchie et traductions."""
        classes_map = {
            c.numero: c for c in ClasseComptable.objects.filter(type_plan=type_plan)
        }

        code_to_account = {}
        created_count = 0
        updated_count = 0

        sorted_accounts = sorted(accounts_data, key=lambda x: len(x["code"]))

        for account_data in sorted_accounts:
            code = account_data["code"]
            labels = account_data["labels"]
            parent_code = account_data.get("parent")

            parent_account = code_to_account.get(parent_code) if parent_code else None

            classe_num = account_data.get("classe", int(code[0]) if code else 1)
            classe_comptable = classes_map.get(classe_num)

            defaults = {
                "libelle_fr": labels.get("fr", ""),
                "libelle_de": labels.get("de", labels.get("fr", "")),
                "libelle_it": labels.get("it", labels.get("fr", "")),
                "libelle_en": labels.get("en", labels.get("fr", "")),
                "libelle_court_fr": labels.get("fr", "")[:100],
                "libelle_court_de": labels.get("de", labels.get("fr", ""))[:100],
                "libelle_court_it": labels.get("it", labels.get("fr", ""))[:100],
                "libelle_court_en": labels.get("en", labels.get("fr", ""))[:100],
                "type_compte": account_data.get("type", "ACTIF"),
                "classe": classe_num,
                "classe_comptable": classe_comptable,
                "niveau": len(code),
                "compte_parent": parent_account,
                "est_collectif": len(code) <= 2,
                "imputable": account_data.get("imputable", len(code) >= 4),
                "lettrable": account_data.get("lettrable", False),
                "soumis_tva": account_data.get("soumis_tva", False),
                "code_tva_defaut": account_data.get("code_tva_defaut", ""),
            }

            account, created = Compte.objects.update_or_create(
                plan_comptable=plan, numero=code, defaults=defaults
            )

            code_to_account[code] = account

            if created:
                created_count += 1
                self.stdout.write(f"  ✓ {code} - {labels.get('fr', '')}")
            elif force_update:
                updated_count += 1
                self.stdout.write(f"  ↻ {code} - {labels.get('fr', '')}")

        return created_count, updated_count

    def _get_ohada_accounts(self):
        """Retourne les données du plan comptable OHADA (SYSCOHADA révisé 2017) complet."""

        # Format: (code, libellé_fr, libellé_en, type_compte, code_parent)
        raw_data = [
            # ═══════════════════════════════════════════════════════════════════════
            # CLASSE 1 - COMPTES DE RESSOURCES DURABLES
            # ═══════════════════════════════════════════════════════════════════════
            ("1", "Comptes de ressources durables", "Long-term resources accounts", "PASSIF", None),
            ("10", "Capital", "Capital", "PASSIF", "1"),
            ("101", "Capital social", "Share capital", "PASSIF", "10"),
            ("1011", "Capital souscrit, non appelé", "Subscribed capital, not called", "PASSIF", "101"),
            ("1012", "Capital souscrit, appelé, non versé", "Subscribed capital, called, not paid", "PASSIF", "101"),
            ("1013", "Capital souscrit, appelé, versé, non amorti", "Subscribed capital, called, paid, not amortized", "PASSIF", "101"),
            ("1014", "Capital souscrit, appelé, versé, amorti", "Subscribed capital, called, paid, amortized", "PASSIF", "101"),
            ("1018", "Capital souscrit soumis à des conditions particulières", "Subscribed capital with special conditions", "PASSIF", "101"),
            ("102", "Capital par dotation", "Endowment capital", "PASSIF", "10"),
            ("1021", "Dotation initiale", "Initial endowment", "PASSIF", "102"),
            ("1022", "Dotations complémentaires", "Additional endowments", "PASSIF", "102"),
            ("1028", "Autres dotations", "Other endowments", "PASSIF", "102"),
            ("103", "Capital personnel", "Personal capital", "PASSIF", "10"),
            ("104", "Compte de l'exploitant", "Owner's account", "PASSIF", "10"),
            ("1041", "Apports temporaires", "Temporary contributions", "PASSIF", "104"),
            ("1042", "Opérations courantes", "Current operations", "PASSIF", "104"),
            ("1043", "Rémunérations, impôts et autres charges personnelles", "Compensation, taxes and personal expenses", "PASSIF", "104"),
            ("1047", "Prélèvements d'autoconsommation", "Self-consumption withdrawals", "PASSIF", "104"),
            ("1048", "Autres prélèvements", "Other withdrawals", "PASSIF", "104"),
            ("105", "Primes liées au capital social", "Share premiums", "PASSIF", "10"),
            ("1051", "Primes d'émission", "Share issue premiums", "PASSIF", "105"),
            ("1052", "Primes d'apport", "Contribution premiums", "PASSIF", "105"),
            ("1053", "Primes de fusion", "Merger premiums", "PASSIF", "105"),
            ("1054", "Primes de conversion", "Conversion premiums", "PASSIF", "105"),
            ("1058", "Autres primes", "Other premiums", "PASSIF", "105"),
            ("106", "Écarts de réévaluation", "Revaluation reserves", "PASSIF", "10"),
            ("1061", "Écart de réévaluation légale", "Legal revaluation reserve", "PASSIF", "106"),
            ("1062", "Écart de réévaluation libre", "Free revaluation reserve", "PASSIF", "106"),
            ("109", "Actionnaire, capital souscrit non appelé", "Shareholder, subscribed capital not called", "ACTIF", "10"),
            ("11", "Réserves", "Reserves", "PASSIF", "1"),
            ("111", "Réserve légale", "Legal reserve", "PASSIF", "11"),
            ("112", "Réserves statutaires ou contractuelles", "Statutory or contractual reserves", "PASSIF", "11"),
            ("113", "Réserves réglementées", "Regulated reserves", "PASSIF", "11"),
            ("1131", "Réserves de plus-values nettes à long terme", "Long-term net capital gains reserves", "PASSIF", "113"),
            ("1132", "Réserves consécutives à l'octroi de subventions", "Reserves from investment grants", "PASSIF", "113"),
            ("1138", "Autres réserves réglementées", "Other regulated reserves", "PASSIF", "113"),
            ("118", "Autres réserves", "Other reserves", "PASSIF", "11"),
            ("1181", "Réserves facultatives", "Optional reserves", "PASSIF", "118"),
            ("1188", "Réserves diverses", "Miscellaneous reserves", "PASSIF", "118"),
            ("12", "Report à nouveau", "Retained earnings", "PASSIF", "1"),
            ("121", "Report à nouveau créditeur", "Retained earnings (credit)", "PASSIF", "12"),
            ("129", "Report à nouveau débiteur", "Retained earnings (debit)", "PASSIF", "12"),
            ("13", "Résultat net de l'exercice", "Net income for the year", "PASSIF", "1"),
            ("130", "Résultat en instance d'affectation", "Unappropriated result", "PASSIF", "13"),
            ("1301", "Résultat en instance d'affectation: Bénéfice", "Unappropriated result: Profit", "PASSIF", "130"),
            ("1309", "Résultat en instance d'affectation: Perte", "Unappropriated result: Loss", "PASSIF", "130"),
            ("131", "Résultat net: Bénéfice", "Net result: Profit", "PASSIF", "13"),
            ("139", "Résultat net: Perte", "Net result: Loss", "PASSIF", "13"),
            ("14", "Subventions d'investissement", "Investment grants", "PASSIF", "1"),
            ("141", "Subventions d'équipement", "Equipment grants", "PASSIF", "14"),
            ("1411", "État", "State", "PASSIF", "141"),
            ("1412", "Régions", "Regions", "PASSIF", "141"),
            ("1413", "Départements", "Departments", "PASSIF", "141"),
            ("1414", "Communes et collectivités publiques", "Municipalities and public authorities", "PASSIF", "141"),
            ("1415", "Entités publiques ou mixtes", "Public or mixed entities", "PASSIF", "141"),
            ("1416", "Entités et organismes privés", "Private entities and organizations", "PASSIF", "141"),
            ("1417", "Organismes internationaux", "International organizations", "PASSIF", "141"),
            ("1418", "Autres", "Others", "PASSIF", "141"),
            ("148", "Autres subventions d'investissement", "Other investment grants", "PASSIF", "14"),
            ("15", "Provisions réglementées et fonds assimilés", "Regulated provisions", "PASSIF", "1"),
            ("151", "Amortissements dérogatoires", "Accelerated depreciation", "PASSIF", "15"),
            ("152", "Plus-values de cession à réinvestir", "Capital gains to be reinvested", "PASSIF", "15"),
            ("153", "Fonds réglementés", "Regulated funds", "PASSIF", "15"),
            ("1531", "Fonds national", "National fund", "PASSIF", "153"),
            ("1532", "Prélèvement pour le budget", "Budget allocation", "PASSIF", "153"),
            ("154", "Provisions spéciales de réévaluation", "Special revaluation provisions", "PASSIF", "15"),
            ("155", "Provisions réglementées relatives aux immobilisations", "Regulated provisions for fixed assets", "PASSIF", "15"),
            ("1551", "Reconstitution des gisements miniers et pétroliers", "Reconstitution of mineral and oil deposits", "PASSIF", "155"),
            ("156", "Provisions réglementées relatives aux stocks", "Regulated provisions for inventories", "PASSIF", "15"),
            ("1561", "Hausse de prix", "Price increase", "PASSIF", "156"),
            ("1562", "Fluctuation des cours", "Price fluctuation", "PASSIF", "156"),
            ("157", "Provisions pour investissement", "Provisions for investment", "PASSIF", "15"),
            ("158", "Autres provisions et fonds réglementés", "Other provisions and regulated funds", "PASSIF", "15"),
            ("16", "Emprunts et dettes assimilées", "Borrowings and similar debts", "PASSIF", "1"),
            ("161", "Emprunts obligataires", "Bond loans", "PASSIF", "16"),
            ("1611", "Emprunts obligataires ordinaires", "Ordinary bond loans", "PASSIF", "161"),
            ("1612", "Emprunts obligataires convertibles en actions", "Convertible bond loans", "PASSIF", "161"),
            ("1618", "Autres emprunts obligataires", "Other bond loans", "PASSIF", "161"),
            ("162", "Emprunts et dettes auprès des établissements de crédit", "Loans from credit institutions", "PASSIF", "16"),
            ("163", "Avances reçues de l'État", "Advances from the State", "PASSIF", "16"),
            ("164", "Avances reçues et comptes courants bloqués", "Advances and blocked current accounts", "PASSIF", "16"),
            ("165", "Dépôts et cautionnements reçus", "Deposits and guarantees received", "PASSIF", "16"),
            ("1651", "Dépôts", "Deposits", "PASSIF", "165"),
            ("1652", "Cautionnements", "Guarantees", "PASSIF", "165"),
            ("166", "Intérêts courus", "Accrued interest", "PASSIF", "16"),
            ("1661", "Sur emprunts obligataires", "On bond loans", "PASSIF", "166"),
            ("1662", "Sur emprunts auprès des établissements de crédit", "On loans from credit institutions", "PASSIF", "166"),
            ("1663", "Sur avances reçues de l'État", "On advances from the State", "PASSIF", "166"),
            ("1668", "Sur autres emprunts et dettes", "On other borrowings", "PASSIF", "166"),
            ("167", "Avances assorties de conditions particulières", "Advances with special conditions", "PASSIF", "16"),
            ("1671", "Avances bloquées pour augmentation du capital", "Blocked advances for capital increase", "PASSIF", "167"),
            ("1672", "Avances conditionnées par l'État", "Conditional advances from the State", "PASSIF", "167"),
            ("1674", "Avances conditionnées par les organismes internationaux", "Conditional advances from international organizations", "PASSIF", "167"),
            ("168", "Autres emprunts et dettes", "Other borrowings and debts", "PASSIF", "16"),
            ("1681", "Rentes viagères capitalisées", "Capitalized life annuities", "PASSIF", "168"),
            ("1682", "Billets de fonds", "Promissory notes", "PASSIF", "168"),
            ("1683", "Dettes consécutives à des titres empruntés", "Debts from borrowed securities", "PASSIF", "168"),
            ("1684", "Emprunts participatifs", "Participating loans", "PASSIF", "168"),
            ("1685", "Participation des travailleurs aux bénéfices", "Employee profit sharing", "PASSIF", "168"),
            ("1686", "Emprunts et dettes auprès des autres tiers", "Borrowings from other third parties", "PASSIF", "168"),
            ("17", "Dettes de location-acquisition", "Finance lease liabilities", "PASSIF", "1"),
            ("172", "Emprunts équivalents de crédit-bail immobilier", "Real estate finance lease equivalent loans", "PASSIF", "17"),
            ("173", "Emprunts équivalents de crédit-bail mobilier", "Equipment finance lease equivalent loans", "PASSIF", "17"),
            ("176", "Intérêts courus", "Accrued interest", "PASSIF", "17"),
            ("1762", "Sur crédit-bail immobilier", "On real estate finance lease", "PASSIF", "176"),
            ("1763", "Sur crédit-bail mobilier", "On equipment finance lease", "PASSIF", "176"),
            ("178", "Autres dettes de location-acquisition", "Other finance lease liabilities", "PASSIF", "17"),
            ("18", "Dettes liées à des participations", "Debts related to investments", "PASSIF", "1"),
            ("181", "Dettes liées à des participations (groupe)", "Debts from group investments", "PASSIF", "18"),
            ("182", "Dettes liées à des participations (hors groupe)", "Debts from non-group investments", "PASSIF", "18"),
            ("183", "Intérêts courus sur dettes liées à des participations", "Accrued interest on investment debts", "PASSIF", "18"),
            ("184", "Comptes permanents bloqués des établissements", "Blocked permanent accounts of establishments", "PASSIF", "18"),
            ("185", "Comptes permanents non bloqués des établissements", "Unblocked permanent accounts of establishments", "PASSIF", "18"),
            ("186", "Comptes de liaison charges", "Expense intercompany accounts", "PASSIF", "18"),
            ("187", "Comptes de liaison produits", "Income intercompany accounts", "PASSIF", "18"),
            ("188", "Comptes de liaison des sociétés en participation", "Joint venture intercompany accounts", "PASSIF", "18"),
            ("19", "Provisions pour risques et charges", "Provisions for risks and charges", "PASSIF", "1"),
            ("191", "Provisions pour litiges", "Provisions for litigation", "PASSIF", "19"),
            ("192", "Provisions pour garanties données aux clients", "Provisions for customer warranties", "PASSIF", "19"),
            ("193", "Provisions pour pertes sur marchés à achèvement futur", "Provisions for losses on contracts", "PASSIF", "19"),
            ("194", "Provisions pour pertes de change", "Provisions for foreign exchange losses", "PASSIF", "19"),
            ("195", "Provisions pour impôts", "Provisions for taxes", "PASSIF", "19"),
            ("196", "Provisions pour pensions et obligations similaires", "Provisions for pensions", "PASSIF", "19"),
            ("1961", "Provisions pour pensions", "Provisions for pensions", "PASSIF", "196"),
            ("1968", "Autres provisions pour obligations similaires", "Other provisions for similar obligations", "PASSIF", "196"),
            ("197", "Provisions pour charges à répartir", "Provisions for allocated charges", "PASSIF", "19"),
            ("1971", "Provisions pour grosses réparations", "Provisions for major repairs", "PASSIF", "197"),
            ("198", "Autres provisions pour risques et charges", "Other provisions for risks and charges", "PASSIF", "19"),
            ("1981", "Provisions pour amendes et pénalités", "Provisions for fines and penalties", "PASSIF", "198"),
            ("1983", "Provisions pour propre assureur", "Self-insurance provisions", "PASSIF", "198"),
            ("1988", "Autres provisions pour risques divers", "Other miscellaneous provisions", "PASSIF", "198"),

            # ═══════════════════════════════════════════════════════════════════════
            # CLASSE 2 - COMPTES D'ACTIF IMMOBILISÉ
            # ═══════════════════════════════════════════════════════════════════════
            ("2", "Comptes d'actif immobilisé", "Fixed assets accounts", "ACTIF", None),
            ("21", "Immobilisations incorporelles", "Intangible assets", "ACTIF", "2"),
            ("211", "Frais de développement", "Development costs", "ACTIF", "21"),
            ("212", "Brevets, licences, concessions et droits similaires", "Patents, licenses, concessions", "ACTIF", "21"),
            ("2121", "Brevets", "Patents", "ACTIF", "212"),
            ("2122", "Licences", "Licenses", "ACTIF", "212"),
            ("2123", "Concessions", "Concessions", "ACTIF", "212"),
            ("2128", "Autres droits similaires", "Other similar rights", "ACTIF", "212"),
            ("213", "Logiciels et sites internet", "Software and websites", "ACTIF", "21"),
            ("2131", "Logiciels", "Software", "ACTIF", "213"),
            ("2132", "Sites internet", "Websites", "ACTIF", "213"),
            ("214", "Marques", "Trademarks", "ACTIF", "21"),
            ("215", "Fonds commercial", "Goodwill", "ACTIF", "21"),
            ("216", "Droit au bail", "Lease rights", "ACTIF", "21"),
            ("217", "Investissements de création", "Creative investments", "ACTIF", "21"),
            ("218", "Autres droits et valeurs incorporels", "Other intangible assets", "ACTIF", "21"),
            ("2181", "Frais de prospection et d'évaluation de ressources", "Prospecting and resource evaluation costs", "ACTIF", "218"),
            ("2188", "Autres droits et valeurs incorporels divers", "Other miscellaneous intangible assets", "ACTIF", "218"),
            ("219", "Immobilisations incorporelles en cours", "Intangible assets in progress", "ACTIF", "21"),
            ("22", "Terrains", "Land", "ACTIF", "2"),
            ("221", "Terrains agricoles et forestiers", "Agricultural and forest land", "ACTIF", "22"),
            ("222", "Terrains nus", "Undeveloped land", "ACTIF", "22"),
            ("223", "Terrains bâtis", "Built-on land", "ACTIF", "22"),
            ("224", "Travaux de mise en valeur des terrains", "Land development work", "ACTIF", "22"),
            ("225", "Terrains de gisement", "Mineral land", "ACTIF", "22"),
            ("226", "Terrains aménagés", "Developed land", "ACTIF", "22"),
            ("227", "Terrains mis en concession", "Concessioned land", "ACTIF", "22"),
            ("228", "Autres terrains", "Other land", "ACTIF", "22"),
            ("2281", "Terrains - immeubles de placement", "Land - investment property", "ACTIF", "228"),
            ("2285", "Terrains des logements affectés au personnel", "Land for staff housing", "ACTIF", "228"),
            ("2286", "Terrains en location-acquisition", "Leased land", "ACTIF", "228"),
            ("229", "Aménagements de terrains en cours", "Land development in progress", "ACTIF", "22"),
            ("23", "Bâtiments, installations techniques et agencements", "Buildings and installations", "ACTIF", "2"),
            ("231", "Bâtiments sur sol propre", "Buildings on own land", "ACTIF", "23"),
            ("2311", "Bâtiments industriels", "Industrial buildings", "ACTIF", "231"),
            ("2312", "Bâtiments agricoles", "Agricultural buildings", "ACTIF", "231"),
            ("2313", "Bâtiments administratifs et commerciaux", "Administrative and commercial buildings", "ACTIF", "231"),
            ("2314", "Bâtiments affectés au logement du personnel", "Staff housing buildings", "ACTIF", "231"),
            ("2315", "Bâtiments - immeubles de placement", "Investment property buildings", "ACTIF", "231"),
            ("2316", "Bâtiments en location-acquisition", "Finance lease buildings", "ACTIF", "231"),
            ("232", "Bâtiments sur sol d'autrui", "Buildings on third-party land", "ACTIF", "23"),
            ("233", "Ouvrages d'infrastructure", "Infrastructure works", "ACTIF", "23"),
            ("2331", "Voies de terre", "Roads", "ACTIF", "233"),
            ("2332", "Voies de fer", "Railways", "ACTIF", "233"),
            ("2333", "Voies d'eau", "Waterways", "ACTIF", "233"),
            ("2334", "Barrages, digues", "Dams, dikes", "ACTIF", "233"),
            ("2335", "Pistes d'aérodrome", "Airport runways", "ACTIF", "233"),
            ("2338", "Autres ouvrages d'infrastructure", "Other infrastructure works", "ACTIF", "233"),
            ("234", "Installations techniques", "Technical installations", "ACTIF", "23"),
            ("235", "Aménagements de bureaux", "Office fixtures", "ACTIF", "23"),
            ("237", "Bâtiments mis en concession", "Concessioned buildings", "ACTIF", "23"),
            ("238", "Autres installations et agencements", "Other installations and fixtures", "ACTIF", "23"),
            ("239", "Bâtiments et installations en cours", "Buildings in progress", "ACTIF", "23"),
            ("24", "Matériel, mobilier et actifs biologiques", "Equipment, furniture and biological assets", "ACTIF", "2"),
            ("241", "Matériel et outillage industriel et commercial", "Industrial and commercial equipment", "ACTIF", "24"),
            ("2411", "Matériel industriel", "Industrial equipment", "ACTIF", "241"),
            ("2412", "Outillage industriel", "Industrial tools", "ACTIF", "241"),
            ("2413", "Matériel commercial", "Commercial equipment", "ACTIF", "241"),
            ("2414", "Outillage commercial", "Commercial tools", "ACTIF", "241"),
            ("2416", "Matériel en location-acquisition", "Finance lease equipment", "ACTIF", "241"),
            ("242", "Matériel et outillage agricole", "Agricultural equipment", "ACTIF", "24"),
            ("243", "Matériel d'emballage récupérable", "Returnable packaging equipment", "ACTIF", "24"),
            ("244", "Matériel et mobilier", "Equipment and furniture", "ACTIF", "24"),
            ("2441", "Matériel de bureau", "Office equipment", "ACTIF", "244"),
            ("2442", "Matériel informatique", "Computer equipment", "ACTIF", "244"),
            ("2443", "Matériel bureautique", "Office automation equipment", "ACTIF", "244"),
            ("2444", "Mobilier de bureau", "Office furniture", "ACTIF", "244"),
            ("2446", "Matériel et mobilier en location-acquisition", "Finance lease equipment and furniture", "ACTIF", "244"),
            ("2447", "Matériel des logements du personnel", "Staff housing equipment", "ACTIF", "244"),
            ("245", "Matériel de transport", "Transport equipment", "ACTIF", "24"),
            ("2451", "Matériel automobile", "Motor vehicles", "ACTIF", "245"),
            ("2452", "Matériel ferroviaire", "Railway equipment", "ACTIF", "245"),
            ("2453", "Matériel fluvial, lagunaire", "River and lagoon equipment", "ACTIF", "245"),
            ("2454", "Matériel naval", "Naval equipment", "ACTIF", "245"),
            ("2455", "Matériel aérien", "Aircraft", "ACTIF", "245"),
            ("2456", "Matériel de transport en location-acquisition", "Finance lease transport equipment", "ACTIF", "245"),
            ("2458", "Autres matériels de transport", "Other transport equipment", "ACTIF", "245"),
            ("246", "Actifs biologiques", "Biological assets", "ACTIF", "24"),
            ("2461", "Cheptel, animaux de trait", "Livestock, draft animals", "ACTIF", "246"),
            ("2462", "Cheptel, animaux reproducteurs", "Livestock, breeding animals", "ACTIF", "246"),
            ("2463", "Animaux de garde", "Guard animals", "ACTIF", "246"),
            ("2465", "Plantations agricoles", "Agricultural plantations", "ACTIF", "246"),
            ("2468", "Autres actifs biologiques", "Other biological assets", "ACTIF", "246"),
            ("247", "Agencements, aménagements du matériel", "Equipment fittings", "ACTIF", "24"),
            ("248", "Autres matériels et mobiliers", "Other equipment and furniture", "ACTIF", "24"),
            ("2481", "Collections et œuvres d'art", "Collections and works of art", "ACTIF", "248"),
            ("2488", "Divers matériels et mobiliers", "Miscellaneous equipment and furniture", "ACTIF", "248"),
            ("249", "Matériel en cours", "Equipment in progress", "ACTIF", "24"),
            ("25", "Avances et acomptes versés sur immobilisations", "Advances on fixed assets", "ACTIF", "2"),
            ("251", "Avances sur immobilisations incorporelles", "Advances on intangible assets", "ACTIF", "25"),
            ("252", "Avances sur immobilisations corporelles", "Advances on tangible assets", "ACTIF", "25"),
            ("26", "Titres de participation", "Equity investments", "ACTIF", "2"),
            ("261", "Titres de participation dans des sociétés du groupe", "Equity investments in group companies", "ACTIF", "26"),
            ("262", "Titres de participation hors groupe", "Equity investments in non-group companies", "ACTIF", "26"),
            ("265", "Participations dans des organismes professionnels", "Investments in professional organizations", "ACTIF", "26"),
            ("266", "Parts dans des GIE", "Shares in economic interest groups", "ACTIF", "26"),
            ("268", "Autres titres de participation", "Other equity investments", "ACTIF", "26"),
            ("27", "Autres immobilisations financières", "Other financial assets", "ACTIF", "2"),
            ("271", "Prêts et créances non commerciales", "Non-commercial loans and receivables", "ACTIF", "27"),
            ("2711", "Prêts participatifs", "Participating loans", "ACTIF", "271"),
            ("2712", "Prêts aux associés", "Loans to partners", "ACTIF", "271"),
            ("2713", "Billets de fonds", "Promissory notes", "ACTIF", "271"),
            ("2718", "Autres prêts et créances", "Other loans and receivables", "ACTIF", "271"),
            ("272", "Prêts au personnel", "Loans to employees", "ACTIF", "27"),
            ("273", "Créances sur l'État", "Receivables from the State", "ACTIF", "27"),
            ("274", "Titres immobilisés", "Long-term securities", "ACTIF", "27"),
            ("2741", "Titres immobilisés (droit de propriété)", "Long-term securities (ownership)", "ACTIF", "274"),
            ("2742", "Titres immobilisés (droit de créance)", "Long-term securities (receivable)", "ACTIF", "274"),
            ("275", "Dépôts et cautionnements versés", "Deposits and guarantees paid", "ACTIF", "27"),
            ("2751", "Dépôts", "Deposits", "ACTIF", "275"),
            ("2752", "Cautionnements", "Guarantees", "ACTIF", "275"),
            ("276", "Intérêts courus", "Accrued interest", "ACTIF", "27"),
            ("2761", "Intérêts courus sur prêts non commerciaux", "Accrued interest on non-commercial loans", "ACTIF", "276"),
            ("2762", "Intérêts courus sur prêts au personnel", "Accrued interest on employee loans", "ACTIF", "276"),
            ("2768", "Intérêts courus sur créances diverses", "Accrued interest on miscellaneous receivables", "ACTIF", "276"),
            ("277", "Créances rattachées à des participations", "Receivables from investments", "ACTIF", "27"),
            ("2771", "Créances rattachées à des participations (groupe)", "Receivables from group investments", "ACTIF", "277"),
            ("2772", "Créances rattachées à des participations (hors groupe)", "Receivables from non-group investments", "ACTIF", "277"),
            ("2773", "Intérêts courus sur créances rattachées", "Accrued interest on investment receivables", "ACTIF", "277"),
            ("278", "Immobilisations financières diverses", "Other financial assets", "ACTIF", "27"),
            ("28", "Amortissements", "Accumulated depreciation", "ACTIF", "2"),
            ("281", "Amortissements des immobilisations incorporelles", "Accumulated amortization of intangible assets", "ACTIF", "28"),
            ("2811", "Amortissements des frais de développement", "Accumulated amortization of development costs", "ACTIF", "281"),
            ("2812", "Amortissements des brevets, licences, concessions", "Accumulated amortization of patents", "ACTIF", "281"),
            ("2813", "Amortissements des logiciels et sites internet", "Accumulated amortization of software", "ACTIF", "281"),
            ("2816", "Amortissements du droit au bail", "Accumulated amortization of lease rights", "ACTIF", "281"),
            ("2818", "Amortissements des autres droits incorporels", "Accumulated amortization of other intangible assets", "ACTIF", "281"),
            ("282", "Amortissements des terrains", "Accumulated depreciation of land", "ACTIF", "28"),
            ("283", "Amortissements des bâtiments", "Accumulated depreciation of buildings", "ACTIF", "28"),
            ("2831", "Amortissements des bâtiments sur sol propre", "Accumulated depreciation of buildings on own land", "ACTIF", "283"),
            ("2832", "Amortissements des bâtiments sur sol d'autrui", "Accumulated depreciation of buildings on third-party land", "ACTIF", "283"),
            ("2833", "Amortissements des ouvrages d'infrastructure", "Accumulated depreciation of infrastructure", "ACTIF", "283"),
            ("2834", "Amortissements des installations techniques", "Accumulated depreciation of technical installations", "ACTIF", "283"),
            ("2835", "Amortissements des aménagements de bureaux", "Accumulated depreciation of office fixtures", "ACTIF", "283"),
            ("2838", "Amortissements des autres installations", "Accumulated depreciation of other installations", "ACTIF", "283"),
            ("284", "Amortissements du matériel", "Accumulated depreciation of equipment", "ACTIF", "28"),
            ("2841", "Amortissements du matériel industriel et commercial", "Accumulated depreciation of industrial equipment", "ACTIF", "284"),
            ("2842", "Amortissements du matériel agricole", "Accumulated depreciation of agricultural equipment", "ACTIF", "284"),
            ("2844", "Amortissements du matériel et mobilier", "Accumulated depreciation of equipment and furniture", "ACTIF", "284"),
            ("2845", "Amortissements du matériel de transport", "Accumulated depreciation of transport equipment", "ACTIF", "284"),
            ("2846", "Amortissements des actifs biologiques", "Accumulated depreciation of biological assets", "ACTIF", "284"),
            ("2848", "Amortissements des autres matériels", "Accumulated depreciation of other equipment", "ACTIF", "284"),
            ("29", "Dépréciations des immobilisations", "Impairment of fixed assets", "ACTIF", "2"),
            ("291", "Dépréciations des immobilisations incorporelles", "Impairment of intangible assets", "ACTIF", "29"),
            ("292", "Dépréciations des terrains", "Impairment of land", "ACTIF", "29"),
            ("293", "Dépréciations des bâtiments", "Impairment of buildings", "ACTIF", "29"),
            ("294", "Dépréciations du matériel", "Impairment of equipment", "ACTIF", "29"),
            ("295", "Dépréciations des avances versées", "Impairment of advances paid", "ACTIF", "29"),
            ("296", "Dépréciations des titres de participation", "Impairment of equity investments", "ACTIF", "29"),
            ("297", "Dépréciations des autres immobilisations financières", "Impairment of other financial assets", "ACTIF", "29"),

            # ═══════════════════════════════════════════════════════════════════════
            # CLASSE 3 - COMPTES DE STOCKS
            # ═══════════════════════════════════════════════════════════════════════
            ("3", "Comptes de stocks", "Inventory accounts", "ACTIF", None),
            ("31", "Marchandises", "Merchandise", "ACTIF", "3"),
            ("311", "Marchandises A", "Merchandise A", "ACTIF", "31"),
            ("312", "Marchandises B", "Merchandise B", "ACTIF", "31"),
            ("318", "Marchandises hors activités ordinaires", "Non-operating merchandise", "ACTIF", "31"),
            ("32", "Matières premières et fournitures liées", "Raw materials and supplies", "ACTIF", "3"),
            ("321", "Matières premières", "Raw materials", "ACTIF", "32"),
            ("322", "Matières et fournitures A", "Materials and supplies A", "ACTIF", "32"),
            ("323", "Matières et fournitures B", "Materials and supplies B", "ACTIF", "32"),
            ("33", "Autres approvisionnements", "Other supplies", "ACTIF", "3"),
            ("331", "Matières consommables", "Consumable materials", "ACTIF", "33"),
            ("332", "Fournitures d'atelier et d'usine", "Workshop and factory supplies", "ACTIF", "33"),
            ("333", "Fournitures de magasin", "Store supplies", "ACTIF", "33"),
            ("334", "Fournitures de bureau", "Office supplies", "ACTIF", "33"),
            ("335", "Emballages", "Packaging", "ACTIF", "33"),
            ("3351", "Emballages perdus", "Non-returnable packaging", "ACTIF", "335"),
            ("3352", "Emballages récupérables non identifiables", "Returnable non-identifiable packaging", "ACTIF", "335"),
            ("3353", "Emballages à usage mixte", "Mixed-use packaging", "ACTIF", "335"),
            ("3358", "Autres emballages", "Other packaging", "ACTIF", "335"),
            ("338", "Autres matières", "Other materials", "ACTIF", "33"),
            ("34", "Produits en cours", "Work in progress", "ACTIF", "3"),
            ("341", "Produits en cours", "Products in progress", "ACTIF", "34"),
            ("342", "Travaux en cours", "Work in progress", "ACTIF", "34"),
            ("343", "Produits intermédiaires en cours", "Intermediate products in progress", "ACTIF", "34"),
            ("344", "Produits résiduels en cours", "Residual products in progress", "ACTIF", "34"),
            ("35", "Services en cours", "Services in progress", "ACTIF", "3"),
            ("351", "Études en cours", "Studies in progress", "ACTIF", "35"),
            ("352", "Prestations de services en cours", "Services in progress", "ACTIF", "35"),
            ("36", "Produits finis", "Finished goods", "ACTIF", "3"),
            ("361", "Produits finis A", "Finished goods A", "ACTIF", "36"),
            ("362", "Produits finis B", "Finished goods B", "ACTIF", "36"),
            ("37", "Produits intermédiaires et résiduels", "Intermediate and residual products", "ACTIF", "3"),
            ("371", "Produits intermédiaires", "Intermediate products", "ACTIF", "37"),
            ("372", "Produits résiduels", "Residual products", "ACTIF", "37"),
            ("38", "Stocks en cours de route", "Inventory in transit", "ACTIF", "3"),
            ("381", "Marchandises en cours de route", "Merchandise in transit", "ACTIF", "38"),
            ("382", "Matières premières en cours de route", "Raw materials in transit", "ACTIF", "38"),
            ("386", "Produits finis en cours de route", "Finished goods in transit", "ACTIF", "38"),
            ("387", "Stocks en consignation ou en dépôt", "Inventory on consignment", "ACTIF", "38"),
            ("39", "Dépréciations des stocks", "Impairment of inventories", "ACTIF", "3"),
            ("391", "Dépréciations des stocks de marchandises", "Impairment of merchandise", "ACTIF", "39"),
            ("392", "Dépréciations des matières premières", "Impairment of raw materials", "ACTIF", "39"),
            ("393", "Dépréciations des autres approvisionnements", "Impairment of other supplies", "ACTIF", "39"),
            ("394", "Dépréciations des produits en cours", "Impairment of work in progress", "ACTIF", "39"),
            ("395", "Dépréciations des services en cours", "Impairment of services in progress", "ACTIF", "39"),
            ("396", "Dépréciations des produits finis", "Impairment of finished goods", "ACTIF", "39"),
            ("397", "Dépréciations des produits intermédiaires", "Impairment of intermediate products", "ACTIF", "39"),
            ("398", "Dépréciations des stocks en cours de route", "Impairment of inventory in transit", "ACTIF", "39"),

            # ═══════════════════════════════════════════════════════════════════════
            # CLASSE 4 - COMPTES DE TIERS
            # ═══════════════════════════════════════════════════════════════════════
            ("4", "Comptes de tiers", "Third-party accounts", "ACTIF", None),
            ("40", "Fournisseurs et comptes rattachés", "Suppliers and related accounts", "PASSIF", "4"),
            ("401", "Fournisseurs, dettes en compte", "Suppliers, account payables", "PASSIF", "40"),
            ("4011", "Fournisseurs", "Suppliers", "PASSIF", "401"),
            ("4012", "Fournisseurs - groupe", "Suppliers - group", "PASSIF", "401"),
            ("4017", "Fournisseurs, retenues de garantie", "Suppliers, retention guarantees", "PASSIF", "401"),
            ("402", "Fournisseurs, effets à payer", "Suppliers, notes payable", "PASSIF", "40"),
            ("404", "Fournisseurs d'investissements", "Investment suppliers", "PASSIF", "40"),
            ("408", "Fournisseurs, factures non parvenues", "Suppliers, unbilled invoices", "PASSIF", "40"),
            ("409", "Fournisseurs débiteurs", "Debit balances with suppliers", "ACTIF", "40"),
            ("4091", "Fournisseurs, avances et acomptes versés", "Suppliers, advances paid", "ACTIF", "409"),
            ("4094", "Fournisseurs, créances pour emballages à rendre", "Suppliers, returnable packaging", "ACTIF", "409"),
            ("4098", "Fournisseurs, rabais et ristournes à obtenir", "Suppliers, rebates receivable", "ACTIF", "409"),
            ("41", "Clients et comptes rattachés", "Customers and related accounts", "ACTIF", "4"),
            ("411", "Clients", "Customers", "ACTIF", "41"),
            ("4111", "Clients", "Customers", "ACTIF", "411"),
            ("4112", "Clients - groupe", "Customers - group", "ACTIF", "411"),
            ("4117", "Clients, retenues de garantie", "Customers, retention guarantees", "ACTIF", "411"),
            ("412", "Clients, effets à recevoir", "Customers, notes receivable", "ACTIF", "41"),
            ("414", "Créances sur cessions d'immobilisations", "Receivables from asset disposals", "ACTIF", "41"),
            ("416", "Créances clients litigieuses ou douteuses", "Disputed or doubtful receivables", "ACTIF", "41"),
            ("418", "Clients, produits à recevoir", "Customers, accrued income", "ACTIF", "41"),
            ("419", "Clients créditeurs", "Credit balances with customers", "PASSIF", "41"),
            ("4191", "Clients, avances et acomptes reçus", "Customers, advances received", "PASSIF", "419"),
            ("4194", "Clients, dettes pour emballages consignés", "Customers, returnable packaging deposits", "PASSIF", "419"),
            ("4198", "Clients, rabais et ristournes à accorder", "Customers, rebates payable", "PASSIF", "419"),
            ("42", "Personnel", "Employees", "PASSIF", "4"),
            ("421", "Personnel, avances et acomptes", "Employees, advances", "ACTIF", "42"),
            ("422", "Personnel, rémunérations dues", "Employees, salaries payable", "PASSIF", "42"),
            ("423", "Personnel, oppositions, saisies-arrêts", "Employees, garnishments", "PASSIF", "42"),
            ("424", "Personnel, œuvres sociales", "Employees, social benefits", "PASSIF", "42"),
            ("425", "Représentants du personnel", "Employee representatives", "PASSIF", "42"),
            ("426", "Personnel, participation aux bénéfices", "Employees, profit sharing", "PASSIF", "42"),
            ("428", "Personnel, charges à payer", "Employees, accrued expenses", "PASSIF", "42"),
            ("43", "Organismes sociaux", "Social security organizations", "PASSIF", "4"),
            ("431", "Sécurité sociale", "Social security", "PASSIF", "43"),
            ("432", "Caisses de retraite", "Pension funds", "PASSIF", "43"),
            ("433", "Autres organismes sociaux", "Other social organizations", "PASSIF", "43"),
            ("438", "Organismes sociaux, charges à payer", "Social organizations, accrued expenses", "PASSIF", "43"),
            ("44", "État et collectivités publiques", "Government and public authorities", "PASSIF", "4"),
            ("441", "État, impôt sur les bénéfices", "State, income tax", "PASSIF", "44"),
            ("442", "État, autres impôts et taxes", "State, other taxes", "PASSIF", "44"),
            ("443", "État, TVA facturée", "State, VAT collected", "PASSIF", "44"),
            ("4431", "TVA facturée sur ventes", "VAT collected on sales", "PASSIF", "443"),
            ("4432", "TVA facturée sur prestations de services", "VAT collected on services", "PASSIF", "443"),
            ("4433", "TVA facturée sur travaux", "VAT collected on work", "PASSIF", "443"),
            ("4435", "TVA sur factures à établir", "VAT on invoices to be issued", "PASSIF", "443"),
            ("444", "État, TVA due ou crédit de TVA", "State, VAT payable or receivable", "PASSIF", "44"),
            ("4441", "État, TVA due", "State, VAT payable", "PASSIF", "444"),
            ("4449", "État, crédit de TVA à reporter", "State, VAT credit carryforward", "ACTIF", "444"),
            ("445", "État, TVA récupérable", "State, recoverable VAT", "ACTIF", "44"),
            ("4451", "TVA récupérable sur immobilisations", "Recoverable VAT on fixed assets", "ACTIF", "445"),
            ("4452", "TVA récupérable sur achats", "Recoverable VAT on purchases", "ACTIF", "445"),
            ("4453", "TVA récupérable sur transport", "Recoverable VAT on transport", "ACTIF", "445"),
            ("4454", "TVA récupérable sur services extérieurs", "Recoverable VAT on external services", "ACTIF", "445"),
            ("4455", "TVA récupérable sur factures non parvenues", "Recoverable VAT on unbilled invoices", "ACTIF", "445"),
            ("446", "État, autres taxes sur le chiffre d'affaires", "State, other taxes on turnover", "PASSIF", "44"),
            ("447", "État, impôts retenus à la source", "State, withholding taxes", "PASSIF", "44"),
            ("448", "État, charges à payer et produits à recevoir", "State, accrued expenses and income", "PASSIF", "44"),
            ("4486", "État, charges à payer", "State, accrued expenses", "PASSIF", "448"),
            ("4487", "État, produits à recevoir", "State, accrued income", "ACTIF", "448"),
            ("449", "État, créances et dettes diverses", "State, miscellaneous receivables and payables", "PASSIF", "44"),
            ("45", "Organismes internationaux", "International organizations", "PASSIF", "4"),
            ("451", "Opérations avec les organismes africains", "Transactions with African organizations", "PASSIF", "45"),
            ("452", "Opérations avec les autres organismes internationaux", "Transactions with other international organizations", "PASSIF", "45"),
            ("458", "Organismes internationaux, charges à payer", "International organizations, accrued expenses", "PASSIF", "45"),
            ("46", "Associés et groupe", "Partners and group", "PASSIF", "4"),
            ("461", "Associés, opérations sur le capital", "Partners, capital operations", "ACTIF", "46"),
            ("462", "Associés, comptes courants", "Partners, current accounts", "PASSIF", "46"),
            ("463", "Associés, opérations faites en commun", "Partners, joint operations", "PASSIF", "46"),
            ("465", "Associés, dividendes à payer", "Partners, dividends payable", "PASSIF", "46"),
            ("466", "Groupe, comptes courants", "Group, current accounts", "PASSIF", "46"),
            ("467", "Actionnaires, restant dû sur capital appelé", "Shareholders, remaining called capital", "ACTIF", "46"),
            ("47", "Débiteurs et créditeurs divers", "Miscellaneous debtors and creditors", "ACTIF", "4"),
            ("471", "Comptes d'attente", "Suspense accounts", "ACTIF", "47"),
            ("472", "Versements restant à effectuer sur titres", "Amounts due on unpaid securities", "PASSIF", "47"),
            ("476", "Charges constatées d'avance", "Prepaid expenses", "ACTIF", "47"),
            ("477", "Produits constatés d'avance", "Deferred income", "PASSIF", "47"),
            ("478", "Écarts de conversion - Actif", "Foreign exchange differences - Asset", "ACTIF", "47"),
            ("479", "Écarts de conversion - Passif", "Foreign exchange differences - Liability", "PASSIF", "47"),
            ("48", "Créances et dettes hors activités ordinaires", "Non-operating receivables and payables", "ACTIF", "4"),
            ("481", "Fournisseurs d'investissements", "Investment suppliers", "PASSIF", "48"),
            ("482", "Fournisseurs d'investissements, effets à payer", "Investment suppliers, notes payable", "PASSIF", "48"),
            ("484", "Autres dettes HAO", "Other non-operating payables", "PASSIF", "48"),
            ("485", "Créances sur cessions d'immobilisations", "Receivables from asset disposals", "ACTIF", "48"),
            ("488", "Autres créances HAO", "Other non-operating receivables", "ACTIF", "48"),
            ("49", "Dépréciations et risques provisionnés", "Impairment and provisioned risks", "ACTIF", "4"),
            ("490", "Dépréciations des comptes fournisseurs", "Impairment of supplier accounts", "ACTIF", "49"),
            ("491", "Dépréciations des comptes clients", "Impairment of customer accounts", "ACTIF", "49"),
            ("492", "Dépréciations des comptes personnel", "Impairment of employee accounts", "ACTIF", "49"),
            ("493", "Dépréciations des comptes organismes sociaux", "Impairment of social organization accounts", "ACTIF", "49"),
            ("494", "Dépréciations des comptes État", "Impairment of government accounts", "ACTIF", "49"),
            ("496", "Dépréciations des comptes associés et groupe", "Impairment of partner accounts", "ACTIF", "49"),
            ("497", "Dépréciations des débiteurs divers", "Impairment of miscellaneous debtors", "ACTIF", "49"),
            ("498", "Dépréciations des créances HAO", "Impairment of non-operating receivables", "ACTIF", "49"),
            ("499", "Risques provisionnés", "Provisioned risks", "PASSIF", "49"),

            # ═══════════════════════════════════════════════════════════════════════
            # CLASSE 5 - COMPTES DE TRÉSORERIE
            # ═══════════════════════════════════════════════════════════════════════
            ("5", "Comptes de trésorerie", "Cash and cash equivalents", "ACTIF", None),
            ("50", "Titres de placement", "Marketable securities", "ACTIF", "5"),
            ("501", "Titres du trésor et bons de caisse", "Treasury bills and cash bonds", "ACTIF", "50"),
            ("502", "Actions", "Shares", "ACTIF", "50"),
            ("503", "Obligations", "Bonds", "ACTIF", "50"),
            ("504", "Bons de souscription", "Subscription warrants", "ACTIF", "50"),
            ("506", "Intérêts courus", "Accrued interest", "ACTIF", "50"),
            ("508", "Autres titres de placement", "Other marketable securities", "ACTIF", "50"),
            ("51", "Valeurs à encaisser", "Items for collection", "ACTIF", "5"),
            ("511", "Effets à encaisser", "Notes receivable for collection", "ACTIF", "51"),
            ("512", "Effets à l'encaissement", "Notes sent for collection", "ACTIF", "51"),
            ("513", "Chèques à encaisser", "Checks for collection", "ACTIF", "51"),
            ("514", "Chèques à l'encaissement", "Checks sent for collection", "ACTIF", "51"),
            ("515", "Cartes de crédit à encaisser", "Credit card receipts", "ACTIF", "51"),
            ("518", "Autres valeurs à l'encaissement", "Other items for collection", "ACTIF", "51"),
            ("52", "Banques", "Banks", "ACTIF", "5"),
            ("521", "Banques locales", "Local banks", "ACTIF", "52"),
            ("5211", "Banques en monnaie nationale", "Banks in local currency", "ACTIF", "521"),
            ("5212", "Banques en devises", "Banks in foreign currency", "ACTIF", "521"),
            ("522", "Banques autres États région", "Regional banks", "ACTIF", "52"),
            ("523", "Banques autres États zone monétaire", "Banks in monetary zone", "ACTIF", "52"),
            ("524", "Banques hors zone monétaire", "Banks outside monetary zone", "ACTIF", "52"),
            ("526", "Banques, intérêts courus", "Banks, accrued interest", "ACTIF", "52"),
            ("53", "Établissements financiers et assimilés", "Financial institutions", "ACTIF", "5"),
            ("531", "Chèques postaux", "Postal checks", "ACTIF", "53"),
            ("532", "Trésor", "Treasury", "ACTIF", "53"),
            ("533", "Sociétés de gestion et d'intermédiation", "Management and intermediation companies", "ACTIF", "53"),
            ("538", "Autres organismes financiers", "Other financial organizations", "ACTIF", "53"),
            ("54", "Instruments de trésorerie", "Treasury instruments", "ACTIF", "5"),
            ("541", "Options de taux d'intérêt", "Interest rate options", "ACTIF", "54"),
            ("542", "Options de taux de change", "Exchange rate options", "ACTIF", "54"),
            ("543", "Options de taux boursiers", "Stock market rate options", "ACTIF", "54"),
            ("544", "Instruments de marchés à terme", "Futures market instruments", "ACTIF", "54"),
            ("545", "Avoirs d'or et autres métaux précieux", "Gold and precious metal holdings", "ACTIF", "54"),
            ("55", "Monnaie électronique", "Electronic money", "ACTIF", "5"),
            ("551", "Monnaie électronique - Carte carburant", "Electronic money - Fuel card", "ACTIF", "55"),
            ("552", "Monnaie électronique - Téléphone portable", "Electronic money - Mobile phone", "ACTIF", "55"),
            ("553", "Monnaie électronique - Carte péage", "Electronic money - Toll card", "ACTIF", "55"),
            ("554", "Porte-monnaie électronique", "Electronic wallet", "ACTIF", "55"),
            ("558", "Autres instruments monnaie électronique", "Other electronic money instruments", "ACTIF", "55"),
            ("56", "Banques, crédits de trésorerie", "Banks, cash credits", "PASSIF", "5"),
            ("561", "Crédits de trésorerie", "Cash credits", "PASSIF", "56"),
            ("564", "Escompte de crédits de campagne", "Campaign credit discounts", "PASSIF", "56"),
            ("565", "Escompte de crédits ordinaires", "Ordinary credit discounts", "PASSIF", "56"),
            ("566", "Banques, crédits de trésorerie, intérêts courus", "Banks, cash credits, accrued interest", "PASSIF", "56"),
            ("57", "Caisse", "Cash on hand", "ACTIF", "5"),
            ("571", "Caisse siège social", "Head office cash", "ACTIF", "57"),
            ("5711", "Caisse en monnaie nationale", "Cash in local currency", "ACTIF", "571"),
            ("5712", "Caisse en devises", "Cash in foreign currency", "ACTIF", "571"),
            ("572", "Caisse succursale A", "Branch A cash", "ACTIF", "57"),
            ("573", "Caisse succursale B", "Branch B cash", "ACTIF", "57"),
            ("58", "Régies d'avances et virements internes", "Advance funds and internal transfers", "ACTIF", "5"),
            ("581", "Régies d'avances", "Advance funds", "ACTIF", "58"),
            ("582", "Accréditifs", "Letters of credit", "ACTIF", "58"),
            ("585", "Virements de fonds", "Fund transfers", "ACTIF", "58"),
            ("588", "Autres virements internes", "Other internal transfers", "ACTIF", "58"),
            ("59", "Dépréciations et provisions trésorerie", "Impairment of cash", "ACTIF", "5"),
            ("590", "Dépréciations des titres de placement", "Impairment of marketable securities", "ACTIF", "59"),
            ("591", "Dépréciations des valeurs à encaisser", "Impairment of items for collection", "ACTIF", "59"),
            ("592", "Dépréciations des comptes banques", "Impairment of bank accounts", "ACTIF", "59"),

            # ═══════════════════════════════════════════════════════════════════════
            # CLASSE 6 - COMPTES DE CHARGES DES ACTIVITÉS ORDINAIRES
            # ═══════════════════════════════════════════════════════════════════════
            ("6", "Comptes de charges des activités ordinaires", "Operating expense accounts", "CHARGE", None),
            ("60", "Achats et variations de stocks", "Purchases and inventory changes", "CHARGE", "6"),
            ("601", "Achats de marchandises", "Purchase of merchandise", "CHARGE", "60"),
            ("6019", "Rabais, remises et ristournes obtenus sur achats de marchandises", "Rebates on merchandise purchases", "CHARGE", "601"),
            ("602", "Achats de matières premières", "Purchase of raw materials", "CHARGE", "60"),
            ("6029", "Rabais, remises et ristournes obtenus sur achats de matières", "Rebates on raw material purchases", "CHARGE", "602"),
            ("603", "Variations des stocks de biens achetés", "Changes in purchased goods inventory", "CHARGE", "60"),
            ("6031", "Variations des stocks de marchandises", "Changes in merchandise inventory", "CHARGE", "603"),
            ("6032", "Variations des stocks de matières premières", "Changes in raw materials inventory", "CHARGE", "603"),
            ("6033", "Variations des stocks d'autres approvisionnements", "Changes in other supplies inventory", "CHARGE", "603"),
            ("604", "Achats de matières et fournitures consommables", "Purchase of consumable materials", "CHARGE", "60"),
            ("6041", "Matières consommables", "Consumable materials", "CHARGE", "604"),
            ("6042", "Matières combustibles", "Fuel materials", "CHARGE", "604"),
            ("6043", "Produits d'entretien", "Maintenance products", "CHARGE", "604"),
            ("6044", "Fournitures d'atelier et d'usine", "Workshop supplies", "CHARGE", "604"),
            ("6046", "Fournitures de bureau", "Office supplies", "CHARGE", "604"),
            ("6047", "Fournitures informatiques", "IT supplies", "CHARGE", "604"),
            ("605", "Autres achats", "Other purchases", "CHARGE", "60"),
            ("6051", "Fournitures non stockables - Eau", "Non-storable supplies - Water", "CHARGE", "605"),
            ("6052", "Fournitures non stockables - Électricité", "Non-storable supplies - Electricity", "CHARGE", "605"),
            ("6053", "Fournitures non stockables - Autres énergies", "Non-storable supplies - Other energy", "CHARGE", "605"),
            ("6054", "Fournitures d'entretien non stockables", "Non-storable maintenance supplies", "CHARGE", "605"),
            ("6056", "Achats de petit matériel et outillage", "Purchase of small equipment", "CHARGE", "605"),
            ("6057", "Achats d'études et prestations de services", "Purchase of studies and services", "CHARGE", "605"),
            ("6058", "Achats de travaux, matériels et équipements", "Purchase of work and equipment", "CHARGE", "605"),
            ("608", "Achats d'emballages", "Purchase of packaging", "CHARGE", "60"),
            ("609", "Rabais, remises et ristournes obtenus sur achats", "Rebates obtained on purchases", "CHARGE", "60"),
            ("61", "Transports", "Transportation", "CHARGE", "6"),
            ("611", "Transports sur achats", "Transportation on purchases", "CHARGE", "61"),
            ("612", "Transports sur ventes", "Transportation on sales", "CHARGE", "61"),
            ("613", "Transports pour le compte de tiers", "Transportation for third parties", "CHARGE", "61"),
            ("614", "Transports du personnel", "Staff transportation", "CHARGE", "61"),
            ("618", "Autres frais de transport", "Other transportation expenses", "CHARGE", "61"),
            ("62", "Services extérieurs A", "External services A", "CHARGE", "6"),
            ("621", "Sous-traitance générale", "General subcontracting", "CHARGE", "62"),
            ("622", "Locations et charges locatives", "Rent and rental charges", "CHARGE", "62"),
            ("6221", "Locations de terrains", "Land rental", "CHARGE", "622"),
            ("6222", "Locations de bâtiments", "Building rental", "CHARGE", "622"),
            ("6223", "Locations de matériel et outillage", "Equipment rental", "CHARGE", "622"),
            ("6224", "Malis sur emballages", "Packaging losses", "CHARGE", "622"),
            ("6225", "Locations d'emballages", "Packaging rental", "CHARGE", "622"),
            ("6228", "Locations et charges locatives diverses", "Other rental charges", "CHARGE", "622"),
            ("623", "Redevances de crédit-bail", "Finance lease payments", "CHARGE", "62"),
            ("6232", "Crédit-bail immobilier", "Real estate finance lease", "CHARGE", "623"),
            ("6233", "Crédit-bail mobilier", "Equipment finance lease", "CHARGE", "623"),
            ("624", "Entretien, réparations et maintenance", "Maintenance and repairs", "CHARGE", "62"),
            ("6241", "Entretien et réparations des biens immobiliers", "Real estate maintenance", "CHARGE", "624"),
            ("6242", "Entretien et réparations des biens mobiliers", "Equipment maintenance", "CHARGE", "624"),
            ("6243", "Maintenance", "Maintenance", "CHARGE", "624"),
            ("6248", "Autres entretiens et réparations", "Other maintenance and repairs", "CHARGE", "624"),
            ("625", "Primes d'assurance", "Insurance premiums", "CHARGE", "62"),
            ("6251", "Assurances multirisques", "Multi-risk insurance", "CHARGE", "625"),
            ("6252", "Assurances matériel de transport", "Transport equipment insurance", "CHARGE", "625"),
            ("6253", "Assurances risques d'exploitation", "Operating risk insurance", "CHARGE", "625"),
            ("6255", "Assurances transport sur achats", "Purchase transport insurance", "CHARGE", "625"),
            ("6256", "Assurances transport sur ventes", "Sales transport insurance", "CHARGE", "625"),
            ("6258", "Autres primes d'assurance", "Other insurance premiums", "CHARGE", "625"),
            ("626", "Études, recherches et documentation", "Studies and documentation", "CHARGE", "62"),
            ("6261", "Études et recherches", "Studies and research", "CHARGE", "626"),
            ("6265", "Documentation générale", "General documentation", "CHARGE", "626"),
            ("6266", "Documentation technique", "Technical documentation", "CHARGE", "626"),
            ("627", "Publicité, publications, relations publiques", "Advertising and PR", "CHARGE", "62"),
            ("6271", "Annonces et insertions", "Advertisements", "CHARGE", "627"),
            ("6272", "Catalogues et imprimés publicitaires", "Catalogs and advertising", "CHARGE", "627"),
            ("6273", "Échantillons", "Samples", "CHARGE", "627"),
            ("6274", "Foires et expositions", "Fairs and exhibitions", "CHARGE", "627"),
            ("6275", "Publications", "Publications", "CHARGE", "627"),
            ("6276", "Cadeaux à la clientèle", "Customer gifts", "CHARGE", "627"),
            ("6278", "Autres charges de publicité", "Other advertising expenses", "CHARGE", "627"),
            ("628", "Frais de télécommunications", "Telecommunications expenses", "CHARGE", "62"),
            ("6281", "Frais de téléphone", "Telephone expenses", "CHARGE", "628"),
            ("6282", "Frais de télex", "Telex expenses", "CHARGE", "628"),
            ("6283", "Frais de télécopie", "Fax expenses", "CHARGE", "628"),
            ("6284", "Frais d'internet", "Internet expenses", "CHARGE", "628"),
            ("6288", "Autres frais de télécommunications", "Other telecommunications", "CHARGE", "628"),
            ("63", "Services extérieurs B", "External services B", "CHARGE", "6"),
            ("631", "Frais bancaires", "Bank charges", "CHARGE", "63"),
            ("6311", "Frais sur titres", "Securities charges", "CHARGE", "631"),
            ("6312", "Frais sur effets", "Notes charges", "CHARGE", "631"),
            ("6313", "Locations de coffres", "Safe deposit box rental", "CHARGE", "631"),
            ("6314", "Commissions sur cartes de crédit", "Credit card commissions", "CHARGE", "631"),
            ("6318", "Autres frais bancaires", "Other bank charges", "CHARGE", "631"),
            ("632", "Rémunérations d'intermédiaires et de conseils", "Intermediary fees", "CHARGE", "63"),
            ("6321", "Commissions et courtages sur achats", "Purchase commissions", "CHARGE", "632"),
            ("6322", "Commissions et courtages sur ventes", "Sales commissions", "CHARGE", "632"),
            ("6323", "Rémunérations des transitaires", "Forwarding agent fees", "CHARGE", "632"),
            ("6324", "Honoraires", "Professional fees", "CHARGE", "632"),
            ("6325", "Frais d'actes et de contentieux", "Legal fees", "CHARGE", "632"),
            ("6328", "Divers frais", "Miscellaneous fees", "CHARGE", "632"),
            ("633", "Frais de formation du personnel", "Staff training expenses", "CHARGE", "63"),
            ("634", "Redevances pour brevets, licences, logiciels", "Royalties", "CHARGE", "63"),
            ("6341", "Redevances pour brevets", "Patent royalties", "CHARGE", "634"),
            ("6342", "Redevances pour licences", "License royalties", "CHARGE", "634"),
            ("6343", "Redevances pour logiciels", "Software royalties", "CHARGE", "634"),
            ("6344", "Redevances pour marques", "Trademark royalties", "CHARGE", "634"),
            ("635", "Cotisations", "Membership fees", "CHARGE", "63"),
            ("637", "Rémunérations de personnel extérieur", "External staff compensation", "CHARGE", "63"),
            ("6371", "Personnel intérimaire", "Temporary staff", "CHARGE", "637"),
            ("6372", "Personnel détaché ou prêté", "Seconded staff", "CHARGE", "637"),
            ("638", "Autres charges externes", "Other external charges", "CHARGE", "63"),
            ("6381", "Frais de recrutement", "Recruitment expenses", "CHARGE", "638"),
            ("6382", "Frais de déménagement", "Moving expenses", "CHARGE", "638"),
            ("6383", "Réceptions", "Entertainment expenses", "CHARGE", "638"),
            ("6384", "Missions", "Mission expenses", "CHARGE", "638"),
            ("6388", "Autres charges externes", "Other external charges", "CHARGE", "638"),
            ("64", "Impôts et taxes", "Taxes and duties", "CHARGE", "6"),
            ("641", "Impôts et taxes directs", "Direct taxes", "CHARGE", "64"),
            ("6411", "Impôts fonciers", "Property taxes", "CHARGE", "641"),
            ("6412", "Patentes et licences", "Business licenses", "CHARGE", "641"),
            ("6413", "Taxes sur appointements et salaires", "Payroll taxes", "CHARGE", "641"),
            ("6414", "Taxes d'apprentissage", "Apprenticeship taxes", "CHARGE", "641"),
            ("6418", "Autres impôts directs", "Other direct taxes", "CHARGE", "641"),
            ("645", "Impôts et taxes indirects", "Indirect taxes", "CHARGE", "64"),
            ("646", "Droits d'enregistrement", "Registration duties", "CHARGE", "64"),
            ("6461", "Droits de mutation", "Transfer duties", "CHARGE", "646"),
            ("6462", "Droits de timbre", "Stamp duties", "CHARGE", "646"),
            ("647", "Pénalités et amendes fiscales", "Tax penalties", "CHARGE", "64"),
            ("648", "Autres impôts et taxes", "Other taxes", "CHARGE", "64"),
            ("65", "Autres charges", "Other operating expenses", "CHARGE", "6"),
            ("651", "Pertes sur créances clients", "Bad debt losses", "CHARGE", "65"),
            ("6511", "Pertes sur créances clients", "Customer bad debts", "CHARGE", "651"),
            ("6515", "Pertes sur créances douteuses", "Doubtful debt losses", "CHARGE", "651"),
            ("652", "Quote-part de résultat sur opérations en commun", "Share of joint operations result", "CHARGE", "65"),
            ("654", "Valeurs comptables des cessions courantes", "Book value of current disposals", "CHARGE", "65"),
            ("656", "Pertes de change sur créances commerciales", "Exchange losses on receivables", "CHARGE", "65"),
            ("658", "Charges diverses", "Miscellaneous expenses", "CHARGE", "65"),
            ("6581", "Jetons de présence", "Directors fees", "CHARGE", "658"),
            ("6583", "Dons", "Donations", "CHARGE", "658"),
            ("6584", "Mécénat", "Sponsorship", "CHARGE", "658"),
            ("6588", "Autres charges diverses", "Other miscellaneous", "CHARGE", "658"),
            ("659", "Charges provisionnées d'exploitation", "Provisioned operating expenses", "CHARGE", "65"),
            ("66", "Charges de personnel", "Personnel expenses", "CHARGE", "6"),
            ("661", "Rémunérations du personnel national", "National staff compensation", "CHARGE", "66"),
            ("6611", "Appointements, salaires et commissions", "Wages and salaries", "CHARGE", "661"),
            ("6612", "Primes et gratifications", "Bonuses", "CHARGE", "661"),
            ("6613", "Congés payés", "Paid leave", "CHARGE", "661"),
            ("6614", "Indemnités de préavis et licenciement", "Severance pay", "CHARGE", "661"),
            ("6615", "Indemnités de maladie", "Sick pay", "CHARGE", "661"),
            ("6617", "Avantages en nature", "Benefits in kind", "CHARGE", "661"),
            ("6618", "Autres rémunérations", "Other compensation", "CHARGE", "661"),
            ("662", "Rémunérations du personnel non national", "Non-national staff compensation", "CHARGE", "66"),
            ("663", "Indemnités forfaitaires", "Flat-rate allowances", "CHARGE", "66"),
            ("6631", "Indemnités de logement", "Housing allowances", "CHARGE", "663"),
            ("6632", "Indemnités de représentation", "Representation allowances", "CHARGE", "663"),
            ("6633", "Indemnités d'expatriation", "Expatriation allowances", "CHARGE", "663"),
            ("6634", "Indemnités de transport", "Transport allowances", "CHARGE", "663"),
            ("664", "Charges sociales", "Social security charges", "CHARGE", "66"),
            ("6641", "Charges sociales sur personnel national", "National staff social charges", "CHARGE", "664"),
            ("6642", "Charges sociales sur personnel non national", "Non-national staff social charges", "CHARGE", "664"),
            ("666", "Rémunération de l'exploitant", "Owner's compensation", "CHARGE", "66"),
            ("667", "Rémunération transférée de personnel extérieur", "Transferred external staff", "CHARGE", "66"),
            ("668", "Autres charges sociales", "Other social charges", "CHARGE", "66"),
            ("6681", "Versements aux syndicats", "Union payments", "CHARGE", "668"),
            ("6682", "Versements aux comités d'hygiène", "Health committee payments", "CHARGE", "668"),
            ("6683", "Versements aux œuvres sociales", "Social welfare payments", "CHARGE", "668"),
            ("6684", "Médecine du travail", "Occupational health", "CHARGE", "668"),
            ("67", "Frais financiers et charges assimilées", "Financial expenses", "CHARGE", "6"),
            ("671", "Intérêts des emprunts", "Interest on borrowings", "CHARGE", "67"),
            ("6711", "Intérêts des emprunts obligataires", "Bond interest", "CHARGE", "671"),
            ("6712", "Intérêts des emprunts bancaires", "Bank loan interest", "CHARGE", "671"),
            ("6713", "Intérêts des avances reçues", "Interest on advances", "CHARGE", "671"),
            ("672", "Intérêts dans loyers de crédit-bail", "Finance lease interest", "CHARGE", "67"),
            ("673", "Escomptes accordés", "Discounts allowed", "CHARGE", "67"),
            ("674", "Autres intérêts", "Other interest", "CHARGE", "67"),
            ("676", "Pertes de change financières", "Financial exchange losses", "CHARGE", "67"),
            ("677", "Pertes sur cessions de titres de placement", "Losses on securities", "CHARGE", "67"),
            ("678", "Pertes sur risques financiers", "Financial risk losses", "CHARGE", "67"),
            ("679", "Charges provisionnées financières", "Provisioned financial charges", "CHARGE", "67"),
            ("68", "Dotations aux amortissements", "Depreciation charges", "CHARGE", "6"),
            ("681", "Dotations aux amortissements d'exploitation", "Operating depreciation", "CHARGE", "68"),
            ("6812", "Dotations aux amortissements des immobilisations incorporelles", "Intangible assets amortization", "CHARGE", "681"),
            ("6813", "Dotations aux amortissements des immobilisations corporelles", "Tangible assets depreciation", "CHARGE", "681"),
            ("69", "Dotations aux provisions", "Provision charges", "CHARGE", "6"),
            ("691", "Dotations aux provisions d'exploitation", "Operating provisions", "CHARGE", "69"),
            ("6911", "Dotations aux provisions pour risques", "Provisions for risks", "CHARGE", "691"),
            ("6913", "Dotations pour dépréciation des immobilisations", "Impairment provisions", "CHARGE", "691"),
            ("6914", "Dotations pour dépréciation des stocks", "Inventory impairment", "CHARGE", "691"),
            ("697", "Dotations aux provisions financières", "Financial provisions", "CHARGE", "69"),

            # ═══════════════════════════════════════════════════════════════════════
            # CLASSE 7 - COMPTES DE PRODUITS DES ACTIVITÉS ORDINAIRES
            # ═══════════════════════════════════════════════════════════════════════
            ("7", "Comptes de produits des activités ordinaires", "Operating income accounts", "PRODUIT", None),
            ("70", "Ventes", "Sales", "PRODUIT", "7"),
            ("701", "Ventes de marchandises", "Sales of merchandise", "PRODUIT", "70"),
            ("7019", "Rabais, remises et ristournes accordés", "Rebates allowed", "PRODUIT", "701"),
            ("702", "Ventes de produits finis", "Sales of finished goods", "PRODUIT", "70"),
            ("7029", "Rabais, remises et ristournes accordés", "Rebates allowed", "PRODUIT", "702"),
            ("703", "Ventes de produits intermédiaires", "Sales of intermediate products", "PRODUIT", "70"),
            ("704", "Ventes de produits résiduels", "Sales of residual products", "PRODUIT", "70"),
            ("705", "Travaux facturés", "Work invoiced", "PRODUIT", "70"),
            ("706", "Services vendus", "Services sold", "PRODUIT", "70"),
            ("707", "Produits accessoires", "Ancillary products", "PRODUIT", "70"),
            ("7071", "Ports et frais facturés", "Shipping charges invoiced", "PRODUIT", "707"),
            ("7072", "Commissions et courtages", "Commissions", "PRODUIT", "707"),
            ("7073", "Locations", "Rentals", "PRODUIT", "707"),
            ("7074", "Bonis sur reprises d'emballages", "Packaging return gains", "PRODUIT", "707"),
            ("7075", "Mise à disposition de personnel", "Staff secondment", "PRODUIT", "707"),
            ("7076", "Redevances perçues", "Royalties received", "PRODUIT", "707"),
            ("7078", "Autres produits accessoires", "Other ancillary products", "PRODUIT", "707"),
            ("71", "Subventions d'exploitation", "Operating subsidies", "PRODUIT", "7"),
            ("711", "Subventions sur produits à l'exportation", "Export subsidies", "PRODUIT", "71"),
            ("712", "Subventions sur produits à l'importation", "Import subsidies", "PRODUIT", "71"),
            ("718", "Autres subventions d'exploitation", "Other operating subsidies", "PRODUIT", "71"),
            ("72", "Production immobilisée", "Capitalized production", "PRODUIT", "7"),
            ("721", "Immobilisations incorporelles", "Intangible assets", "PRODUIT", "72"),
            ("722", "Immobilisations corporelles", "Tangible assets", "PRODUIT", "72"),
            ("73", "Variations des stocks de biens produits", "Changes in produced goods inventory", "PRODUIT", "7"),
            ("734", "Variations des stocks de produits en cours", "Changes in WIP inventory", "PRODUIT", "73"),
            ("735", "Variations des en-cours de services", "Changes in services in progress", "PRODUIT", "73"),
            ("736", "Variations des stocks de produits finis", "Changes in finished goods inventory", "PRODUIT", "73"),
            ("737", "Variations des stocks de produits intermédiaires", "Changes in intermediate products", "PRODUIT", "73"),
            ("75", "Autres produits", "Other income", "PRODUIT", "7"),
            ("752", "Quote-part de résultat sur opérations en commun", "Share of joint operations result", "PRODUIT", "75"),
            ("754", "Produits des cessions courantes d'immobilisations", "Current disposal proceeds", "PRODUIT", "75"),
            ("756", "Gains de change sur créances commerciales", "Exchange gains on receivables", "PRODUIT", "75"),
            ("758", "Produits divers", "Miscellaneous income", "PRODUIT", "75"),
            ("7581", "Jetons de présence perçus", "Directors fees received", "PRODUIT", "758"),
            ("7582", "Indemnités d'assurances", "Insurance compensation", "PRODUIT", "758"),
            ("7588", "Autres produits divers", "Other miscellaneous income", "PRODUIT", "758"),
            ("759", "Reprises de charges provisionnées", "Reversals of provisions", "PRODUIT", "75"),
            ("77", "Revenus financiers et produits assimilés", "Financial income", "PRODUIT", "7"),
            ("771", "Intérêts de prêts", "Interest on loans", "PRODUIT", "77"),
            ("772", "Revenus de participations", "Investment income", "PRODUIT", "77"),
            ("773", "Escomptes obtenus", "Discounts obtained", "PRODUIT", "77"),
            ("774", "Revenus de titres de placement", "Marketable securities income", "PRODUIT", "77"),
            ("776", "Gains de change financiers", "Financial exchange gains", "PRODUIT", "77"),
            ("777", "Gains sur cessions de titres", "Gains on securities disposal", "PRODUIT", "77"),
            ("778", "Gains sur risques financiers", "Financial risk gains", "PRODUIT", "77"),
            ("779", "Reprises de charges financières", "Reversals of financial charges", "PRODUIT", "77"),
            ("78", "Transferts de charges", "Charge transfers", "PRODUIT", "7"),
            ("781", "Transferts de charges d'exploitation", "Operating charge transfers", "PRODUIT", "78"),
            ("787", "Transferts de charges financières", "Financial charge transfers", "PRODUIT", "78"),
            ("79", "Reprises de provisions et dépréciations", "Reversals of provisions", "PRODUIT", "7"),
            ("791", "Reprises de provisions d'exploitation", "Operating provision reversals", "PRODUIT", "79"),
            ("797", "Reprises de provisions financières", "Financial provision reversals", "PRODUIT", "79"),
            ("798", "Reprises d'amortissements", "Depreciation reversals", "PRODUIT", "79"),
            ("799", "Reprises de subventions d'investissement", "Investment grant reversals", "PRODUIT", "79"),

            # ═══════════════════════════════════════════════════════════════════════
            # CLASSE 8 - AUTRES CHARGES ET AUTRES PRODUITS
            # ═══════════════════════════════════════════════════════════════════════
            ("8", "Comptes des autres charges et autres produits", "Other expenses and income", "CHARGE", None),
            ("81", "Valeurs comptables des cessions d'immobilisations", "Book value of asset disposals", "CHARGE", "8"),
            ("811", "Immobilisations incorporelles", "Intangible assets", "CHARGE", "81"),
            ("812", "Immobilisations corporelles", "Tangible assets", "CHARGE", "81"),
            ("816", "Immobilisations financières", "Financial assets", "CHARGE", "81"),
            ("82", "Produits des cessions d'immobilisations", "Proceeds from asset disposals", "PRODUIT", "8"),
            ("821", "Immobilisations incorporelles", "Intangible assets", "PRODUIT", "82"),
            ("822", "Immobilisations corporelles", "Tangible assets", "PRODUIT", "82"),
            ("826", "Immobilisations financières", "Financial assets", "PRODUIT", "82"),
            ("83", "Charges HAO", "Non-operating expenses", "CHARGE", "8"),
            ("831", "Charges HAO constatées", "Recognized non-operating expenses", "CHARGE", "83"),
            ("834", "Pertes sur créances HAO", "Non-operating bad debts", "CHARGE", "83"),
            ("835", "Dons et libéralités accordés", "Gifts given", "CHARGE", "83"),
            ("836", "Abandons de créances consentis", "Debt write-offs given", "CHARGE", "83"),
            ("839", "Charges provisionnées HAO", "Provisioned non-operating expenses", "CHARGE", "83"),
            ("84", "Produits HAO", "Non-operating income", "PRODUIT", "8"),
            ("841", "Produits HAO constatés", "Recognized non-operating income", "PRODUIT", "84"),
            ("845", "Dons et libéralités obtenus", "Gifts received", "PRODUIT", "84"),
            ("846", "Abandons de créances obtenus", "Debt write-offs received", "PRODUIT", "84"),
            ("848", "Transferts de charges HAO", "Non-operating charge transfers", "PRODUIT", "84"),
            ("849", "Reprises de charges provisionnées HAO", "Non-operating provision reversals", "PRODUIT", "84"),
            ("85", "Dotations HAO", "Non-operating provisions", "CHARGE", "8"),
            ("851", "Dotations aux provisions réglementées", "Regulated provisions", "CHARGE", "85"),
            ("852", "Dotations aux amortissements HAO", "Non-operating depreciation", "CHARGE", "85"),
            ("853", "Dotations aux dépréciations HAO", "Non-operating impairment", "CHARGE", "85"),
            ("86", "Reprises HAO", "Non-operating reversals", "PRODUIT", "8"),
            ("861", "Reprises de provisions réglementées", "Regulated provision reversals", "PRODUIT", "86"),
            ("862", "Reprises d'amortissements HAO", "Non-operating depreciation reversals", "PRODUIT", "86"),
            ("863", "Reprises de dépréciations HAO", "Non-operating impairment reversals", "PRODUIT", "86"),
            ("87", "Participation des travailleurs", "Employee profit sharing", "CHARGE", "8"),
            ("871", "Participation légale aux bénéfices", "Legal profit sharing", "CHARGE", "87"),
            ("874", "Participation contractuelle aux bénéfices", "Contractual profit sharing", "CHARGE", "87"),
            ("88", "Subventions d'équilibre", "Balancing subsidies", "PRODUIT", "8"),
            ("881", "État", "State", "PRODUIT", "88"),
            ("886", "Groupe", "Group", "PRODUIT", "88"),
            ("89", "Impôts sur le résultat", "Income taxes", "CHARGE", "8"),
            ("891", "Impôts sur les bénéfices de l'exercice", "Income tax for the year", "CHARGE", "89"),
            ("892", "Rappel d'impôts sur résultats antérieurs", "Prior year tax adjustments", "CHARGE", "89"),
            ("895", "Impôt minimum forfaitaire (IMF)", "Minimum flat tax", "CHARGE", "89"),
            ("899", "Dégrèvements d'impôts sur résultats", "Tax rebates", "PRODUIT", "89"),

            # ═══════════════════════════════════════════════════════════════════════
            # CLASSE 9 - ENGAGEMENTS HORS BILAN
            # ═══════════════════════════════════════════════════════════════════════
            ("9", "Comptes des engagements hors bilan", "Off-balance sheet commitments", "ACTIF", None),
            ("90", "Engagements obtenus et accordés", "Commitments obtained and given", "ACTIF", "9"),
            ("901", "Engagements de financement obtenus", "Financing commitments obtained", "ACTIF", "90"),
            ("902", "Engagements de garantie obtenus", "Guarantee commitments obtained", "ACTIF", "90"),
            ("905", "Engagements de financement accordés", "Financing commitments given", "PASSIF", "90"),
            ("906", "Engagements de garantie accordés", "Guarantee commitments given", "PASSIF", "90"),
            ("91", "Contreparties des engagements", "Counterparties of commitments", "ACTIF", "9"),
        ]

        # Convertir les tuples en format dict attendu par _create_accounts
        accounts = []
        for row in raw_data:
            code, label_fr, label_en, type_compte, parent = row
            accounts.append({
                "code": code,
                "labels": {"fr": label_fr, "en": label_en},
                "type": type_compte,
                "classe": int(code[0]) if code else 1,
                "parent": parent,
            })
        return accounts
